// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAPITokenRepository creates a new instance of APITokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPITokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *APITokenRepository {
	mock := &APITokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APITokenRepository is an autogenerated mock type for the APITokenRepository type
type APITokenRepository struct {
	mock.Mock
}

type APITokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *APITokenRepository) EXPECT() *APITokenRepository_Expecter {
	return &APITokenRepository_Expecter{mock: &_m.Mock}
}

// CountUserActiveAPITokens provides a mock function for the type APITokenRepository
func (_mock *APITokenRepository) CountUserActiveAPITokens(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUserActiveAPITokens")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APITokenRepository_CountUserActiveAPITokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserActiveAPITokens'
type APITokenRepository_CountUserActiveAPITokens_Call struct {
	*mock.Call
}

// CountUserActiveAPITokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *APITokenRepository_Expecter) CountUserActiveAPITokens(ctx interface{}, userID interface{}) *APITokenRepository_CountUserActiveAPITokens_Call {
	return &APITokenRepository_CountUserActiveAPITokens_Call{Call: _e.mock.On("CountUserActiveAPITokens", ctx, userID)}
}

func (_c *APITokenRepository_CountUserActiveAPITokens_Call) Run(run func(ctx context.Context, userID string)) *APITokenRepository_CountUserActiveAPITokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APITokenRepository_CountUserActiveAPITokens_Call) Return(n int64, err error) *APITokenRepository_CountUserActiveAPITokens_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *APITokenRepository_CountUserActiveAPITokens_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *APITokenRepository_CountUserActiveAPITokens_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAPIToken provides a mock function for the type APITokenRepository
func (_mock *APITokenRepository) CreateAPIToken(ctx context.Context, params datasources.CreateAPITokenParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datasources.CreateAPITokenParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APITokenRepository_CreateAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIToken'
type APITokenRepository_CreateAPIToken_Call struct {
	*mock.Call
}

// CreateAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
//   - tokenHash string
//   - tokenPrefix string
//   - name *string
//   - expiresAt *time.Time
func (_e *APITokenRepository_Expecter) CreateAPIToken(ctx interface{}, params interface{}) *APITokenRepository_CreateAPIToken_Call {
	return &APITokenRepository_CreateAPIToken_Call{Call: _e.mock.On("CreateAPIToken", ctx, params)}
}

func (_c *APITokenRepository_CreateAPIToken_Call) Run(run func(ctx context.Context, params datasources.CreateAPITokenParams)) *APITokenRepository_CreateAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(datasources.CreateAPITokenParams))
	})
	return _c
}

func (_c *APITokenRepository_CreateAPIToken_Call) Return(err error) *APITokenRepository_CreateAPIToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APITokenRepository_CreateAPIToken_Call) RunAndReturn(run func(ctx context.Context, params datasources.CreateAPITokenParams) error) *APITokenRepository_CreateAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAPITokenByHash provides a mock function for the type APITokenRepository
func (_mock *APITokenRepository) GetAPITokenByHash(ctx context.Context, tokenHash string) (domain.APIToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetAPITokenByHash")
	}

	var r0 domain.APIToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.APIToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.APIToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(domain.APIToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APITokenRepository_GetAPITokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPITokenByHash'
type APITokenRepository_GetAPITokenByHash_Call struct {
	*mock.Call
}

// GetAPITokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *APITokenRepository_Expecter) GetAPITokenByHash(ctx interface{}, tokenHash interface{}) *APITokenRepository_GetAPITokenByHash_Call {
	return &APITokenRepository_GetAPITokenByHash_Call{Call: _e.mock.On("GetAPITokenByHash", ctx, tokenHash)}
}

func (_c *APITokenRepository_GetAPITokenByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *APITokenRepository_GetAPITokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APITokenRepository_GetAPITokenByHash_Call) Return(aPIToken domain.APIToken, err error) *APITokenRepository_GetAPITokenByHash_Call {
	_c.Call.Return(aPIToken, err)
	return _c
}

func (_c *APITokenRepository_GetAPITokenByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (domain.APIToken, error)) *APITokenRepository_GetAPITokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserAPITokens provides a mock function for the type APITokenRepository
func (_mock *APITokenRepository) ListUserAPITokens(ctx context.Context, userID string) ([]domain.APIToken, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserAPITokens")
	}

	var r0 []domain.APIToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.APIToken, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.APIToken); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.APIToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APITokenRepository_ListUserAPITokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserAPITokens'
type APITokenRepository_ListUserAPITokens_Call struct {
	*mock.Call
}

// ListUserAPITokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *APITokenRepository_Expecter) ListUserAPITokens(ctx interface{}, userID interface{}) *APITokenRepository_ListUserAPITokens_Call {
	return &APITokenRepository_ListUserAPITokens_Call{Call: _e.mock.On("ListUserAPITokens", ctx, userID)}
}

func (_c *APITokenRepository_ListUserAPITokens_Call) Run(run func(ctx context.Context, userID string)) *APITokenRepository_ListUserAPITokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APITokenRepository_ListUserAPITokens_Call) Return(aPITokens []domain.APIToken, err error) *APITokenRepository_ListUserAPITokens_Call {
	_c.Call.Return(aPITokens, err)
	return _c
}

func (_c *APITokenRepository_ListUserAPITokens_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]domain.APIToken, error)) *APITokenRepository_ListUserAPITokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAPIToken provides a mock function for the type APITokenRepository
func (_mock *APITokenRepository) RevokeAPIToken(ctx context.Context, tokenID string, userID string) error {
	ret := _mock.Called(ctx, tokenID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAPIToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, tokenID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APITokenRepository_RevokeAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAPIToken'
type APITokenRepository_RevokeAPIToken_Call struct {
	*mock.Call
}

// RevokeAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - userID string
func (_e *APITokenRepository_Expecter) RevokeAPIToken(ctx interface{}, tokenID interface{}, userID interface{}) *APITokenRepository_RevokeAPIToken_Call {
	return &APITokenRepository_RevokeAPIToken_Call{Call: _e.mock.On("RevokeAPIToken", ctx, tokenID, userID)}
}

func (_c *APITokenRepository_RevokeAPIToken_Call) Run(run func(ctx context.Context, tokenID string, userID string)) *APITokenRepository_RevokeAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *APITokenRepository_RevokeAPIToken_Call) Return(err error) *APITokenRepository_RevokeAPIToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APITokenRepository_RevokeAPIToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string, userID string) error) *APITokenRepository_RevokeAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAPITokenLastUsed provides a mock function for the type APITokenRepository
func (_mock *APITokenRepository) UpdateAPITokenLastUsed(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAPITokenLastUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APITokenRepository_UpdateAPITokenLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAPITokenLastUsed'
type APITokenRepository_UpdateAPITokenLastUsed_Call struct {
	*mock.Call
}

// UpdateAPITokenLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *APITokenRepository_Expecter) UpdateAPITokenLastUsed(ctx interface{}, tokenID interface{}) *APITokenRepository_UpdateAPITokenLastUsed_Call {
	return &APITokenRepository_UpdateAPITokenLastUsed_Call{Call: _e.mock.On("UpdateAPITokenLastUsed", ctx, tokenID)}
}

func (_c *APITokenRepository_UpdateAPITokenLastUsed_Call) Run(run func(ctx context.Context, tokenID string)) *APITokenRepository_UpdateAPITokenLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APITokenRepository_UpdateAPITokenLastUsed_Call) Return(err error) *APITokenRepository_UpdateAPITokenLastUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APITokenRepository_UpdateAPITokenLastUsed_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *APITokenRepository_UpdateAPITokenLastUsed_Call {
	_c.Call.Return(run)
	return _c
}
