// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAPITokenByHashGetter creates a new instance of APITokenByHashGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPITokenByHashGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *APITokenByHashGetter {
	mock := &APITokenByHashGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APITokenByHashGetter is an autogenerated mock type for the APITokenByHashGetter type
type APITokenByHashGetter struct {
	mock.Mock
}

type APITokenByHashGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *APITokenByHashGetter) EXPECT() *APITokenByHashGetter_Expecter {
	return &APITokenByHashGetter_Expecter{mock: &_m.Mock}
}

// GetAPITokenByHash provides a mock function for the type APITokenByHashGetter
func (_mock *APITokenByHashGetter) GetAPITokenByHash(ctx context.Context, tokenHash string) (domain.APIToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetAPITokenByHash")
	}

	var r0 domain.APIToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.APIToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.APIToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(domain.APIToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APITokenByHashGetter_GetAPITokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPITokenByHash'
type APITokenByHashGetter_GetAPITokenByHash_Call struct {
	*mock.Call
}

// GetAPITokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *APITokenByHashGetter_Expecter) GetAPITokenByHash(ctx interface{}, tokenHash interface{}) *APITokenByHashGetter_GetAPITokenByHash_Call {
	return &APITokenByHashGetter_GetAPITokenByHash_Call{Call: _e.mock.On("GetAPITokenByHash", ctx, tokenHash)}
}

func (_c *APITokenByHashGetter_GetAPITokenByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *APITokenByHashGetter_GetAPITokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APITokenByHashGetter_GetAPITokenByHash_Call) Return(aPIToken domain.APIToken, err error) *APITokenByHashGetter_GetAPITokenByHash_Call {
	_c.Call.Return(aPIToken, err)
	return _c
}

func (_c *APITokenByHashGetter_GetAPITokenByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (domain.APIToken, error)) *APITokenByHashGetter_GetAPITokenByHash_Call {
	_c.Call.Return(run)
	return _c
}
