// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAPITokenLastUsedUpdater creates a new instance of APITokenLastUsedUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPITokenLastUsedUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *APITokenLastUsedUpdater {
	mock := &APITokenLastUsedUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APITokenLastUsedUpdater is an autogenerated mock type for the APITokenLastUsedUpdater type
type APITokenLastUsedUpdater struct {
	mock.Mock
}

type APITokenLastUsedUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *APITokenLastUsedUpdater) EXPECT() *APITokenLastUsedUpdater_Expecter {
	return &APITokenLastUsedUpdater_Expecter{mock: &_m.Mock}
}

// UpdateAPITokenLastUsed provides a mock function for the type APITokenLastUsedUpdater
func (_mock *APITokenLastUsedUpdater) UpdateAPITokenLastUsed(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAPITokenLastUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAPITokenLastUsed'
type APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call struct {
	*mock.Call
}

// UpdateAPITokenLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *APITokenLastUsedUpdater_Expecter) UpdateAPITokenLastUsed(ctx interface{}, tokenID interface{}) *APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call {
	return &APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call{Call: _e.mock.On("UpdateAPITokenLastUsed", ctx, tokenID)}
}

func (_c *APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call) Run(run func(ctx context.Context, tokenID string)) *APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call) Return(err error) *APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *APITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call {
	_c.Call.Return(run)
	return _c
}
