// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// NewAPITokenCreator creates a new instance of APITokenCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPITokenCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *APITokenCreator {
	mock := &APITokenCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APITokenCreator is an autogenerated mock type for the APITokenCreator type
type APITokenCreator struct {
	mock.Mock
}

type APITokenCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *APITokenCreator) EXPECT() *APITokenCreator_Expecter {
	return &APITokenCreator_Expecter{mock: &_m.Mock}
}

// CreateAPIToken provides a mock function for the type APITokenCreator
func (_mock *APITokenCreator) CreateAPIToken(ctx context.Context, params datasources.CreateAPITokenParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datasources.CreateAPITokenParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APITokenCreator_CreateAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIToken'
type APITokenCreator_CreateAPIToken_Call struct {
	*mock.Call
}

// CreateAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - params datasources.CreateAPITokenParams
func (_e *APITokenCreator_Expecter) CreateAPIToken(ctx interface{}, params interface{}) *APITokenCreator_CreateAPIToken_Call {
	return &APITokenCreator_CreateAPIToken_Call{Call: _e.mock.On("CreateAPIToken", ctx, params)}
}

func (_c *APITokenCreator_CreateAPIToken_Call) Run(run func(ctx context.Context, params datasources.CreateAPITokenParams)) *APITokenCreator_CreateAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(datasources.CreateAPITokenParams))
	})
	return _c
}

func (_c *APITokenCreator_CreateAPIToken_Call) Return(err error) *APITokenCreator_CreateAPIToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APITokenCreator_CreateAPIToken_Call) RunAndReturn(run func(ctx context.Context, params datasources.CreateAPITokenParams) error) *APITokenCreator_CreateAPIToken_Call {
	_c.Call.Return(run)
	return _c
}
