// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAPITokenRevoker creates a new instance of APITokenRevoker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPITokenRevoker(t interface {
	mock.TestingT
	Cleanup(func())
}) *APITokenRevoker {
	mock := &APITokenRevoker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APITokenRevoker is an autogenerated mock type for the APITokenRevoker type
type APITokenRevoker struct {
	mock.Mock
}

type APITokenRevoker_Expecter struct {
	mock *mock.Mock
}

func (_m *APITokenRevoker) EXPECT() *APITokenRevoker_Expecter {
	return &APITokenRevoker_Expecter{mock: &_m.Mock}
}

// RevokeAPIToken provides a mock function for the type APITokenRevoker
func (_mock *APITokenRevoker) RevokeAPIToken(ctx context.Context, tokenID string, userID string) error {
	ret := _mock.Called(ctx, tokenID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAPIToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, tokenID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APITokenRevoker_RevokeAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAPIToken'
type APITokenRevoker_RevokeAPIToken_Call struct {
	*mock.Call
}

// RevokeAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - userID string
func (_e *APITokenRevoker_Expecter) RevokeAPIToken(ctx interface{}, tokenID interface{}, userID interface{}) *APITokenRevoker_RevokeAPIToken_Call {
	return &APITokenRevoker_RevokeAPIToken_Call{Call: _e.mock.On("RevokeAPIToken", ctx, tokenID, userID)}
}

func (_c *APITokenRevoker_RevokeAPIToken_Call) Run(run func(ctx context.Context, tokenID string, userID string)) *APITokenRevoker_RevokeAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *APITokenRevoker_RevokeAPIToken_Call) Return(err error) *APITokenRevoker_RevokeAPIToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APITokenRevoker_RevokeAPIToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string, userID string) error) *APITokenRevoker_RevokeAPIToken_Call {
	_c.Call.Return(run)
	return _c
}
