// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewArticleFetcher creates a new instance of ArticleFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArticleFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArticleFetcher {
	mock := &ArticleFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ArticleFetcher is an autogenerated mock type for the ArticleFetcher type
type ArticleFetcher struct {
	mock.Mock
}

type ArticleFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *ArticleFetcher) EXPECT() *ArticleFetcher_Expecter {
	return &ArticleFetcher_Expecter{mock: &_m.Mock}
}

// FetchArticlesByID provides a mock function for the type ArticleFetcher
func (_mock *ArticleFetcher) FetchArticlesByID(ctx context.Context, hashIDs []string) ([]domain.Article, error) {
	ret := _mock.Called(ctx, hashIDs)

	if len(ret) == 0 {
		panic("no return value specified for FetchArticlesByID")
	}

	var r0 []domain.Article
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]domain.Article, error)); ok {
		return returnFunc(ctx, hashIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []domain.Article); ok {
		r0 = returnFunc(ctx, hashIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Article)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, hashIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ArticleFetcher_FetchArticlesByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArticlesByID'
type ArticleFetcher_FetchArticlesByID_Call struct {
	*mock.Call
}

// FetchArticlesByID is a helper method to define mock.On call
//   - ctx context.Context
//   - hashIDs []string
func (_e *ArticleFetcher_Expecter) FetchArticlesByID(ctx interface{}, hashIDs interface{}) *ArticleFetcher_FetchArticlesByID_Call {
	return &ArticleFetcher_FetchArticlesByID_Call{Call: _e.mock.On("FetchArticlesByID", ctx, hashIDs)}
}

func (_c *ArticleFetcher_FetchArticlesByID_Call) Run(run func(ctx context.Context, hashIDs []string)) *ArticleFetcher_FetchArticlesByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ArticleFetcher_FetchArticlesByID_Call) Return(articles []domain.Article, err error) *ArticleFetcher_FetchArticlesByID_Call {
	_c.Call.Return(articles, err)
	return _c
}

func (_c *ArticleFetcher_FetchArticlesByID_Call) RunAndReturn(run func(ctx context.Context, hashIDs []string) ([]domain.Article, error)) *ArticleFetcher_FetchArticlesByID_Call {
	_c.Call.Return(run)
	return _c
}
