// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewArticleReadSetter creates a new instance of ArticleReadSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArticleReadSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArticleReadSetter {
	mock := &ArticleReadSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ArticleReadSetter is an autogenerated mock type for the ArticleReadSetter type
type ArticleReadSetter struct {
	mock.Mock
}

type ArticleReadSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *ArticleReadSetter) EXPECT() *ArticleReadSetter_Expecter {
	return &ArticleReadSetter_Expecter{mock: &_m.Mock}
}

// SetArticleRead provides a mock function for the type ArticleReadSetter
func (_mock *ArticleReadSetter) SetArticleRead(ctx context.Context, hashID string, userID string, read bool) error {
	ret := _mock.Called(ctx, hashID, userID, read)

	if len(ret) == 0 {
		panic("no return value specified for SetArticleRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = returnFunc(ctx, hashID, userID, read)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ArticleReadSetter_SetArticleRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArticleRead'
type ArticleReadSetter_SetArticleRead_Call struct {
	*mock.Call
}

// SetArticleRead is a helper method to define mock.On call
//   - ctx context.Context
//   - hashID string
//   - userID string
//   - read bool
func (_e *ArticleReadSetter_Expecter) SetArticleRead(ctx interface{}, hashID interface{}, userID interface{}, read interface{}) *ArticleReadSetter_SetArticleRead_Call {
	return &ArticleReadSetter_SetArticleRead_Call{Call: _e.mock.On("SetArticleRead", ctx, hashID, userID, read)}
}

func (_c *ArticleReadSetter_SetArticleRead_Call) Run(run func(ctx context.Context, hashID string, userID string, read bool)) *ArticleReadSetter_SetArticleRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ArticleReadSetter_SetArticleRead_Call) Return(err error) *ArticleReadSetter_SetArticleRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ArticleReadSetter_SetArticleRead_Call) RunAndReturn(run func(ctx context.Context, hashID string, userID string, read bool) error) *ArticleReadSetter_SetArticleRead_Call {
	_c.Call.Return(run)
	return _c
}
