// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewArticleVectorFetcher creates a new instance of ArticleVectorFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArticleVectorFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArticleVectorFetcher {
	mock := &ArticleVectorFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ArticleVectorFetcher is an autogenerated mock type for the ArticleVectorFetcher type
type ArticleVectorFetcher struct {
	mock.Mock
}

type ArticleVectorFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *ArticleVectorFetcher) EXPECT() *ArticleVectorFetcher_Expecter {
	return &ArticleVectorFetcher_Expecter{mock: &_m.Mock}
}

// FetchArticleVector provides a mock function for the type ArticleVectorFetcher
func (_mock *ArticleVectorFetcher) FetchArticleVector(ctx context.Context, hashID string) ([]float32, error) {
	ret := _mock.Called(ctx, hashID)

	if len(ret) == 0 {
		panic("no return value specified for FetchArticleVector")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return returnFunc(ctx, hashID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = returnFunc(ctx, hashID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hashID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ArticleVectorFetcher_FetchArticleVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArticleVector'
type ArticleVectorFetcher_FetchArticleVector_Call struct {
	*mock.Call
}

// FetchArticleVector is a helper method to define mock.On call
//   - ctx context.Context
//   - hashID string
func (_e *ArticleVectorFetcher_Expecter) FetchArticleVector(ctx interface{}, hashID interface{}) *ArticleVectorFetcher_FetchArticleVector_Call {
	return &ArticleVectorFetcher_FetchArticleVector_Call{Call: _e.mock.On("FetchArticleVector", ctx, hashID)}
}

func (_c *ArticleVectorFetcher_FetchArticleVector_Call) Run(run func(ctx context.Context, hashID string)) *ArticleVectorFetcher_FetchArticleVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ArticleVectorFetcher_FetchArticleVector_Call) Return(float32s []float32, err error) *ArticleVectorFetcher_FetchArticleVector_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *ArticleVectorFetcher_FetchArticleVector_Call) RunAndReturn(run func(ctx context.Context, hashID string) ([]float32, error)) *ArticleVectorFetcher_FetchArticleVector_Call {
	_c.Call.Return(run)
	return _c
}
