// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewArticleRatingSetter creates a new instance of ArticleRatingSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArticleRatingSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArticleRatingSetter {
	mock := &ArticleRatingSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ArticleRatingSetter is an autogenerated mock type for the ArticleRatingSetter type
type ArticleRatingSetter struct {
	mock.Mock
}

type ArticleRatingSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *ArticleRatingSetter) EXPECT() *ArticleRatingSetter_Expecter {
	return &ArticleRatingSetter_Expecter{mock: &_m.Mock}
}

// SetArticleRating provides a mock function for the type ArticleRatingSetter
func (_mock *ArticleRatingSetter) SetArticleRating(ctx context.Context, userID string, articleHashID string, thumbsUp bool, thumbsDown bool, vector []float32) error {
	ret := _mock.Called(ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)

	if len(ret) == 0 {
		panic("no return value specified for SetArticleRating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool, bool, []float32) error); ok {
		r0 = returnFunc(ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ArticleRatingSetter_SetArticleRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArticleRating'
type ArticleRatingSetter_SetArticleRating_Call struct {
	*mock.Call
}

// SetArticleRating is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - thumbsUp bool
//   - thumbsDown bool
//   - vector []float32
func (_e *ArticleRatingSetter_Expecter) SetArticleRating(ctx interface{}, userID interface{}, articleHashID interface{}, thumbsUp interface{}, thumbsDown interface{}, vector interface{}) *ArticleRatingSetter_SetArticleRating_Call {
	return &ArticleRatingSetter_SetArticleRating_Call{Call: _e.mock.On("SetArticleRating", ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)}
}

func (_c *ArticleRatingSetter_SetArticleRating_Call) Run(run func(ctx context.Context, userID string, articleHashID string, thumbsUp bool, thumbsDown bool, vector []float32)) *ArticleRatingSetter_SetArticleRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 []float32
		if args[5] != nil {
			arg5 = args[5].([]float32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ArticleRatingSetter_SetArticleRating_Call) Return(err error) *ArticleRatingSetter_SetArticleRating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ArticleRatingSetter_SetArticleRating_Call) RunAndReturn(run func(ctx context.Context, userID string, articleHashID string, thumbsUp bool, thumbsDown bool, vector []float32) error) *ArticleRatingSetter_SetArticleRating_Call {
	_c.Call.Return(run)
	return _c
}
