// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewDislikedArticleLister creates a new instance of DislikedArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDislikedArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *DislikedArticleLister {
	mock := &DislikedArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DislikedArticleLister is an autogenerated mock type for the DislikedArticleLister type
type DislikedArticleLister struct {
	mock.Mock
}

type DislikedArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *DislikedArticleLister) EXPECT() *DislikedArticleLister_Expecter {
	return &DislikedArticleLister_Expecter{mock: &_m.Mock}
}

// ListDislikedArticleIDs provides a mock function for the type DislikedArticleLister
func (_mock *DislikedArticleLister) ListDislikedArticleIDs(ctx context.Context, userID string, page int, pageSize int) ([]string, error) {
	ret := _mock.Called(ctx, userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListDislikedArticleIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]string, error)); ok {
		return returnFunc(ctx, userID, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []string); ok {
		r0 = returnFunc(ctx, userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, userID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DislikedArticleLister_ListDislikedArticleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDislikedArticleIDs'
type DislikedArticleLister_ListDislikedArticleIDs_Call struct {
	*mock.Call
}

// ListDislikedArticleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - pageSize int
func (_e *DislikedArticleLister_Expecter) ListDislikedArticleIDs(ctx interface{}, userID interface{}, page interface{}, pageSize interface{}) *DislikedArticleLister_ListDislikedArticleIDs_Call {
	return &DislikedArticleLister_ListDislikedArticleIDs_Call{Call: _e.mock.On("ListDislikedArticleIDs", ctx, userID, page, pageSize)}
}

func (_c *DislikedArticleLister_ListDislikedArticleIDs_Call) Run(run func(ctx context.Context, userID string, page int, pageSize int)) *DislikedArticleLister_ListDislikedArticleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DislikedArticleLister_ListDislikedArticleIDs_Call) Return(strings []string, err error) *DislikedArticleLister_ListDislikedArticleIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *DislikedArticleLister_ListDislikedArticleIDs_Call) RunAndReturn(run func(ctx context.Context, userID string, page int, pageSize int) ([]string, error)) *DislikedArticleLister_ListDislikedArticleIDs_Call {
	_c.Call.Return(run)
	return _c
}
