// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewLatestArticleLister creates a new instance of LatestArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLatestArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *LatestArticleLister {
	mock := &LatestArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LatestArticleLister is an autogenerated mock type for the LatestArticleLister type
type LatestArticleLister struct {
	mock.Mock
}

type LatestArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *LatestArticleLister) EXPECT() *LatestArticleLister_Expecter {
	return &LatestArticleLister_Expecter{mock: &_m.Mock}
}

// ListLatestArticleIDs provides a mock function for the type LatestArticleLister
func (_mock *LatestArticleLister) ListLatestArticleIDs(ctx context.Context, filters domain.ArticleFilters, options domain.ArticleListOptions) ([]string, error) {
	ret := _mock.Called(ctx, filters, options)

	if len(ret) == 0 {
		panic("no return value specified for ListLatestArticleIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ArticleFilters, domain.ArticleListOptions) ([]string, error)); ok {
		return returnFunc(ctx, filters, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ArticleFilters, domain.ArticleListOptions) []string); ok {
		r0 = returnFunc(ctx, filters, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ArticleFilters, domain.ArticleListOptions) error); ok {
		r1 = returnFunc(ctx, filters, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LatestArticleLister_ListLatestArticleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLatestArticleIDs'
type LatestArticleLister_ListLatestArticleIDs_Call struct {
	*mock.Call
}

// ListLatestArticleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - filters domain.ArticleFilters
//   - options domain.ArticleListOptions
func (_e *LatestArticleLister_Expecter) ListLatestArticleIDs(ctx interface{}, filters interface{}, options interface{}) *LatestArticleLister_ListLatestArticleIDs_Call {
	return &LatestArticleLister_ListLatestArticleIDs_Call{Call: _e.mock.On("ListLatestArticleIDs", ctx, filters, options)}
}

func (_c *LatestArticleLister_ListLatestArticleIDs_Call) Run(run func(ctx context.Context, filters domain.ArticleFilters, options domain.ArticleListOptions)) *LatestArticleLister_ListLatestArticleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ArticleFilters
		if args[1] != nil {
			arg1 = args[1].(domain.ArticleFilters)
		}
		var arg2 domain.ArticleListOptions
		if args[2] != nil {
			arg2 = args[2].(domain.ArticleListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LatestArticleLister_ListLatestArticleIDs_Call) Return(strings []string, err error) *LatestArticleLister_ListLatestArticleIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *LatestArticleLister_ListLatestArticleIDs_Call) RunAndReturn(run func(ctx context.Context, filters domain.ArticleFilters, options domain.ArticleListOptions) ([]string, error)) *LatestArticleLister_ListLatestArticleIDs_Call {
	_c.Call.Return(run)
	return _c
}
