// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserArticleVectorsGetter is an autogenerated mock type for the UserArticleVectorsGetter type
type MockUserArticleVectorsGetter struct {
	mock.Mock
}

type MockUserArticleVectorsGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserArticleVectorsGetter) EXPECT() *MockUserArticleVectorsGetter_Expecter {
	return &MockUserArticleVectorsGetter_Expecter{mock: &_m.Mock}
}

// GetUserArticleVectorsByType provides a mock function with given fields: ctx, userID, ratingType
func (_m *MockUserArticleVectorsGetter) GetUserArticleVectorsByType(ctx context.Context, userID string, ratingType domain.UserRatingType) ([]domain.UserArticleRating, error) {
	ret := _m.Called(ctx, userID, ratingType)

	if len(ret) == 0 {
		panic("no return value specified for GetUserArticleVectorsByType")
	}

	var r0 []domain.UserArticleRating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) ([]domain.UserArticleRating, error)); ok {
		return rf(ctx, userID, ratingType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) []domain.UserArticleRating); ok {
		r0 = rf(ctx, userID, ratingType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserArticleRating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.UserRatingType) error); ok {
		r1 = rf(ctx, userID, ratingType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserArticleVectorsByType'
type MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call struct {
	*mock.Call
}

// GetUserArticleVectorsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ratingType domain.UserRatingType
func (_e *MockUserArticleVectorsGetter_Expecter) GetUserArticleVectorsByType(ctx interface{}, userID interface{}, ratingType interface{}) *MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call {
	return &MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call{Call: _e.mock.On("GetUserArticleVectorsByType", ctx, userID, ratingType)}
}

func (_c *MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call) Run(run func(ctx context.Context, userID string, ratingType domain.UserRatingType)) *MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.UserRatingType))
	})
	return _c
}

func (_c *MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call) Return(_a0 []domain.UserArticleRating, _a1 error) *MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call) RunAndReturn(run func(context.Context, string, domain.UserRatingType) ([]domain.UserArticleRating, error)) *MockUserArticleVectorsGetter_GetUserArticleVectorsByType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserArticleVectorsGetter creates a new instance of MockUserArticleVectorsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserArticleVectorsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserArticleVectorsGetter {
	mock := &MockUserArticleVectorsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
