// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserAPITokenLister is an autogenerated mock type for the UserAPITokenLister type
type MockUserAPITokenLister struct {
	mock.Mock
}

type MockUserAPITokenLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAPITokenLister) EXPECT() *MockUserAPITokenLister_Expecter {
	return &MockUserAPITokenLister_Expecter{mock: &_m.Mock}
}

// ListUserAPITokens provides a mock function with given fields: ctx, userID
func (_m *MockUserAPITokenLister) ListUserAPITokens(ctx context.Context, userID string) ([]domain.APIToken, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserAPITokens")
	}

	var r0 []domain.APIToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.APIToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.APIToken); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.APIToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserAPITokenLister_ListUserAPITokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserAPITokens'
type MockUserAPITokenLister_ListUserAPITokens_Call struct {
	*mock.Call
}

// ListUserAPITokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserAPITokenLister_Expecter) ListUserAPITokens(ctx interface{}, userID interface{}) *MockUserAPITokenLister_ListUserAPITokens_Call {
	return &MockUserAPITokenLister_ListUserAPITokens_Call{Call: _e.mock.On("ListUserAPITokens", ctx, userID)}
}

func (_c *MockUserAPITokenLister_ListUserAPITokens_Call) Run(run func(ctx context.Context, userID string)) *MockUserAPITokenLister_ListUserAPITokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserAPITokenLister_ListUserAPITokens_Call) Return(_a0 []domain.APIToken, _a1 error) *MockUserAPITokenLister_ListUserAPITokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserAPITokenLister_ListUserAPITokens_Call) RunAndReturn(run func(context.Context, string) ([]domain.APIToken, error)) *MockUserAPITokenLister_ListUserAPITokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserAPITokenLister creates a new instance of MockUserAPITokenLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAPITokenLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAPITokenLister {
	mock := &MockUserAPITokenLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
