// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	datasources "github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRecommendationStateGetter is an autogenerated mock type for the UserRecommendationStateGetter type
type MockUserRecommendationStateGetter struct {
	mock.Mock
}

type MockUserRecommendationStateGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRecommendationStateGetter) EXPECT() *MockUserRecommendationStateGetter_Expecter {
	return &MockUserRecommendationStateGetter_Expecter{mock: &_m.Mock}
}

// GetUserRecommendationState provides a mock function with given fields: ctx, userID
func (_m *MockUserRecommendationStateGetter) GetUserRecommendationState(ctx context.Context, userID string) (datasources.UserRecommendationState, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecommendationState")
	}

	var r0 datasources.UserRecommendationState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (datasources.UserRecommendationState, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) datasources.UserRecommendationState); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(datasources.UserRecommendationState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRecommendationStateGetter_GetUserRecommendationState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRecommendationState'
type MockUserRecommendationStateGetter_GetUserRecommendationState_Call struct {
	*mock.Call
}

// GetUserRecommendationState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRecommendationStateGetter_Expecter) GetUserRecommendationState(ctx interface{}, userID interface{}) *MockUserRecommendationStateGetter_GetUserRecommendationState_Call {
	return &MockUserRecommendationStateGetter_GetUserRecommendationState_Call{Call: _e.mock.On("GetUserRecommendationState", ctx, userID)}
}

func (_c *MockUserRecommendationStateGetter_GetUserRecommendationState_Call) Run(run func(ctx context.Context, userID string)) *MockUserRecommendationStateGetter_GetUserRecommendationState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRecommendationStateGetter_GetUserRecommendationState_Call) Return(_a0 datasources.UserRecommendationState, _a1 error) *MockUserRecommendationStateGetter_GetUserRecommendationState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRecommendationStateGetter_GetUserRecommendationState_Call) RunAndReturn(run func(context.Context, string) (datasources.UserRecommendationState, error)) *MockUserRecommendationStateGetter_GetUserRecommendationState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRecommendationStateGetter creates a new instance of MockUserRecommendationStateGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRecommendationStateGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRecommendationStateGetter {
	mock := &MockUserRecommendationStateGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
