// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReadArticleIDsLister is an autogenerated mock type for the ReadArticleIDsLister type
type MockReadArticleIDsLister struct {
	mock.Mock
}

type MockReadArticleIDsLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadArticleIDsLister) EXPECT() *MockReadArticleIDsLister_Expecter {
	return &MockReadArticleIDsLister_Expecter{mock: &_m.Mock}
}

// ListReadArticleIDs provides a mock function with given fields: ctx, userID
func (_m *MockReadArticleIDsLister) ListReadArticleIDs(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListReadArticleIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadArticleIDsLister_ListReadArticleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReadArticleIDs'
type MockReadArticleIDsLister_ListReadArticleIDs_Call struct {
	*mock.Call
}

// ListReadArticleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockReadArticleIDsLister_Expecter) ListReadArticleIDs(ctx interface{}, userID interface{}) *MockReadArticleIDsLister_ListReadArticleIDs_Call {
	return &MockReadArticleIDsLister_ListReadArticleIDs_Call{Call: _e.mock.On("ListReadArticleIDs", ctx, userID)}
}

func (_c *MockReadArticleIDsLister_ListReadArticleIDs_Call) Run(run func(ctx context.Context, userID string)) *MockReadArticleIDsLister_ListReadArticleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReadArticleIDsLister_ListReadArticleIDs_Call) Return(_a0 []string, _a1 error) *MockReadArticleIDsLister_ListReadArticleIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadArticleIDsLister_ListReadArticleIDs_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockReadArticleIDsLister_ListReadArticleIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReadArticleIDsLister creates a new instance of MockReadArticleIDsLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadArticleIDsLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadArticleIDsLister {
	mock := &MockReadArticleIDsLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
