// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockAPITokenByHashGetter is an autogenerated mock type for the APITokenByHashGetter type
type MockAPITokenByHashGetter struct {
	mock.Mock
}

type MockAPITokenByHashGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPITokenByHashGetter) EXPECT() *MockAPITokenByHashGetter_Expecter {
	return &MockAPITokenByHashGetter_Expecter{mock: &_m.Mock}
}

// GetAPITokenByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockAPITokenByHashGetter) GetAPITokenByHash(ctx context.Context, tokenHash string) (domain.APIToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetAPITokenByHash")
	}

	var r0 domain.APIToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.APIToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.APIToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(domain.APIToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPITokenByHashGetter_GetAPITokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPITokenByHash'
type MockAPITokenByHashGetter_GetAPITokenByHash_Call struct {
	*mock.Call
}

// GetAPITokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockAPITokenByHashGetter_Expecter) GetAPITokenByHash(ctx interface{}, tokenHash interface{}) *MockAPITokenByHashGetter_GetAPITokenByHash_Call {
	return &MockAPITokenByHashGetter_GetAPITokenByHash_Call{Call: _e.mock.On("GetAPITokenByHash", ctx, tokenHash)}
}

func (_c *MockAPITokenByHashGetter_GetAPITokenByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockAPITokenByHashGetter_GetAPITokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPITokenByHashGetter_GetAPITokenByHash_Call) Return(_a0 domain.APIToken, _a1 error) *MockAPITokenByHashGetter_GetAPITokenByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPITokenByHashGetter_GetAPITokenByHash_Call) RunAndReturn(run func(context.Context, string) (domain.APIToken, error)) *MockAPITokenByHashGetter_GetAPITokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPITokenByHashGetter creates a new instance of MockAPITokenByHashGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPITokenByHashGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPITokenByHashGetter {
	mock := &MockAPITokenByHashGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
