// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserInterestClusterDeleter is an autogenerated mock type for the UserInterestClusterDeleter type
type MockUserInterestClusterDeleter struct {
	mock.Mock
}

type MockUserInterestClusterDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserInterestClusterDeleter) EXPECT() *MockUserInterestClusterDeleter_Expecter {
	return &MockUserInterestClusterDeleter_Expecter{mock: &_m.Mock}
}

// DeleteUserInterestClusters provides a mock function with given fields: ctx, userID
func (_m *MockUserInterestClusterDeleter) DeleteUserInterestClusters(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserInterestClusters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserInterestClusters'
type MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call struct {
	*mock.Call
}

// DeleteUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserInterestClusterDeleter_Expecter) DeleteUserInterestClusters(ctx interface{}, userID interface{}) *MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call {
	return &MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call{Call: _e.mock.On("DeleteUserInterestClusters", ctx, userID)}
}

func (_c *MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call) Return(_a0 error) *MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call) RunAndReturn(run func(context.Context, string) error) *MockUserInterestClusterDeleter_DeleteUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserInterestClusterDeleter creates a new instance of MockUserInterestClusterDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserInterestClusterDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserInterestClusterDeleter {
	mock := &MockUserInterestClusterDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
