// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRegenerationNeededMarker is an autogenerated mock type for the UserRegenerationNeededMarker type
type MockUserRegenerationNeededMarker struct {
	mock.Mock
}

type MockUserRegenerationNeededMarker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRegenerationNeededMarker) EXPECT() *MockUserRegenerationNeededMarker_Expecter {
	return &MockUserRegenerationNeededMarker_Expecter{mock: &_m.Mock}
}

// MarkUserNeedsRegeneration provides a mock function with given fields: ctx, userID
func (_m *MockUserRegenerationNeededMarker) MarkUserNeedsRegeneration(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserNeedsRegeneration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserNeedsRegeneration'
type MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call struct {
	*mock.Call
}

// MarkUserNeedsRegeneration is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRegenerationNeededMarker_Expecter) MarkUserNeedsRegeneration(ctx interface{}, userID interface{}) *MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call {
	return &MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call{Call: _e.mock.On("MarkUserNeedsRegeneration", ctx, userID)}
}

func (_c *MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call) Run(run func(ctx context.Context, userID string)) *MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call) Return(_a0 error) *MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRegenerationNeededMarker creates a new instance of MockUserRegenerationNeededMarker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRegenerationNeededMarker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRegenerationNeededMarker {
	mock := &MockUserRegenerationNeededMarker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
