// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLikedArticleLister is an autogenerated mock type for the LikedArticleLister type
type MockLikedArticleLister struct {
	mock.Mock
}

type MockLikedArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLikedArticleLister) EXPECT() *MockLikedArticleLister_Expecter {
	return &MockLikedArticleLister_Expecter{mock: &_m.Mock}
}

// ListLikedArticleIDs provides a mock function with given fields: ctx, userID, page, pageSize
func (_m *MockLikedArticleLister) ListLikedArticleIDs(ctx context.Context, userID string, page int, pageSize int) ([]string, error) {
	ret := _m.Called(ctx, userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListLikedArticleIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]string, error)); ok {
		return rf(ctx, userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []string); ok {
		r0 = rf(ctx, userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLikedArticleLister_ListLikedArticleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLikedArticleIDs'
type MockLikedArticleLister_ListLikedArticleIDs_Call struct {
	*mock.Call
}

// ListLikedArticleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - pageSize int
func (_e *MockLikedArticleLister_Expecter) ListLikedArticleIDs(ctx interface{}, userID interface{}, page interface{}, pageSize interface{}) *MockLikedArticleLister_ListLikedArticleIDs_Call {
	return &MockLikedArticleLister_ListLikedArticleIDs_Call{Call: _e.mock.On("ListLikedArticleIDs", ctx, userID, page, pageSize)}
}

func (_c *MockLikedArticleLister_ListLikedArticleIDs_Call) Run(run func(ctx context.Context, userID string, page int, pageSize int)) *MockLikedArticleLister_ListLikedArticleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockLikedArticleLister_ListLikedArticleIDs_Call) Return(_a0 []string, _a1 error) *MockLikedArticleLister_ListLikedArticleIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLikedArticleLister_ListLikedArticleIDs_Call) RunAndReturn(run func(context.Context, string, int, int) ([]string, error)) *MockLikedArticleLister_ListLikedArticleIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLikedArticleLister creates a new instance of MockLikedArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLikedArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLikedArticleLister {
	mock := &MockLikedArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
