// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleRatingSetter is an autogenerated mock type for the ArticleRatingSetter type
type MockArticleRatingSetter struct {
	mock.Mock
}

type MockArticleRatingSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleRatingSetter) EXPECT() *MockArticleRatingSetter_Expecter {
	return &MockArticleRatingSetter_Expecter{mock: &_m.Mock}
}

// SetArticleRating provides a mock function with given fields: ctx, userID, articleHashID, thumbsUp, thumbsDown, vector
func (_m *MockArticleRatingSetter) SetArticleRating(ctx context.Context, userID string, articleHashID string, thumbsUp bool, thumbsDown bool, vector []float32) error {
	ret := _m.Called(ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)

	if len(ret) == 0 {
		panic("no return value specified for SetArticleRating")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool, bool, []float32) error); ok {
		r0 = rf(ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArticleRatingSetter_SetArticleRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArticleRating'
type MockArticleRatingSetter_SetArticleRating_Call struct {
	*mock.Call
}

// SetArticleRating is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - thumbsUp bool
//   - thumbsDown bool
//   - vector []float32
func (_e *MockArticleRatingSetter_Expecter) SetArticleRating(ctx interface{}, userID interface{}, articleHashID interface{}, thumbsUp interface{}, thumbsDown interface{}, vector interface{}) *MockArticleRatingSetter_SetArticleRating_Call {
	return &MockArticleRatingSetter_SetArticleRating_Call{Call: _e.mock.On("SetArticleRating", ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)}
}

func (_c *MockArticleRatingSetter_SetArticleRating_Call) Run(run func(ctx context.Context, userID string, articleHashID string, thumbsUp bool, thumbsDown bool, vector []float32)) *MockArticleRatingSetter_SetArticleRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool), args[4].(bool), args[5].([]float32))
	})
	return _c
}

func (_c *MockArticleRatingSetter_SetArticleRating_Call) Return(_a0 error) *MockArticleRatingSetter_SetArticleRating_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArticleRatingSetter_SetArticleRating_Call) RunAndReturn(run func(context.Context, string, string, bool, bool, []float32) error) *MockArticleRatingSetter_SetArticleRating_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArticleRatingSetter creates a new instance of MockArticleRatingSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleRatingSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleRatingSetter {
	mock := &MockArticleRatingSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
