// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockPrecomputedRecommendationAgeGetter is an autogenerated mock type for the PrecomputedRecommendationAgeGetter type
type MockPrecomputedRecommendationAgeGetter struct {
	mock.Mock
}

type MockPrecomputedRecommendationAgeGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrecomputedRecommendationAgeGetter) EXPECT() *MockPrecomputedRecommendationAgeGetter_Expecter {
	return &MockPrecomputedRecommendationAgeGetter_Expecter{mock: &_m.Mock}
}

// GetPrecomputedRecommendationAge provides a mock function with given fields: ctx, userID
func (_m *MockPrecomputedRecommendationAgeGetter) GetPrecomputedRecommendationAge(ctx context.Context, userID string) (time.Time, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendationAge")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendationAge'
type MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendationAge is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPrecomputedRecommendationAgeGetter_Expecter) GetPrecomputedRecommendationAge(ctx interface{}, userID interface{}) *MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call {
	return &MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call{Call: _e.mock.On("GetPrecomputedRecommendationAge", ctx, userID)}
}

func (_c *MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call) Run(run func(ctx context.Context, userID string)) *MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call) Return(_a0 time.Time, _a1 error) *MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call) RunAndReturn(run func(context.Context, string) (time.Time, error)) *MockPrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrecomputedRecommendationAgeGetter creates a new instance of MockPrecomputedRecommendationAgeGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrecomputedRecommendationAgeGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrecomputedRecommendationAgeGetter {
	mock := &MockPrecomputedRecommendationAgeGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
