// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPrecomputedRecommendationDeleter is an autogenerated mock type for the PrecomputedRecommendationDeleter type
type MockPrecomputedRecommendationDeleter struct {
	mock.Mock
}

type MockPrecomputedRecommendationDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrecomputedRecommendationDeleter) EXPECT() *MockPrecomputedRecommendationDeleter_Expecter {
	return &MockPrecomputedRecommendationDeleter_Expecter{mock: &_m.Mock}
}

// DeleteUserPrecomputedRecommendations provides a mock function with given fields: ctx, userID
func (_m *MockPrecomputedRecommendationDeleter) DeleteUserPrecomputedRecommendations(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPrecomputedRecommendations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserPrecomputedRecommendations'
type MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call struct {
	*mock.Call
}

// DeleteUserPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPrecomputedRecommendationDeleter_Expecter) DeleteUserPrecomputedRecommendations(ctx interface{}, userID interface{}) *MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call {
	return &MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call{Call: _e.mock.On("DeleteUserPrecomputedRecommendations", ctx, userID)}
}

func (_c *MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string)) *MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call) Return(_a0 error) *MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call) RunAndReturn(run func(context.Context, string) error) *MockPrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrecomputedRecommendationDeleter creates a new instance of MockPrecomputedRecommendationDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrecomputedRecommendationDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrecomputedRecommendationDeleter {
	mock := &MockPrecomputedRecommendationDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
