// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockThumbsUpArticleLister is an autogenerated mock type for the ThumbsUpArticleLister type
type MockThumbsUpArticleLister struct {
	mock.Mock
}

type MockThumbsUpArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThumbsUpArticleLister) EXPECT() *MockThumbsUpArticleLister_Expecter {
	return &MockThumbsUpArticleLister_Expecter{mock: &_m.Mock}
}

// ListThumbsUpArticleIDs provides a mock function with given fields: ctx, userID
func (_m *MockThumbsUpArticleLister) ListThumbsUpArticleIDs(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListThumbsUpArticleIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListThumbsUpArticleIDs'
type MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call struct {
	*mock.Call
}

// ListThumbsUpArticleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockThumbsUpArticleLister_Expecter) ListThumbsUpArticleIDs(ctx interface{}, userID interface{}) *MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call {
	return &MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call{Call: _e.mock.On("ListThumbsUpArticleIDs", ctx, userID)}
}

func (_c *MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call) Run(run func(ctx context.Context, userID string)) *MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call) Return(_a0 []string, _a1 error) *MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockThumbsUpArticleLister_ListThumbsUpArticleIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockThumbsUpArticleLister creates a new instance of MockThumbsUpArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThumbsUpArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThumbsUpArticleLister {
	mock := &MockThumbsUpArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
