// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	datasources "github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockPrecomputedRecommendationReader is an autogenerated mock type for the PrecomputedRecommendationReader type
type MockPrecomputedRecommendationReader struct {
	mock.Mock
}

type MockPrecomputedRecommendationReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrecomputedRecommendationReader) EXPECT() *MockPrecomputedRecommendationReader_Expecter {
	return &MockPrecomputedRecommendationReader_Expecter{mock: &_m.Mock}
}

// GetPrecomputedRecommendationAge provides a mock function with given fields: ctx, userID
func (_m *MockPrecomputedRecommendationReader) GetPrecomputedRecommendationAge(ctx context.Context, userID string) (time.Time, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendationAge")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendationAge'
type MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendationAge is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPrecomputedRecommendationReader_Expecter) GetPrecomputedRecommendationAge(ctx interface{}, userID interface{}) *MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call {
	return &MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call{Call: _e.mock.On("GetPrecomputedRecommendationAge", ctx, userID)}
}

func (_c *MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call) Run(run func(ctx context.Context, userID string)) *MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call) Return(_a0 time.Time, _a1 error) *MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call) RunAndReturn(run func(context.Context, string) (time.Time, error)) *MockPrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrecomputedRecommendations provides a mock function with given fields: ctx, userID, limit
func (_m *MockPrecomputedRecommendationReader) GetPrecomputedRecommendations(ctx context.Context, userID string, limit int) ([]datasources.PrecomputedRecommendation, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendations")
	}

	var r0 []datasources.PrecomputedRecommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]datasources.PrecomputedRecommendation, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []datasources.PrecomputedRecommendation); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.PrecomputedRecommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendations'
type MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *MockPrecomputedRecommendationReader_Expecter) GetPrecomputedRecommendations(ctx interface{}, userID interface{}, limit interface{}) *MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call {
	return &MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call{Call: _e.mock.On("GetPrecomputedRecommendations", ctx, userID, limit)}
}

func (_c *MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string, limit int)) *MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call) Return(_a0 []datasources.PrecomputedRecommendation, _a1 error) *MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call) RunAndReturn(run func(context.Context, string, int) ([]datasources.PrecomputedRecommendation, error)) *MockPrecomputedRecommendationReader_GetPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrecomputedRecommendationReader creates a new instance of MockPrecomputedRecommendationReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrecomputedRecommendationReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrecomputedRecommendationReader {
	mock := &MockPrecomputedRecommendationReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
