// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleVectorFetcher is an autogenerated mock type for the ArticleVectorFetcher type
type MockArticleVectorFetcher struct {
	mock.Mock
}

type MockArticleVectorFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleVectorFetcher) EXPECT() *MockArticleVectorFetcher_Expecter {
	return &MockArticleVectorFetcher_Expecter{mock: &_m.Mock}
}

// FetchArticleVector provides a mock function with given fields: ctx, hashID
func (_m *MockArticleVectorFetcher) FetchArticleVector(ctx context.Context, hashID string) ([]float32, error) {
	ret := _m.Called(ctx, hashID)

	if len(ret) == 0 {
		panic("no return value specified for FetchArticleVector")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return rf(ctx, hashID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = rf(ctx, hashID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hashID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArticleVectorFetcher_FetchArticleVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArticleVector'
type MockArticleVectorFetcher_FetchArticleVector_Call struct {
	*mock.Call
}

// FetchArticleVector is a helper method to define mock.On call
//   - ctx context.Context
//   - hashID string
func (_e *MockArticleVectorFetcher_Expecter) FetchArticleVector(ctx interface{}, hashID interface{}) *MockArticleVectorFetcher_FetchArticleVector_Call {
	return &MockArticleVectorFetcher_FetchArticleVector_Call{Call: _e.mock.On("FetchArticleVector", ctx, hashID)}
}

func (_c *MockArticleVectorFetcher_FetchArticleVector_Call) Run(run func(ctx context.Context, hashID string)) *MockArticleVectorFetcher_FetchArticleVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockArticleVectorFetcher_FetchArticleVector_Call) Return(_a0 []float32, _a1 error) *MockArticleVectorFetcher_FetchArticleVector_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArticleVectorFetcher_FetchArticleVector_Call) RunAndReturn(run func(context.Context, string) ([]float32, error)) *MockArticleVectorFetcher_FetchArticleVector_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArticleVectorFetcher creates a new instance of MockArticleVectorFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleVectorFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleVectorFetcher {
	mock := &MockArticleVectorFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
