// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRegeneratedMarker is an autogenerated mock type for the UserRegeneratedMarker type
type MockUserRegeneratedMarker struct {
	mock.Mock
}

type MockUserRegeneratedMarker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRegeneratedMarker) EXPECT() *MockUserRegeneratedMarker_Expecter {
	return &MockUserRegeneratedMarker_Expecter{mock: &_m.Mock}
}

// MarkUserRegenerated provides a mock function with given fields: ctx, userID
func (_m *MockUserRegeneratedMarker) MarkUserRegenerated(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserRegenerated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRegeneratedMarker_MarkUserRegenerated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserRegenerated'
type MockUserRegeneratedMarker_MarkUserRegenerated_Call struct {
	*mock.Call
}

// MarkUserRegenerated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRegeneratedMarker_Expecter) MarkUserRegenerated(ctx interface{}, userID interface{}) *MockUserRegeneratedMarker_MarkUserRegenerated_Call {
	return &MockUserRegeneratedMarker_MarkUserRegenerated_Call{Call: _e.mock.On("MarkUserRegenerated", ctx, userID)}
}

func (_c *MockUserRegeneratedMarker_MarkUserRegenerated_Call) Run(run func(ctx context.Context, userID string)) *MockUserRegeneratedMarker_MarkUserRegenerated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRegeneratedMarker_MarkUserRegenerated_Call) Return(_a0 error) *MockUserRegeneratedMarker_MarkUserRegenerated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRegeneratedMarker_MarkUserRegenerated_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRegeneratedMarker_MarkUserRegenerated_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRegeneratedMarker creates a new instance of MockUserRegeneratedMarker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRegeneratedMarker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRegeneratedMarker {
	mock := &MockUserRegeneratedMarker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
