// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleThumbsUpSetter is an autogenerated mock type for the ArticleThumbsUpSetter type
type MockArticleThumbsUpSetter struct {
	mock.Mock
}

type MockArticleThumbsUpSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleThumbsUpSetter) EXPECT() *MockArticleThumbsUpSetter_Expecter {
	return &MockArticleThumbsUpSetter_Expecter{mock: &_m.Mock}
}

// SetArticleThumbsUp provides a mock function with given fields: ctx, hashID, userID, thumbsUp
func (_m *MockArticleThumbsUpSetter) SetArticleThumbsUp(ctx context.Context, hashID string, userID string, thumbsUp bool) error {
	ret := _m.Called(ctx, hashID, userID, thumbsUp)

	if len(ret) == 0 {
		panic("no return value specified for SetArticleThumbsUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, hashID, userID, thumbsUp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArticleThumbsUpSetter_SetArticleThumbsUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArticleThumbsUp'
type MockArticleThumbsUpSetter_SetArticleThumbsUp_Call struct {
	*mock.Call
}

// SetArticleThumbsUp is a helper method to define mock.On call
//   - ctx context.Context
//   - hashID string
//   - userID string
//   - thumbsUp bool
func (_e *MockArticleThumbsUpSetter_Expecter) SetArticleThumbsUp(ctx interface{}, hashID interface{}, userID interface{}, thumbsUp interface{}) *MockArticleThumbsUpSetter_SetArticleThumbsUp_Call {
	return &MockArticleThumbsUpSetter_SetArticleThumbsUp_Call{Call: _e.mock.On("SetArticleThumbsUp", ctx, hashID, userID, thumbsUp)}
}

func (_c *MockArticleThumbsUpSetter_SetArticleThumbsUp_Call) Run(run func(ctx context.Context, hashID string, userID string, thumbsUp bool)) *MockArticleThumbsUpSetter_SetArticleThumbsUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockArticleThumbsUpSetter_SetArticleThumbsUp_Call) Return(_a0 error) *MockArticleThumbsUpSetter_SetArticleThumbsUp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArticleThumbsUpSetter_SetArticleThumbsUp_Call) RunAndReturn(run func(context.Context, string, string, bool) error) *MockArticleThumbsUpSetter_SetArticleThumbsUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArticleThumbsUpSetter creates a new instance of MockArticleThumbsUpSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleThumbsUpSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleThumbsUpSetter {
	mock := &MockArticleThumbsUpSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
