// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleThumbsDownSetter is an autogenerated mock type for the ArticleThumbsDownSetter type
type MockArticleThumbsDownSetter struct {
	mock.Mock
}

type MockArticleThumbsDownSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleThumbsDownSetter) EXPECT() *MockArticleThumbsDownSetter_Expecter {
	return &MockArticleThumbsDownSetter_Expecter{mock: &_m.Mock}
}

// SetArticleThumbsDown provides a mock function with given fields: ctx, hashID, userID, thumbsDown
func (_m *MockArticleThumbsDownSetter) SetArticleThumbsDown(ctx context.Context, hashID string, userID string, thumbsDown bool) error {
	ret := _m.Called(ctx, hashID, userID, thumbsDown)

	if len(ret) == 0 {
		panic("no return value specified for SetArticleThumbsDown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, hashID, userID, thumbsDown)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArticleThumbsDownSetter_SetArticleThumbsDown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArticleThumbsDown'
type MockArticleThumbsDownSetter_SetArticleThumbsDown_Call struct {
	*mock.Call
}

// SetArticleThumbsDown is a helper method to define mock.On call
//   - ctx context.Context
//   - hashID string
//   - userID string
//   - thumbsDown bool
func (_e *MockArticleThumbsDownSetter_Expecter) SetArticleThumbsDown(ctx interface{}, hashID interface{}, userID interface{}, thumbsDown interface{}) *MockArticleThumbsDownSetter_SetArticleThumbsDown_Call {
	return &MockArticleThumbsDownSetter_SetArticleThumbsDown_Call{Call: _e.mock.On("SetArticleThumbsDown", ctx, hashID, userID, thumbsDown)}
}

func (_c *MockArticleThumbsDownSetter_SetArticleThumbsDown_Call) Run(run func(ctx context.Context, hashID string, userID string, thumbsDown bool)) *MockArticleThumbsDownSetter_SetArticleThumbsDown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockArticleThumbsDownSetter_SetArticleThumbsDown_Call) Return(_a0 error) *MockArticleThumbsDownSetter_SetArticleThumbsDown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArticleThumbsDownSetter_SetArticleThumbsDown_Call) RunAndReturn(run func(context.Context, string, string, bool) error) *MockArticleThumbsDownSetter_SetArticleThumbsDown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArticleThumbsDownSetter creates a new instance of MockArticleThumbsDownSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleThumbsDownSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleThumbsDownSetter {
	mock := &MockArticleThumbsDownSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
