// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAPITokenLastUsedUpdater is an autogenerated mock type for the APITokenLastUsedUpdater type
type MockAPITokenLastUsedUpdater struct {
	mock.Mock
}

type MockAPITokenLastUsedUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPITokenLastUsedUpdater) EXPECT() *MockAPITokenLastUsedUpdater_Expecter {
	return &MockAPITokenLastUsedUpdater_Expecter{mock: &_m.Mock}
}

// UpdateAPITokenLastUsed provides a mock function with given fields: ctx, tokenID
func (_m *MockAPITokenLastUsedUpdater) UpdateAPITokenLastUsed(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAPITokenLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAPITokenLastUsed'
type MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call struct {
	*mock.Call
}

// UpdateAPITokenLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockAPITokenLastUsedUpdater_Expecter) UpdateAPITokenLastUsed(ctx interface{}, tokenID interface{}) *MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call {
	return &MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call{Call: _e.mock.On("UpdateAPITokenLastUsed", ctx, tokenID)}
}

func (_c *MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call) Run(run func(ctx context.Context, tokenID string)) *MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call) Return(_a0 error) *MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call) RunAndReturn(run func(context.Context, string) error) *MockAPITokenLastUsedUpdater_UpdateAPITokenLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPITokenLastUsedUpdater creates a new instance of MockAPITokenLastUsedUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPITokenLastUsedUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPITokenLastUsedUpdater {
	mock := &MockAPITokenLastUsedUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
