// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockSimilarArticleLister is an autogenerated mock type for the SimilarArticleLister type
type MockSimilarArticleLister struct {
	mock.Mock
}

type MockSimilarArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSimilarArticleLister) EXPECT() *MockSimilarArticleLister_Expecter {
	return &MockSimilarArticleLister_Expecter{mock: &_m.Mock}
}

// ListSimilarArticles provides a mock function with given fields: ctx, hashIDs, count
func (_m *MockSimilarArticleLister) ListSimilarArticles(ctx context.Context, hashIDs []string, count int) ([]domain.SimilarArticle, error) {
	ret := _m.Called(ctx, hashIDs, count)

	if len(ret) == 0 {
		panic("no return value specified for ListSimilarArticles")
	}

	var r0 []domain.SimilarArticle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, int) ([]domain.SimilarArticle, error)); ok {
		return rf(ctx, hashIDs, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, int) []domain.SimilarArticle); ok {
		r0 = rf(ctx, hashIDs, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SimilarArticle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, int) error); ok {
		r1 = rf(ctx, hashIDs, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSimilarArticleLister_ListSimilarArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSimilarArticles'
type MockSimilarArticleLister_ListSimilarArticles_Call struct {
	*mock.Call
}

// ListSimilarArticles is a helper method to define mock.On call
//   - ctx context.Context
//   - hashIDs []string
//   - count int
func (_e *MockSimilarArticleLister_Expecter) ListSimilarArticles(ctx interface{}, hashIDs interface{}, count interface{}) *MockSimilarArticleLister_ListSimilarArticles_Call {
	return &MockSimilarArticleLister_ListSimilarArticles_Call{Call: _e.mock.On("ListSimilarArticles", ctx, hashIDs, count)}
}

func (_c *MockSimilarArticleLister_ListSimilarArticles_Call) Run(run func(ctx context.Context, hashIDs []string, count int)) *MockSimilarArticleLister_ListSimilarArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(int))
	})
	return _c
}

func (_c *MockSimilarArticleLister_ListSimilarArticles_Call) Return(_a0 []domain.SimilarArticle, _a1 error) *MockSimilarArticleLister_ListSimilarArticles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSimilarArticleLister_ListSimilarArticles_Call) RunAndReturn(run func(context.Context, []string, int) ([]domain.SimilarArticle, error)) *MockSimilarArticleLister_ListSimilarArticles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSimilarArticleLister creates a new instance of MockSimilarArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSimilarArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSimilarArticleLister {
	mock := &MockSimilarArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
