// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserArticleVectorsCounter is an autogenerated mock type for the UserArticleVectorsCounter type
type MockUserArticleVectorsCounter struct {
	mock.Mock
}

type MockUserArticleVectorsCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserArticleVectorsCounter) EXPECT() *MockUserArticleVectorsCounter_Expecter {
	return &MockUserArticleVectorsCounter_Expecter{mock: &_m.Mock}
}

// CountUserArticleVectorsByType provides a mock function with given fields: ctx, userID, ratingType
func (_m *MockUserArticleVectorsCounter) CountUserArticleVectorsByType(ctx context.Context, userID string, ratingType domain.UserRatingType) (int64, error) {
	ret := _m.Called(ctx, userID, ratingType)

	if len(ret) == 0 {
		panic("no return value specified for CountUserArticleVectorsByType")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) (int64, error)); ok {
		return rf(ctx, userID, ratingType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) int64); ok {
		r0 = rf(ctx, userID, ratingType)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.UserRatingType) error); ok {
		r1 = rf(ctx, userID, ratingType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserArticleVectorsByType'
type MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call struct {
	*mock.Call
}

// CountUserArticleVectorsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ratingType domain.UserRatingType
func (_e *MockUserArticleVectorsCounter_Expecter) CountUserArticleVectorsByType(ctx interface{}, userID interface{}, ratingType interface{}) *MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call {
	return &MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call{Call: _e.mock.On("CountUserArticleVectorsByType", ctx, userID, ratingType)}
}

func (_c *MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call) Run(run func(ctx context.Context, userID string, ratingType domain.UserRatingType)) *MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.UserRatingType))
	})
	return _c
}

func (_c *MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call) Return(_a0 int64, _a1 error) *MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call) RunAndReturn(run func(context.Context, string, domain.UserRatingType) (int64, error)) *MockUserArticleVectorsCounter_CountUserArticleVectorsByType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserArticleVectorsCounter creates a new instance of MockUserArticleVectorsCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserArticleVectorsCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserArticleVectorsCounter {
	mock := &MockUserArticleVectorsCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
