// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserVectorSyncer is an autogenerated mock type for the UserVectorSyncer type
type MockUserVectorSyncer struct {
	mock.Mock
}

type MockUserVectorSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserVectorSyncer) EXPECT() *MockUserVectorSyncer_Expecter {
	return &MockUserVectorSyncer_Expecter{mock: &_m.Mock}
}

// AddArticleVectorToUser provides a mock function with given fields: ctx, userID, articleHashID, vector
func (_m *MockUserVectorSyncer) AddArticleVectorToUser(ctx context.Context, userID string, articleHashID string, vector []float32) (bool, error) {
	ret := _m.Called(ctx, userID, articleHashID, vector)

	if len(ret) == 0 {
		panic("no return value specified for AddArticleVectorToUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []float32) (bool, error)); ok {
		return rf(ctx, userID, articleHashID, vector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []float32) bool); ok {
		r0 = rf(ctx, userID, articleHashID, vector)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []float32) error); ok {
		r1 = rf(ctx, userID, articleHashID, vector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserVectorSyncer_AddArticleVectorToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddArticleVectorToUser'
type MockUserVectorSyncer_AddArticleVectorToUser_Call struct {
	*mock.Call
}

// AddArticleVectorToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - vector []float32
func (_e *MockUserVectorSyncer_Expecter) AddArticleVectorToUser(ctx interface{}, userID interface{}, articleHashID interface{}, vector interface{}) *MockUserVectorSyncer_AddArticleVectorToUser_Call {
	return &MockUserVectorSyncer_AddArticleVectorToUser_Call{Call: _e.mock.On("AddArticleVectorToUser", ctx, userID, articleHashID, vector)}
}

func (_c *MockUserVectorSyncer_AddArticleVectorToUser_Call) Run(run func(ctx context.Context, userID string, articleHashID string, vector []float32)) *MockUserVectorSyncer_AddArticleVectorToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]float32))
	})
	return _c
}

func (_c *MockUserVectorSyncer_AddArticleVectorToUser_Call) Return(added bool, err error) *MockUserVectorSyncer_AddArticleVectorToUser_Call {
	_c.Call.Return(added, err)
	return _c
}

func (_c *MockUserVectorSyncer_AddArticleVectorToUser_Call) RunAndReturn(run func(context.Context, string, string, []float32) (bool, error)) *MockUserVectorSyncer_AddArticleVectorToUser_Call {
	_c.Call.Return(run)
	return _c
}

// SubtractArticleVectorFromUser provides a mock function with given fields: ctx, userID, articleHashID, vector
func (_m *MockUserVectorSyncer) SubtractArticleVectorFromUser(ctx context.Context, userID string, articleHashID string, vector []float32) (bool, error) {
	ret := _m.Called(ctx, userID, articleHashID, vector)

	if len(ret) == 0 {
		panic("no return value specified for SubtractArticleVectorFromUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []float32) (bool, error)); ok {
		return rf(ctx, userID, articleHashID, vector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []float32) bool); ok {
		r0 = rf(ctx, userID, articleHashID, vector)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []float32) error); ok {
		r1 = rf(ctx, userID, articleHashID, vector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserVectorSyncer_SubtractArticleVectorFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubtractArticleVectorFromUser'
type MockUserVectorSyncer_SubtractArticleVectorFromUser_Call struct {
	*mock.Call
}

// SubtractArticleVectorFromUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - vector []float32
func (_e *MockUserVectorSyncer_Expecter) SubtractArticleVectorFromUser(ctx interface{}, userID interface{}, articleHashID interface{}, vector interface{}) *MockUserVectorSyncer_SubtractArticleVectorFromUser_Call {
	return &MockUserVectorSyncer_SubtractArticleVectorFromUser_Call{Call: _e.mock.On("SubtractArticleVectorFromUser", ctx, userID, articleHashID, vector)}
}

func (_c *MockUserVectorSyncer_SubtractArticleVectorFromUser_Call) Run(run func(ctx context.Context, userID string, articleHashID string, vector []float32)) *MockUserVectorSyncer_SubtractArticleVectorFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]float32))
	})
	return _c
}

func (_c *MockUserVectorSyncer_SubtractArticleVectorFromUser_Call) Return(removed bool, err error) *MockUserVectorSyncer_SubtractArticleVectorFromUser_Call {
	_c.Call.Return(removed, err)
	return _c
}

func (_c *MockUserVectorSyncer_SubtractArticleVectorFromUser_Call) RunAndReturn(run func(context.Context, string, string, []float32) (bool, error)) *MockUserVectorSyncer_SubtractArticleVectorFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserVectorSyncer creates a new instance of MockUserVectorSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserVectorSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserVectorSyncer {
	mock := &MockUserVectorSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
