// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserVectorGetter is an autogenerated mock type for the UserVectorGetter type
type MockUserVectorGetter struct {
	mock.Mock
}

type MockUserVectorGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserVectorGetter) EXPECT() *MockUserVectorGetter_Expecter {
	return &MockUserVectorGetter_Expecter{mock: &_m.Mock}
}

// GetUserVector provides a mock function with given fields: ctx, userID
func (_m *MockUserVectorGetter) GetUserVector(ctx context.Context, userID string) ([]float32, int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserVector")
	}

	var r0 []float32
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float32, int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserVectorGetter_GetUserVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserVector'
type MockUserVectorGetter_GetUserVector_Call struct {
	*mock.Call
}

// GetUserVector is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserVectorGetter_Expecter) GetUserVector(ctx interface{}, userID interface{}) *MockUserVectorGetter_GetUserVector_Call {
	return &MockUserVectorGetter_GetUserVector_Call{Call: _e.mock.On("GetUserVector", ctx, userID)}
}

func (_c *MockUserVectorGetter_GetUserVector_Call) Run(run func(ctx context.Context, userID string)) *MockUserVectorGetter_GetUserVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserVectorGetter_GetUserVector_Call) Return(vectorSum []float32, count int, err error) *MockUserVectorGetter_GetUserVector_Call {
	_c.Call.Return(vectorSum, count, err)
	return _c
}

func (_c *MockUserVectorGetter_GetUserVector_Call) RunAndReturn(run func(context.Context, string) ([]float32, int, error)) *MockUserVectorGetter_GetUserVector_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserVectorGetter creates a new instance of MockUserVectorGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserVectorGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserVectorGetter {
	mock := &MockUserVectorGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
