// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockAPITokenCreator is an autogenerated mock type for the APITokenCreator type
type MockAPITokenCreator struct {
	mock.Mock
}

type MockAPITokenCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPITokenCreator) EXPECT() *MockAPITokenCreator_Expecter {
	return &MockAPITokenCreator_Expecter{mock: &_m.Mock}
}

// CreateAPIToken provides a mock function with given fields: ctx, id, userID, tokenHash, tokenPrefix, name, expiresAt
func (_m *MockAPITokenCreator) CreateAPIToken(ctx context.Context, id string, userID string, tokenHash string, tokenPrefix string, name *string, expiresAt *time.Time) error {
	ret := _m.Called(ctx, id, userID, tokenHash, tokenPrefix, name, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *string, *time.Time) error); ok {
		r0 = rf(ctx, id, userID, tokenHash, tokenPrefix, name, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPITokenCreator_CreateAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIToken'
type MockAPITokenCreator_CreateAPIToken_Call struct {
	*mock.Call
}

// CreateAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
//   - tokenHash string
//   - tokenPrefix string
//   - name *string
//   - expiresAt *time.Time
func (_e *MockAPITokenCreator_Expecter) CreateAPIToken(ctx interface{}, id interface{}, userID interface{}, tokenHash interface{}, tokenPrefix interface{}, name interface{}, expiresAt interface{}) *MockAPITokenCreator_CreateAPIToken_Call {
	return &MockAPITokenCreator_CreateAPIToken_Call{Call: _e.mock.On("CreateAPIToken", ctx, id, userID, tokenHash, tokenPrefix, name, expiresAt)}
}

func (_c *MockAPITokenCreator_CreateAPIToken_Call) Run(run func(ctx context.Context, id string, userID string, tokenHash string, tokenPrefix string, name *string, expiresAt *time.Time)) *MockAPITokenCreator_CreateAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(*string), args[6].(*time.Time))
	})
	return _c
}

func (_c *MockAPITokenCreator_CreateAPIToken_Call) Return(_a0 error) *MockAPITokenCreator_CreateAPIToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPITokenCreator_CreateAPIToken_Call) RunAndReturn(run func(context.Context, string, string, string, string, *string, *time.Time) error) *MockAPITokenCreator_CreateAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPITokenCreator creates a new instance of MockAPITokenCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPITokenCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPITokenCreator {
	mock := &MockAPITokenCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
