// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	datasources "github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// MockUserInterestClusterGetter is an autogenerated mock type for the UserInterestClusterGetter type
type MockUserInterestClusterGetter struct {
	mock.Mock
}

type MockUserInterestClusterGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserInterestClusterGetter) EXPECT() *MockUserInterestClusterGetter_Expecter {
	return &MockUserInterestClusterGetter_Expecter{mock: &_m.Mock}
}

// GetUserInterestClusters provides a mock function with given fields: ctx, userID
func (_m *MockUserInterestClusterGetter) GetUserInterestClusters(ctx context.Context, userID string) ([]datasources.UserInterestCluster, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInterestClusters")
	}

	var r0 []datasources.UserInterestCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]datasources.UserInterestCluster, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []datasources.UserInterestCluster); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.UserInterestCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserInterestClusterGetter_GetUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInterestClusters'
type MockUserInterestClusterGetter_GetUserInterestClusters_Call struct {
	*mock.Call
}

// GetUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserInterestClusterGetter_Expecter) GetUserInterestClusters(ctx interface{}, userID interface{}) *MockUserInterestClusterGetter_GetUserInterestClusters_Call {
	return &MockUserInterestClusterGetter_GetUserInterestClusters_Call{Call: _e.mock.On("GetUserInterestClusters", ctx, userID)}
}

func (_c *MockUserInterestClusterGetter_GetUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *MockUserInterestClusterGetter_GetUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserInterestClusterGetter_GetUserInterestClusters_Call) Return(_a0 []datasources.UserInterestCluster, _a1 error) *MockUserInterestClusterGetter_GetUserInterestClusters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserInterestClusterGetter_GetUserInterestClusters_Call) RunAndReturn(run func(context.Context, string) ([]datasources.UserInterestCluster, error)) *MockUserInterestClusterGetter_GetUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserInterestClusterGetter creates a new instance of MockUserInterestClusterGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserInterestClusterGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserInterestClusterGetter {
	mock := &MockUserInterestClusterGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
