// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserArticleInteractionStore is an autogenerated mock type for the UserArticleInteractionStore type
type MockUserArticleInteractionStore struct {
	mock.Mock
}

type MockUserArticleInteractionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserArticleInteractionStore) EXPECT() *MockUserArticleInteractionStore_Expecter {
	return &MockUserArticleInteractionStore_Expecter{mock: &_m.Mock}
}

// CountUserArticleVectorsByType provides a mock function with given fields: ctx, userID, ratingType
func (_m *MockUserArticleInteractionStore) CountUserArticleVectorsByType(ctx context.Context, userID string, ratingType domain.UserRatingType) (int64, error) {
	ret := _m.Called(ctx, userID, ratingType)

	if len(ret) == 0 {
		panic("no return value specified for CountUserArticleVectorsByType")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) (int64, error)); ok {
		return rf(ctx, userID, ratingType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) int64); ok {
		r0 = rf(ctx, userID, ratingType)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.UserRatingType) error); ok {
		r1 = rf(ctx, userID, ratingType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserArticleVectorsByType'
type MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call struct {
	*mock.Call
}

// CountUserArticleVectorsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ratingType domain.UserRatingType
func (_e *MockUserArticleInteractionStore_Expecter) CountUserArticleVectorsByType(ctx interface{}, userID interface{}, ratingType interface{}) *MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call {
	return &MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call{Call: _e.mock.On("CountUserArticleVectorsByType", ctx, userID, ratingType)}
}

func (_c *MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call) Run(run func(ctx context.Context, userID string, ratingType domain.UserRatingType)) *MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.UserRatingType))
	})
	return _c
}

func (_c *MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call) Return(_a0 int64, _a1 error) *MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call) RunAndReturn(run func(context.Context, string, domain.UserRatingType) (int64, error)) *MockUserArticleInteractionStore_CountUserArticleVectorsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserArticleVectorsByType provides a mock function with given fields: ctx, userID, ratingType
func (_m *MockUserArticleInteractionStore) GetUserArticleVectorsByType(ctx context.Context, userID string, ratingType domain.UserRatingType) ([]domain.UserArticleRating, error) {
	ret := _m.Called(ctx, userID, ratingType)

	if len(ret) == 0 {
		panic("no return value specified for GetUserArticleVectorsByType")
	}

	var r0 []domain.UserArticleRating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) ([]domain.UserArticleRating, error)); ok {
		return rf(ctx, userID, ratingType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) []domain.UserArticleRating); ok {
		r0 = rf(ctx, userID, ratingType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserArticleRating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.UserRatingType) error); ok {
		r1 = rf(ctx, userID, ratingType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserArticleVectorsByType'
type MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call struct {
	*mock.Call
}

// GetUserArticleVectorsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ratingType domain.UserRatingType
func (_e *MockUserArticleInteractionStore_Expecter) GetUserArticleVectorsByType(ctx interface{}, userID interface{}, ratingType interface{}) *MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call {
	return &MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call{Call: _e.mock.On("GetUserArticleVectorsByType", ctx, userID, ratingType)}
}

func (_c *MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call) Run(run func(ctx context.Context, userID string, ratingType domain.UserRatingType)) *MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.UserRatingType))
	})
	return _c
}

func (_c *MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call) Return(_a0 []domain.UserArticleRating, _a1 error) *MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call) RunAndReturn(run func(context.Context, string, domain.UserRatingType) ([]domain.UserArticleRating, error)) *MockUserArticleInteractionStore_GetUserArticleVectorsByType_Call {
	_c.Call.Return(run)
	return _c
}

// SetArticleRating provides a mock function with given fields: ctx, userID, articleHashID, thumbsUp, thumbsDown, vector
func (_m *MockUserArticleInteractionStore) SetArticleRating(ctx context.Context, userID string, articleHashID string, thumbsUp bool, thumbsDown bool, vector []float32) error {
	ret := _m.Called(ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)

	if len(ret) == 0 {
		panic("no return value specified for SetArticleRating")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool, bool, []float32) error); ok {
		r0 = rf(ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserArticleInteractionStore_SetArticleRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArticleRating'
type MockUserArticleInteractionStore_SetArticleRating_Call struct {
	*mock.Call
}

// SetArticleRating is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - thumbsUp bool
//   - thumbsDown bool
//   - vector []float32
func (_e *MockUserArticleInteractionStore_Expecter) SetArticleRating(ctx interface{}, userID interface{}, articleHashID interface{}, thumbsUp interface{}, thumbsDown interface{}, vector interface{}) *MockUserArticleInteractionStore_SetArticleRating_Call {
	return &MockUserArticleInteractionStore_SetArticleRating_Call{Call: _e.mock.On("SetArticleRating", ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)}
}

func (_c *MockUserArticleInteractionStore_SetArticleRating_Call) Run(run func(ctx context.Context, userID string, articleHashID string, thumbsUp bool, thumbsDown bool, vector []float32)) *MockUserArticleInteractionStore_SetArticleRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool), args[4].(bool), args[5].([]float32))
	})
	return _c
}

func (_c *MockUserArticleInteractionStore_SetArticleRating_Call) Return(_a0 error) *MockUserArticleInteractionStore_SetArticleRating_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserArticleInteractionStore_SetArticleRating_Call) RunAndReturn(run func(context.Context, string, string, bool, bool, []float32) error) *MockUserArticleInteractionStore_SetArticleRating_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserArticleInteractionStore creates a new instance of MockUserArticleInteractionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserArticleInteractionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserArticleInteractionStore {
	mock := &MockUserArticleInteractionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
