// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleReadSetter is an autogenerated mock type for the ArticleReadSetter type
type MockArticleReadSetter struct {
	mock.Mock
}

type MockArticleReadSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleReadSetter) EXPECT() *MockArticleReadSetter_Expecter {
	return &MockArticleReadSetter_Expecter{mock: &_m.Mock}
}

// SetArticleRead provides a mock function with given fields: ctx, hashID, userID, read
func (_m *MockArticleReadSetter) SetArticleRead(ctx context.Context, hashID string, userID string, read bool) error {
	ret := _m.Called(ctx, hashID, userID, read)

	if len(ret) == 0 {
		panic("no return value specified for SetArticleRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, hashID, userID, read)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArticleReadSetter_SetArticleRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArticleRead'
type MockArticleReadSetter_SetArticleRead_Call struct {
	*mock.Call
}

// SetArticleRead is a helper method to define mock.On call
//   - ctx context.Context
//   - hashID string
//   - userID string
//   - read bool
func (_e *MockArticleReadSetter_Expecter) SetArticleRead(ctx interface{}, hashID interface{}, userID interface{}, read interface{}) *MockArticleReadSetter_SetArticleRead_Call {
	return &MockArticleReadSetter_SetArticleRead_Call{Call: _e.mock.On("SetArticleRead", ctx, hashID, userID, read)}
}

func (_c *MockArticleReadSetter_SetArticleRead_Call) Run(run func(ctx context.Context, hashID string, userID string, read bool)) *MockArticleReadSetter_SetArticleRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockArticleReadSetter_SetArticleRead_Call) Return(_a0 error) *MockArticleReadSetter_SetArticleRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArticleReadSetter_SetArticleRead_Call) RunAndReturn(run func(context.Context, string, string, bool) error) *MockArticleReadSetter_SetArticleRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArticleReadSetter creates a new instance of MockArticleReadSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleReadSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleReadSetter {
	mock := &MockArticleReadSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
