// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	datasources "github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockPrecomputedRecommendationStore is an autogenerated mock type for the PrecomputedRecommendationStore type
type MockPrecomputedRecommendationStore struct {
	mock.Mock
}

type MockPrecomputedRecommendationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrecomputedRecommendationStore) EXPECT() *MockPrecomputedRecommendationStore_Expecter {
	return &MockPrecomputedRecommendationStore_Expecter{mock: &_m.Mock}
}

// DeleteUserPrecomputedRecommendations provides a mock function with given fields: ctx, userID
func (_m *MockPrecomputedRecommendationStore) DeleteUserPrecomputedRecommendations(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPrecomputedRecommendations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserPrecomputedRecommendations'
type MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call struct {
	*mock.Call
}

// DeleteUserPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPrecomputedRecommendationStore_Expecter) DeleteUserPrecomputedRecommendations(ctx interface{}, userID interface{}) *MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call {
	return &MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call{Call: _e.mock.On("DeleteUserPrecomputedRecommendations", ctx, userID)}
}

func (_c *MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string)) *MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call) Return(_a0 error) *MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call) RunAndReturn(run func(context.Context, string) error) *MockPrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrecomputedRecommendationAge provides a mock function with given fields: ctx, userID
func (_m *MockPrecomputedRecommendationStore) GetPrecomputedRecommendationAge(ctx context.Context, userID string) (time.Time, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendationAge")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendationAge'
type MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendationAge is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPrecomputedRecommendationStore_Expecter) GetPrecomputedRecommendationAge(ctx interface{}, userID interface{}) *MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call {
	return &MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call{Call: _e.mock.On("GetPrecomputedRecommendationAge", ctx, userID)}
}

func (_c *MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call) Run(run func(ctx context.Context, userID string)) *MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call) Return(_a0 time.Time, _a1 error) *MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call) RunAndReturn(run func(context.Context, string) (time.Time, error)) *MockPrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrecomputedRecommendations provides a mock function with given fields: ctx, userID, limit
func (_m *MockPrecomputedRecommendationStore) GetPrecomputedRecommendations(ctx context.Context, userID string, limit int) ([]datasources.PrecomputedRecommendation, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendations")
	}

	var r0 []datasources.PrecomputedRecommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]datasources.PrecomputedRecommendation, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []datasources.PrecomputedRecommendation); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.PrecomputedRecommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendations'
type MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *MockPrecomputedRecommendationStore_Expecter) GetPrecomputedRecommendations(ctx interface{}, userID interface{}, limit interface{}) *MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call {
	return &MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call{Call: _e.mock.On("GetPrecomputedRecommendations", ctx, userID, limit)}
}

func (_c *MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string, limit int)) *MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call) Return(_a0 []datasources.PrecomputedRecommendation, _a1 error) *MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call) RunAndReturn(run func(context.Context, string, int) ([]datasources.PrecomputedRecommendation, error)) *MockPrecomputedRecommendationStore_GetPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPrecomputedRecommendation provides a mock function with given fields: ctx, userID, articleHashID, score, source, position, generatedAt
func (_m *MockPrecomputedRecommendationStore) UpsertPrecomputedRecommendation(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time) error {
	ret := _m.Called(ctx, userID, articleHashID, score, source, position, generatedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPrecomputedRecommendation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, string, int, time.Time) error); ok {
		r0 = rf(ctx, userID, articleHashID, score, source, position, generatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPrecomputedRecommendation'
type MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call struct {
	*mock.Call
}

// UpsertPrecomputedRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - score float64
//   - source string
//   - position int
//   - generatedAt time.Time
func (_e *MockPrecomputedRecommendationStore_Expecter) UpsertPrecomputedRecommendation(ctx interface{}, userID interface{}, articleHashID interface{}, score interface{}, source interface{}, position interface{}, generatedAt interface{}) *MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call {
	return &MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call{Call: _e.mock.On("UpsertPrecomputedRecommendation", ctx, userID, articleHashID, score, source, position, generatedAt)}
}

func (_c *MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call) Run(run func(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time)) *MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(float64), args[4].(string), args[5].(int), args[6].(time.Time))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call) Return(_a0 error) *MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call) RunAndReturn(run func(context.Context, string, string, float64, string, int, time.Time) error) *MockPrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrecomputedRecommendationStore creates a new instance of MockPrecomputedRecommendationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrecomputedRecommendationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrecomputedRecommendationStore {
	mock := &MockPrecomputedRecommendationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
