// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockPrecomputedRecommendationWriter is an autogenerated mock type for the PrecomputedRecommendationWriter type
type MockPrecomputedRecommendationWriter struct {
	mock.Mock
}

type MockPrecomputedRecommendationWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrecomputedRecommendationWriter) EXPECT() *MockPrecomputedRecommendationWriter_Expecter {
	return &MockPrecomputedRecommendationWriter_Expecter{mock: &_m.Mock}
}

// DeleteUserPrecomputedRecommendations provides a mock function with given fields: ctx, userID
func (_m *MockPrecomputedRecommendationWriter) DeleteUserPrecomputedRecommendations(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPrecomputedRecommendations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserPrecomputedRecommendations'
type MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call struct {
	*mock.Call
}

// DeleteUserPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPrecomputedRecommendationWriter_Expecter) DeleteUserPrecomputedRecommendations(ctx interface{}, userID interface{}) *MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call {
	return &MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call{Call: _e.mock.On("DeleteUserPrecomputedRecommendations", ctx, userID)}
}

func (_c *MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string)) *MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call) Return(_a0 error) *MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call) RunAndReturn(run func(context.Context, string) error) *MockPrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPrecomputedRecommendation provides a mock function with given fields: ctx, userID, articleHashID, score, source, position, generatedAt
func (_m *MockPrecomputedRecommendationWriter) UpsertPrecomputedRecommendation(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time) error {
	ret := _m.Called(ctx, userID, articleHashID, score, source, position, generatedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPrecomputedRecommendation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, string, int, time.Time) error); ok {
		r0 = rf(ctx, userID, articleHashID, score, source, position, generatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPrecomputedRecommendation'
type MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call struct {
	*mock.Call
}

// UpsertPrecomputedRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - score float64
//   - source string
//   - position int
//   - generatedAt time.Time
func (_e *MockPrecomputedRecommendationWriter_Expecter) UpsertPrecomputedRecommendation(ctx interface{}, userID interface{}, articleHashID interface{}, score interface{}, source interface{}, position interface{}, generatedAt interface{}) *MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call {
	return &MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call{Call: _e.mock.On("UpsertPrecomputedRecommendation", ctx, userID, articleHashID, score, source, position, generatedAt)}
}

func (_c *MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call) Run(run func(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time)) *MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(float64), args[4].(string), args[5].(int), args[6].(time.Time))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call) Return(_a0 error) *MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call) RunAndReturn(run func(context.Context, string, string, float64, string, int, time.Time) error) *MockPrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrecomputedRecommendationWriter creates a new instance of MockPrecomputedRecommendationWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrecomputedRecommendationWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrecomputedRecommendationWriter {
	mock := &MockPrecomputedRecommendationWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
