// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDislikedArticleLister is an autogenerated mock type for the DislikedArticleLister type
type MockDislikedArticleLister struct {
	mock.Mock
}

type MockDislikedArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDislikedArticleLister) EXPECT() *MockDislikedArticleLister_Expecter {
	return &MockDislikedArticleLister_Expecter{mock: &_m.Mock}
}

// ListDislikedArticleIDs provides a mock function with given fields: ctx, userID, page, pageSize
func (_m *MockDislikedArticleLister) ListDislikedArticleIDs(ctx context.Context, userID string, page int, pageSize int) ([]string, error) {
	ret := _m.Called(ctx, userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListDislikedArticleIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]string, error)); ok {
		return rf(ctx, userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []string); ok {
		r0 = rf(ctx, userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDislikedArticleLister_ListDislikedArticleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDislikedArticleIDs'
type MockDislikedArticleLister_ListDislikedArticleIDs_Call struct {
	*mock.Call
}

// ListDislikedArticleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - pageSize int
func (_e *MockDislikedArticleLister_Expecter) ListDislikedArticleIDs(ctx interface{}, userID interface{}, page interface{}, pageSize interface{}) *MockDislikedArticleLister_ListDislikedArticleIDs_Call {
	return &MockDislikedArticleLister_ListDislikedArticleIDs_Call{Call: _e.mock.On("ListDislikedArticleIDs", ctx, userID, page, pageSize)}
}

func (_c *MockDislikedArticleLister_ListDislikedArticleIDs_Call) Run(run func(ctx context.Context, userID string, page int, pageSize int)) *MockDislikedArticleLister_ListDislikedArticleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockDislikedArticleLister_ListDislikedArticleIDs_Call) Return(_a0 []string, _a1 error) *MockDislikedArticleLister_ListDislikedArticleIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDislikedArticleLister_ListDislikedArticleIDs_Call) RunAndReturn(run func(context.Context, string, int, int) ([]string, error)) *MockDislikedArticleLister_ListDislikedArticleIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDislikedArticleLister creates a new instance of MockDislikedArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDislikedArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDislikedArticleLister {
	mock := &MockDislikedArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
