// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUsersNeedingRegenerationLister is an autogenerated mock type for the UsersNeedingRegenerationLister type
type MockUsersNeedingRegenerationLister struct {
	mock.Mock
}

type MockUsersNeedingRegenerationLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersNeedingRegenerationLister) EXPECT() *MockUsersNeedingRegenerationLister_Expecter {
	return &MockUsersNeedingRegenerationLister_Expecter{mock: &_m.Mock}
}

// ListUsersNeedingRegeneration provides a mock function with given fields: ctx
func (_m *MockUsersNeedingRegenerationLister) ListUsersNeedingRegeneration(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersNeedingRegeneration")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsersNeedingRegeneration'
type MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call struct {
	*mock.Call
}

// ListUsersNeedingRegeneration is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsersNeedingRegenerationLister_Expecter) ListUsersNeedingRegeneration(ctx interface{}) *MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call {
	return &MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call{Call: _e.mock.On("ListUsersNeedingRegeneration", ctx)}
}

func (_c *MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call) Run(run func(ctx context.Context)) *MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call) Return(_a0 []string, _a1 error) *MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockUsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersNeedingRegenerationLister creates a new instance of MockUsersNeedingRegenerationLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersNeedingRegenerationLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersNeedingRegenerationLister {
	mock := &MockUsersNeedingRegenerationLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
