// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleFetcher is an autogenerated mock type for the ArticleFetcher type
type MockArticleFetcher struct {
	mock.Mock
}

type MockArticleFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleFetcher) EXPECT() *MockArticleFetcher_Expecter {
	return &MockArticleFetcher_Expecter{mock: &_m.Mock}
}

// FetchArticlesByID provides a mock function with given fields: ctx, hashIDs
func (_m *MockArticleFetcher) FetchArticlesByID(ctx context.Context, hashIDs []string) ([]domain.Article, error) {
	ret := _m.Called(ctx, hashIDs)

	if len(ret) == 0 {
		panic("no return value specified for FetchArticlesByID")
	}

	var r0 []domain.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]domain.Article, error)); ok {
		return rf(ctx, hashIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []domain.Article); ok {
		r0 = rf(ctx, hashIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, hashIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArticleFetcher_FetchArticlesByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArticlesByID'
type MockArticleFetcher_FetchArticlesByID_Call struct {
	*mock.Call
}

// FetchArticlesByID is a helper method to define mock.On call
//   - ctx context.Context
//   - hashIDs []string
func (_e *MockArticleFetcher_Expecter) FetchArticlesByID(ctx interface{}, hashIDs interface{}) *MockArticleFetcher_FetchArticlesByID_Call {
	return &MockArticleFetcher_FetchArticlesByID_Call{Call: _e.mock.On("FetchArticlesByID", ctx, hashIDs)}
}

func (_c *MockArticleFetcher_FetchArticlesByID_Call) Run(run func(ctx context.Context, hashIDs []string)) *MockArticleFetcher_FetchArticlesByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockArticleFetcher_FetchArticlesByID_Call) Return(_a0 []domain.Article, _a1 error) *MockArticleFetcher_FetchArticlesByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArticleFetcher_FetchArticlesByID_Call) RunAndReturn(run func(context.Context, []string) ([]domain.Article, error)) *MockArticleFetcher_FetchArticlesByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArticleFetcher creates a new instance of MockArticleFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleFetcher {
	mock := &MockArticleFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
