// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserAPITokenCounter is an autogenerated mock type for the UserAPITokenCounter type
type MockUserAPITokenCounter struct {
	mock.Mock
}

type MockUserAPITokenCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAPITokenCounter) EXPECT() *MockUserAPITokenCounter_Expecter {
	return &MockUserAPITokenCounter_Expecter{mock: &_m.Mock}
}

// CountUserActiveAPITokens provides a mock function with given fields: ctx, userID
func (_m *MockUserAPITokenCounter) CountUserActiveAPITokens(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUserActiveAPITokens")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserAPITokenCounter_CountUserActiveAPITokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserActiveAPITokens'
type MockUserAPITokenCounter_CountUserActiveAPITokens_Call struct {
	*mock.Call
}

// CountUserActiveAPITokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserAPITokenCounter_Expecter) CountUserActiveAPITokens(ctx interface{}, userID interface{}) *MockUserAPITokenCounter_CountUserActiveAPITokens_Call {
	return &MockUserAPITokenCounter_CountUserActiveAPITokens_Call{Call: _e.mock.On("CountUserActiveAPITokens", ctx, userID)}
}

func (_c *MockUserAPITokenCounter_CountUserActiveAPITokens_Call) Run(run func(ctx context.Context, userID string)) *MockUserAPITokenCounter_CountUserActiveAPITokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserAPITokenCounter_CountUserActiveAPITokens_Call) Return(_a0 int64, _a1 error) *MockUserAPITokenCounter_CountUserActiveAPITokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserAPITokenCounter_CountUserActiveAPITokens_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockUserAPITokenCounter_CountUserActiveAPITokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserAPITokenCounter creates a new instance of MockUserAPITokenCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAPITokenCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAPITokenCounter {
	mock := &MockUserAPITokenCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
