// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserInterestClusterUpserter is an autogenerated mock type for the UserInterestClusterUpserter type
type MockUserInterestClusterUpserter struct {
	mock.Mock
}

type MockUserInterestClusterUpserter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserInterestClusterUpserter) EXPECT() *MockUserInterestClusterUpserter_Expecter {
	return &MockUserInterestClusterUpserter_Expecter{mock: &_m.Mock}
}

// UpsertUserInterestCluster provides a mock function with given fields: ctx, userID, clusterID, centroidVector, articleCount
func (_m *MockUserInterestClusterUpserter) UpsertUserInterestCluster(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int) error {
	ret := _m.Called(ctx, userID, clusterID, centroidVector, articleCount)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserInterestCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, []float32, int) error); ok {
		r0 = rf(ctx, userID, clusterID, centroidVector, articleCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserInterestCluster'
type MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call struct {
	*mock.Call
}

// UpsertUserInterestCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - clusterID int
//   - centroidVector []float32
//   - articleCount int
func (_e *MockUserInterestClusterUpserter_Expecter) UpsertUserInterestCluster(ctx interface{}, userID interface{}, clusterID interface{}, centroidVector interface{}, articleCount interface{}) *MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call {
	return &MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call{Call: _e.mock.On("UpsertUserInterestCluster", ctx, userID, clusterID, centroidVector, articleCount)}
}

func (_c *MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call) Run(run func(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int)) *MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].([]float32), args[4].(int))
	})
	return _c
}

func (_c *MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call) Return(_a0 error) *MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call) RunAndReturn(run func(context.Context, string, int, []float32, int) error) *MockUserInterestClusterUpserter_UpsertUserInterestCluster_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserInterestClusterUpserter creates a new instance of MockUserInterestClusterUpserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserInterestClusterUpserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserInterestClusterUpserter {
	mock := &MockUserInterestClusterUpserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
