// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmbedder is an autogenerated mock type for the Embedder type
type MockEmbedder struct {
	mock.Mock
}

type MockEmbedder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbedder) EXPECT() *MockEmbedder_Expecter {
	return &MockEmbedder_Expecter{mock: &_m.Mock}
}

// EmbedText provides a mock function with given fields: ctx, text
func (_m *MockEmbedder) EmbedText(ctx context.Context, text string) ([]float32, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for EmbedText")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = rf(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbedder_EmbedText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedText'
type MockEmbedder_EmbedText_Call struct {
	*mock.Call
}

// EmbedText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockEmbedder_Expecter) EmbedText(ctx interface{}, text interface{}) *MockEmbedder_EmbedText_Call {
	return &MockEmbedder_EmbedText_Call{Call: _e.mock.On("EmbedText", ctx, text)}
}

func (_c *MockEmbedder_EmbedText_Call) Run(run func(ctx context.Context, text string)) *MockEmbedder_EmbedText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmbedder_EmbedText_Call) Return(_a0 []float32, _a1 error) *MockEmbedder_EmbedText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbedder_EmbedText_Call) RunAndReturn(run func(context.Context, string) ([]float32, error)) *MockEmbedder_EmbedText_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbedder creates a new instance of MockEmbedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbedder {
	mock := &MockEmbedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
