// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	datasources "github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// MockPrecomputedRecommendationGetter is an autogenerated mock type for the PrecomputedRecommendationGetter type
type MockPrecomputedRecommendationGetter struct {
	mock.Mock
}

type MockPrecomputedRecommendationGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrecomputedRecommendationGetter) EXPECT() *MockPrecomputedRecommendationGetter_Expecter {
	return &MockPrecomputedRecommendationGetter_Expecter{mock: &_m.Mock}
}

// GetPrecomputedRecommendations provides a mock function with given fields: ctx, userID, limit
func (_m *MockPrecomputedRecommendationGetter) GetPrecomputedRecommendations(ctx context.Context, userID string, limit int) ([]datasources.PrecomputedRecommendation, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendations")
	}

	var r0 []datasources.PrecomputedRecommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]datasources.PrecomputedRecommendation, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []datasources.PrecomputedRecommendation); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.PrecomputedRecommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendations'
type MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *MockPrecomputedRecommendationGetter_Expecter) GetPrecomputedRecommendations(ctx interface{}, userID interface{}, limit interface{}) *MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call {
	return &MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call{Call: _e.mock.On("GetPrecomputedRecommendations", ctx, userID, limit)}
}

func (_c *MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string, limit int)) *MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call) Return(_a0 []datasources.PrecomputedRecommendation, _a1 error) *MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call) RunAndReturn(run func(context.Context, string, int) ([]datasources.PrecomputedRecommendation, error)) *MockPrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrecomputedRecommendationGetter creates a new instance of MockPrecomputedRecommendationGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrecomputedRecommendationGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrecomputedRecommendationGetter {
	mock := &MockPrecomputedRecommendationGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
