// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockSimilarArticlesByVectorLister is an autogenerated mock type for the SimilarArticlesByVectorLister type
type MockSimilarArticlesByVectorLister struct {
	mock.Mock
}

type MockSimilarArticlesByVectorLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSimilarArticlesByVectorLister) EXPECT() *MockSimilarArticlesByVectorLister_Expecter {
	return &MockSimilarArticlesByVectorLister_Expecter{mock: &_m.Mock}
}

// ListSimilarArticlesByVector provides a mock function with given fields: ctx, excludeHashIDs, vector, limit
func (_m *MockSimilarArticlesByVectorLister) ListSimilarArticlesByVector(ctx context.Context, excludeHashIDs []string, vector []float32, limit int) ([]domain.SimilarArticle, error) {
	ret := _m.Called(ctx, excludeHashIDs, vector, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSimilarArticlesByVector")
	}

	var r0 []domain.SimilarArticle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []float32, int) ([]domain.SimilarArticle, error)); ok {
		return rf(ctx, excludeHashIDs, vector, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []float32, int) []domain.SimilarArticle); ok {
		r0 = rf(ctx, excludeHashIDs, vector, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SimilarArticle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []float32, int) error); ok {
		r1 = rf(ctx, excludeHashIDs, vector, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSimilarArticlesByVector'
type MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call struct {
	*mock.Call
}

// ListSimilarArticlesByVector is a helper method to define mock.On call
//   - ctx context.Context
//   - excludeHashIDs []string
//   - vector []float32
//   - limit int
func (_e *MockSimilarArticlesByVectorLister_Expecter) ListSimilarArticlesByVector(ctx interface{}, excludeHashIDs interface{}, vector interface{}, limit interface{}) *MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call {
	return &MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call{Call: _e.mock.On("ListSimilarArticlesByVector", ctx, excludeHashIDs, vector, limit)}
}

func (_c *MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call) Run(run func(ctx context.Context, excludeHashIDs []string, vector []float32, limit int)) *MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].([]float32), args[3].(int))
	})
	return _c
}

func (_c *MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call) Return(_a0 []domain.SimilarArticle, _a1 error) *MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call) RunAndReturn(run func(context.Context, []string, []float32, int) ([]domain.SimilarArticle, error)) *MockSimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSimilarArticlesByVectorLister creates a new instance of MockSimilarArticlesByVectorLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSimilarArticlesByVectorLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSimilarArticlesByVectorLister {
	mock := &MockSimilarArticlesByVectorLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
