// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockAPITokenRepository is an autogenerated mock type for the APITokenRepository type
type MockAPITokenRepository struct {
	mock.Mock
}

type MockAPITokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPITokenRepository) EXPECT() *MockAPITokenRepository_Expecter {
	return &MockAPITokenRepository_Expecter{mock: &_m.Mock}
}

// CountUserActiveAPITokens provides a mock function with given fields: ctx, userID
func (_m *MockAPITokenRepository) CountUserActiveAPITokens(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUserActiveAPITokens")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPITokenRepository_CountUserActiveAPITokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserActiveAPITokens'
type MockAPITokenRepository_CountUserActiveAPITokens_Call struct {
	*mock.Call
}

// CountUserActiveAPITokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAPITokenRepository_Expecter) CountUserActiveAPITokens(ctx interface{}, userID interface{}) *MockAPITokenRepository_CountUserActiveAPITokens_Call {
	return &MockAPITokenRepository_CountUserActiveAPITokens_Call{Call: _e.mock.On("CountUserActiveAPITokens", ctx, userID)}
}

func (_c *MockAPITokenRepository_CountUserActiveAPITokens_Call) Run(run func(ctx context.Context, userID string)) *MockAPITokenRepository_CountUserActiveAPITokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPITokenRepository_CountUserActiveAPITokens_Call) Return(_a0 int64, _a1 error) *MockAPITokenRepository_CountUserActiveAPITokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPITokenRepository_CountUserActiveAPITokens_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockAPITokenRepository_CountUserActiveAPITokens_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAPIToken provides a mock function with given fields: ctx, id, userID, tokenHash, tokenPrefix, name, expiresAt
func (_m *MockAPITokenRepository) CreateAPIToken(ctx context.Context, id string, userID string, tokenHash string, tokenPrefix string, name *string, expiresAt *time.Time) error {
	ret := _m.Called(ctx, id, userID, tokenHash, tokenPrefix, name, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *string, *time.Time) error); ok {
		r0 = rf(ctx, id, userID, tokenHash, tokenPrefix, name, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPITokenRepository_CreateAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIToken'
type MockAPITokenRepository_CreateAPIToken_Call struct {
	*mock.Call
}

// CreateAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
//   - tokenHash string
//   - tokenPrefix string
//   - name *string
//   - expiresAt *time.Time
func (_e *MockAPITokenRepository_Expecter) CreateAPIToken(ctx interface{}, id interface{}, userID interface{}, tokenHash interface{}, tokenPrefix interface{}, name interface{}, expiresAt interface{}) *MockAPITokenRepository_CreateAPIToken_Call {
	return &MockAPITokenRepository_CreateAPIToken_Call{Call: _e.mock.On("CreateAPIToken", ctx, id, userID, tokenHash, tokenPrefix, name, expiresAt)}
}

func (_c *MockAPITokenRepository_CreateAPIToken_Call) Run(run func(ctx context.Context, id string, userID string, tokenHash string, tokenPrefix string, name *string, expiresAt *time.Time)) *MockAPITokenRepository_CreateAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(*string), args[6].(*time.Time))
	})
	return _c
}

func (_c *MockAPITokenRepository_CreateAPIToken_Call) Return(_a0 error) *MockAPITokenRepository_CreateAPIToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPITokenRepository_CreateAPIToken_Call) RunAndReturn(run func(context.Context, string, string, string, string, *string, *time.Time) error) *MockAPITokenRepository_CreateAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAPITokenByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockAPITokenRepository) GetAPITokenByHash(ctx context.Context, tokenHash string) (domain.APIToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetAPITokenByHash")
	}

	var r0 domain.APIToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.APIToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.APIToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(domain.APIToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPITokenRepository_GetAPITokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPITokenByHash'
type MockAPITokenRepository_GetAPITokenByHash_Call struct {
	*mock.Call
}

// GetAPITokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockAPITokenRepository_Expecter) GetAPITokenByHash(ctx interface{}, tokenHash interface{}) *MockAPITokenRepository_GetAPITokenByHash_Call {
	return &MockAPITokenRepository_GetAPITokenByHash_Call{Call: _e.mock.On("GetAPITokenByHash", ctx, tokenHash)}
}

func (_c *MockAPITokenRepository_GetAPITokenByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockAPITokenRepository_GetAPITokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPITokenRepository_GetAPITokenByHash_Call) Return(_a0 domain.APIToken, _a1 error) *MockAPITokenRepository_GetAPITokenByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPITokenRepository_GetAPITokenByHash_Call) RunAndReturn(run func(context.Context, string) (domain.APIToken, error)) *MockAPITokenRepository_GetAPITokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserAPITokens provides a mock function with given fields: ctx, userID
func (_m *MockAPITokenRepository) ListUserAPITokens(ctx context.Context, userID string) ([]domain.APIToken, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserAPITokens")
	}

	var r0 []domain.APIToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.APIToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.APIToken); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.APIToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPITokenRepository_ListUserAPITokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserAPITokens'
type MockAPITokenRepository_ListUserAPITokens_Call struct {
	*mock.Call
}

// ListUserAPITokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAPITokenRepository_Expecter) ListUserAPITokens(ctx interface{}, userID interface{}) *MockAPITokenRepository_ListUserAPITokens_Call {
	return &MockAPITokenRepository_ListUserAPITokens_Call{Call: _e.mock.On("ListUserAPITokens", ctx, userID)}
}

func (_c *MockAPITokenRepository_ListUserAPITokens_Call) Run(run func(ctx context.Context, userID string)) *MockAPITokenRepository_ListUserAPITokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPITokenRepository_ListUserAPITokens_Call) Return(_a0 []domain.APIToken, _a1 error) *MockAPITokenRepository_ListUserAPITokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPITokenRepository_ListUserAPITokens_Call) RunAndReturn(run func(context.Context, string) ([]domain.APIToken, error)) *MockAPITokenRepository_ListUserAPITokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAPIToken provides a mock function with given fields: ctx, tokenID, userID
func (_m *MockAPITokenRepository) RevokeAPIToken(ctx context.Context, tokenID string, userID string) error {
	ret := _m.Called(ctx, tokenID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAPIToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tokenID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPITokenRepository_RevokeAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAPIToken'
type MockAPITokenRepository_RevokeAPIToken_Call struct {
	*mock.Call
}

// RevokeAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - userID string
func (_e *MockAPITokenRepository_Expecter) RevokeAPIToken(ctx interface{}, tokenID interface{}, userID interface{}) *MockAPITokenRepository_RevokeAPIToken_Call {
	return &MockAPITokenRepository_RevokeAPIToken_Call{Call: _e.mock.On("RevokeAPIToken", ctx, tokenID, userID)}
}

func (_c *MockAPITokenRepository_RevokeAPIToken_Call) Run(run func(ctx context.Context, tokenID string, userID string)) *MockAPITokenRepository_RevokeAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAPITokenRepository_RevokeAPIToken_Call) Return(_a0 error) *MockAPITokenRepository_RevokeAPIToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPITokenRepository_RevokeAPIToken_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAPITokenRepository_RevokeAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAPITokenLastUsed provides a mock function with given fields: ctx, tokenID
func (_m *MockAPITokenRepository) UpdateAPITokenLastUsed(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAPITokenLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPITokenRepository_UpdateAPITokenLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAPITokenLastUsed'
type MockAPITokenRepository_UpdateAPITokenLastUsed_Call struct {
	*mock.Call
}

// UpdateAPITokenLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockAPITokenRepository_Expecter) UpdateAPITokenLastUsed(ctx interface{}, tokenID interface{}) *MockAPITokenRepository_UpdateAPITokenLastUsed_Call {
	return &MockAPITokenRepository_UpdateAPITokenLastUsed_Call{Call: _e.mock.On("UpdateAPITokenLastUsed", ctx, tokenID)}
}

func (_c *MockAPITokenRepository_UpdateAPITokenLastUsed_Call) Run(run func(ctx context.Context, tokenID string)) *MockAPITokenRepository_UpdateAPITokenLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPITokenRepository_UpdateAPITokenLastUsed_Call) Return(_a0 error) *MockAPITokenRepository_UpdateAPITokenLastUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPITokenRepository_UpdateAPITokenLastUsed_Call) RunAndReturn(run func(context.Context, string) error) *MockAPITokenRepository_UpdateAPITokenLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPITokenRepository creates a new instance of MockAPITokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPITokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPITokenRepository {
	mock := &MockAPITokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
