// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockSimilarityRepository is an autogenerated mock type for the SimilarityRepository type
type MockSimilarityRepository struct {
	mock.Mock
}

type MockSimilarityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSimilarityRepository) EXPECT() *MockSimilarityRepository_Expecter {
	return &MockSimilarityRepository_Expecter{mock: &_m.Mock}
}

// FetchArticleVector provides a mock function with given fields: ctx, hashID
func (_m *MockSimilarityRepository) FetchArticleVector(ctx context.Context, hashID string) ([]float32, error) {
	ret := _m.Called(ctx, hashID)

	if len(ret) == 0 {
		panic("no return value specified for FetchArticleVector")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return rf(ctx, hashID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = rf(ctx, hashID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hashID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSimilarityRepository_FetchArticleVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArticleVector'
type MockSimilarityRepository_FetchArticleVector_Call struct {
	*mock.Call
}

// FetchArticleVector is a helper method to define mock.On call
//   - ctx context.Context
//   - hashID string
func (_e *MockSimilarityRepository_Expecter) FetchArticleVector(ctx interface{}, hashID interface{}) *MockSimilarityRepository_FetchArticleVector_Call {
	return &MockSimilarityRepository_FetchArticleVector_Call{Call: _e.mock.On("FetchArticleVector", ctx, hashID)}
}

func (_c *MockSimilarityRepository_FetchArticleVector_Call) Run(run func(ctx context.Context, hashID string)) *MockSimilarityRepository_FetchArticleVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSimilarityRepository_FetchArticleVector_Call) Return(_a0 []float32, _a1 error) *MockSimilarityRepository_FetchArticleVector_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSimilarityRepository_FetchArticleVector_Call) RunAndReturn(run func(context.Context, string) ([]float32, error)) *MockSimilarityRepository_FetchArticleVector_Call {
	_c.Call.Return(run)
	return _c
}

// ListSimilarArticles provides a mock function with given fields: ctx, hashIDs, count
func (_m *MockSimilarityRepository) ListSimilarArticles(ctx context.Context, hashIDs []string, count int) ([]domain.SimilarArticle, error) {
	ret := _m.Called(ctx, hashIDs, count)

	if len(ret) == 0 {
		panic("no return value specified for ListSimilarArticles")
	}

	var r0 []domain.SimilarArticle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, int) ([]domain.SimilarArticle, error)); ok {
		return rf(ctx, hashIDs, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, int) []domain.SimilarArticle); ok {
		r0 = rf(ctx, hashIDs, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SimilarArticle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, int) error); ok {
		r1 = rf(ctx, hashIDs, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSimilarityRepository_ListSimilarArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSimilarArticles'
type MockSimilarityRepository_ListSimilarArticles_Call struct {
	*mock.Call
}

// ListSimilarArticles is a helper method to define mock.On call
//   - ctx context.Context
//   - hashIDs []string
//   - count int
func (_e *MockSimilarityRepository_Expecter) ListSimilarArticles(ctx interface{}, hashIDs interface{}, count interface{}) *MockSimilarityRepository_ListSimilarArticles_Call {
	return &MockSimilarityRepository_ListSimilarArticles_Call{Call: _e.mock.On("ListSimilarArticles", ctx, hashIDs, count)}
}

func (_c *MockSimilarityRepository_ListSimilarArticles_Call) Run(run func(ctx context.Context, hashIDs []string, count int)) *MockSimilarityRepository_ListSimilarArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(int))
	})
	return _c
}

func (_c *MockSimilarityRepository_ListSimilarArticles_Call) Return(_a0 []domain.SimilarArticle, _a1 error) *MockSimilarityRepository_ListSimilarArticles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSimilarityRepository_ListSimilarArticles_Call) RunAndReturn(run func(context.Context, []string, int) ([]domain.SimilarArticle, error)) *MockSimilarityRepository_ListSimilarArticles_Call {
	_c.Call.Return(run)
	return _c
}

// ListSimilarArticlesByVector provides a mock function with given fields: ctx, excludeHashIDs, vector, limit
func (_m *MockSimilarityRepository) ListSimilarArticlesByVector(ctx context.Context, excludeHashIDs []string, vector []float32, limit int) ([]domain.SimilarArticle, error) {
	ret := _m.Called(ctx, excludeHashIDs, vector, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSimilarArticlesByVector")
	}

	var r0 []domain.SimilarArticle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []float32, int) ([]domain.SimilarArticle, error)); ok {
		return rf(ctx, excludeHashIDs, vector, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []float32, int) []domain.SimilarArticle); ok {
		r0 = rf(ctx, excludeHashIDs, vector, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SimilarArticle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []float32, int) error); ok {
		r1 = rf(ctx, excludeHashIDs, vector, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSimilarityRepository_ListSimilarArticlesByVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSimilarArticlesByVector'
type MockSimilarityRepository_ListSimilarArticlesByVector_Call struct {
	*mock.Call
}

// ListSimilarArticlesByVector is a helper method to define mock.On call
//   - ctx context.Context
//   - excludeHashIDs []string
//   - vector []float32
//   - limit int
func (_e *MockSimilarityRepository_Expecter) ListSimilarArticlesByVector(ctx interface{}, excludeHashIDs interface{}, vector interface{}, limit interface{}) *MockSimilarityRepository_ListSimilarArticlesByVector_Call {
	return &MockSimilarityRepository_ListSimilarArticlesByVector_Call{Call: _e.mock.On("ListSimilarArticlesByVector", ctx, excludeHashIDs, vector, limit)}
}

func (_c *MockSimilarityRepository_ListSimilarArticlesByVector_Call) Run(run func(ctx context.Context, excludeHashIDs []string, vector []float32, limit int)) *MockSimilarityRepository_ListSimilarArticlesByVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].([]float32), args[3].(int))
	})
	return _c
}

func (_c *MockSimilarityRepository_ListSimilarArticlesByVector_Call) Return(_a0 []domain.SimilarArticle, _a1 error) *MockSimilarityRepository_ListSimilarArticlesByVector_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSimilarityRepository_ListSimilarArticlesByVector_Call) RunAndReturn(run func(context.Context, []string, []float32, int) ([]domain.SimilarArticle, error)) *MockSimilarityRepository_ListSimilarArticlesByVector_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSimilarityRepository creates a new instance of MockSimilarityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSimilarityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSimilarityRepository {
	mock := &MockSimilarityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
