// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserInterestClusterWriter is an autogenerated mock type for the UserInterestClusterWriter type
type MockUserInterestClusterWriter struct {
	mock.Mock
}

type MockUserInterestClusterWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserInterestClusterWriter) EXPECT() *MockUserInterestClusterWriter_Expecter {
	return &MockUserInterestClusterWriter_Expecter{mock: &_m.Mock}
}

// DeleteUserInterestClusters provides a mock function with given fields: ctx, userID
func (_m *MockUserInterestClusterWriter) DeleteUserInterestClusters(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserInterestClusters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserInterestClusterWriter_DeleteUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserInterestClusters'
type MockUserInterestClusterWriter_DeleteUserInterestClusters_Call struct {
	*mock.Call
}

// DeleteUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserInterestClusterWriter_Expecter) DeleteUserInterestClusters(ctx interface{}, userID interface{}) *MockUserInterestClusterWriter_DeleteUserInterestClusters_Call {
	return &MockUserInterestClusterWriter_DeleteUserInterestClusters_Call{Call: _e.mock.On("DeleteUserInterestClusters", ctx, userID)}
}

func (_c *MockUserInterestClusterWriter_DeleteUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *MockUserInterestClusterWriter_DeleteUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserInterestClusterWriter_DeleteUserInterestClusters_Call) Return(_a0 error) *MockUserInterestClusterWriter_DeleteUserInterestClusters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserInterestClusterWriter_DeleteUserInterestClusters_Call) RunAndReturn(run func(context.Context, string) error) *MockUserInterestClusterWriter_DeleteUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserInterestCluster provides a mock function with given fields: ctx, userID, clusterID, centroidVector, articleCount
func (_m *MockUserInterestClusterWriter) UpsertUserInterestCluster(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int) error {
	ret := _m.Called(ctx, userID, clusterID, centroidVector, articleCount)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserInterestCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, []float32, int) error); ok {
		r0 = rf(ctx, userID, clusterID, centroidVector, articleCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserInterestClusterWriter_UpsertUserInterestCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserInterestCluster'
type MockUserInterestClusterWriter_UpsertUserInterestCluster_Call struct {
	*mock.Call
}

// UpsertUserInterestCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - clusterID int
//   - centroidVector []float32
//   - articleCount int
func (_e *MockUserInterestClusterWriter_Expecter) UpsertUserInterestCluster(ctx interface{}, userID interface{}, clusterID interface{}, centroidVector interface{}, articleCount interface{}) *MockUserInterestClusterWriter_UpsertUserInterestCluster_Call {
	return &MockUserInterestClusterWriter_UpsertUserInterestCluster_Call{Call: _e.mock.On("UpsertUserInterestCluster", ctx, userID, clusterID, centroidVector, articleCount)}
}

func (_c *MockUserInterestClusterWriter_UpsertUserInterestCluster_Call) Run(run func(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int)) *MockUserInterestClusterWriter_UpsertUserInterestCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].([]float32), args[4].(int))
	})
	return _c
}

func (_c *MockUserInterestClusterWriter_UpsertUserInterestCluster_Call) Return(_a0 error) *MockUserInterestClusterWriter_UpsertUserInterestCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserInterestClusterWriter_UpsertUserInterestCluster_Call) RunAndReturn(run func(context.Context, string, int, []float32, int) error) *MockUserInterestClusterWriter_UpsertUserInterestCluster_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserInterestClusterWriter creates a new instance of MockUserInterestClusterWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserInterestClusterWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserInterestClusterWriter {
	mock := &MockUserInterestClusterWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
