// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	datasources "github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// MockUserInterestClusterStore is an autogenerated mock type for the UserInterestClusterStore type
type MockUserInterestClusterStore struct {
	mock.Mock
}

type MockUserInterestClusterStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserInterestClusterStore) EXPECT() *MockUserInterestClusterStore_Expecter {
	return &MockUserInterestClusterStore_Expecter{mock: &_m.Mock}
}

// DeleteUserInterestClusters provides a mock function with given fields: ctx, userID
func (_m *MockUserInterestClusterStore) DeleteUserInterestClusters(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserInterestClusters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserInterestClusterStore_DeleteUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserInterestClusters'
type MockUserInterestClusterStore_DeleteUserInterestClusters_Call struct {
	*mock.Call
}

// DeleteUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserInterestClusterStore_Expecter) DeleteUserInterestClusters(ctx interface{}, userID interface{}) *MockUserInterestClusterStore_DeleteUserInterestClusters_Call {
	return &MockUserInterestClusterStore_DeleteUserInterestClusters_Call{Call: _e.mock.On("DeleteUserInterestClusters", ctx, userID)}
}

func (_c *MockUserInterestClusterStore_DeleteUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *MockUserInterestClusterStore_DeleteUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserInterestClusterStore_DeleteUserInterestClusters_Call) Return(_a0 error) *MockUserInterestClusterStore_DeleteUserInterestClusters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserInterestClusterStore_DeleteUserInterestClusters_Call) RunAndReturn(run func(context.Context, string) error) *MockUserInterestClusterStore_DeleteUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInterestClusters provides a mock function with given fields: ctx, userID
func (_m *MockUserInterestClusterStore) GetUserInterestClusters(ctx context.Context, userID string) ([]datasources.UserInterestCluster, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInterestClusters")
	}

	var r0 []datasources.UserInterestCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]datasources.UserInterestCluster, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []datasources.UserInterestCluster); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.UserInterestCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserInterestClusterStore_GetUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInterestClusters'
type MockUserInterestClusterStore_GetUserInterestClusters_Call struct {
	*mock.Call
}

// GetUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserInterestClusterStore_Expecter) GetUserInterestClusters(ctx interface{}, userID interface{}) *MockUserInterestClusterStore_GetUserInterestClusters_Call {
	return &MockUserInterestClusterStore_GetUserInterestClusters_Call{Call: _e.mock.On("GetUserInterestClusters", ctx, userID)}
}

func (_c *MockUserInterestClusterStore_GetUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *MockUserInterestClusterStore_GetUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserInterestClusterStore_GetUserInterestClusters_Call) Return(_a0 []datasources.UserInterestCluster, _a1 error) *MockUserInterestClusterStore_GetUserInterestClusters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserInterestClusterStore_GetUserInterestClusters_Call) RunAndReturn(run func(context.Context, string) ([]datasources.UserInterestCluster, error)) *MockUserInterestClusterStore_GetUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserInterestCluster provides a mock function with given fields: ctx, userID, clusterID, centroidVector, articleCount
func (_m *MockUserInterestClusterStore) UpsertUserInterestCluster(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int) error {
	ret := _m.Called(ctx, userID, clusterID, centroidVector, articleCount)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserInterestCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, []float32, int) error); ok {
		r0 = rf(ctx, userID, clusterID, centroidVector, articleCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserInterestClusterStore_UpsertUserInterestCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserInterestCluster'
type MockUserInterestClusterStore_UpsertUserInterestCluster_Call struct {
	*mock.Call
}

// UpsertUserInterestCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - clusterID int
//   - centroidVector []float32
//   - articleCount int
func (_e *MockUserInterestClusterStore_Expecter) UpsertUserInterestCluster(ctx interface{}, userID interface{}, clusterID interface{}, centroidVector interface{}, articleCount interface{}) *MockUserInterestClusterStore_UpsertUserInterestCluster_Call {
	return &MockUserInterestClusterStore_UpsertUserInterestCluster_Call{Call: _e.mock.On("UpsertUserInterestCluster", ctx, userID, clusterID, centroidVector, articleCount)}
}

func (_c *MockUserInterestClusterStore_UpsertUserInterestCluster_Call) Run(run func(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int)) *MockUserInterestClusterStore_UpsertUserInterestCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].([]float32), args[4].(int))
	})
	return _c
}

func (_c *MockUserInterestClusterStore_UpsertUserInterestCluster_Call) Return(_a0 error) *MockUserInterestClusterStore_UpsertUserInterestCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserInterestClusterStore_UpsertUserInterestCluster_Call) RunAndReturn(run func(context.Context, string, int, []float32, int) error) *MockUserInterestClusterStore_UpsertUserInterestCluster_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserInterestClusterStore creates a new instance of MockUserInterestClusterStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserInterestClusterStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserInterestClusterStore {
	mock := &MockUserInterestClusterStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
