// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbeshir/alignment-research-feed/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockLatestArticleLister is an autogenerated mock type for the LatestArticleLister type
type MockLatestArticleLister struct {
	mock.Mock
}

type MockLatestArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLatestArticleLister) EXPECT() *MockLatestArticleLister_Expecter {
	return &MockLatestArticleLister_Expecter{mock: &_m.Mock}
}

// ListLatestArticleIDs provides a mock function with given fields: ctx, filters, options
func (_m *MockLatestArticleLister) ListLatestArticleIDs(ctx context.Context, filters domain.ArticleFilters, options domain.ArticleListOptions) ([]string, error) {
	ret := _m.Called(ctx, filters, options)

	if len(ret) == 0 {
		panic("no return value specified for ListLatestArticleIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ArticleFilters, domain.ArticleListOptions) ([]string, error)); ok {
		return rf(ctx, filters, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ArticleFilters, domain.ArticleListOptions) []string); ok {
		r0 = rf(ctx, filters, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ArticleFilters, domain.ArticleListOptions) error); ok {
		r1 = rf(ctx, filters, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLatestArticleLister_ListLatestArticleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLatestArticleIDs'
type MockLatestArticleLister_ListLatestArticleIDs_Call struct {
	*mock.Call
}

// ListLatestArticleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - filters domain.ArticleFilters
//   - options domain.ArticleListOptions
func (_e *MockLatestArticleLister_Expecter) ListLatestArticleIDs(ctx interface{}, filters interface{}, options interface{}) *MockLatestArticleLister_ListLatestArticleIDs_Call {
	return &MockLatestArticleLister_ListLatestArticleIDs_Call{Call: _e.mock.On("ListLatestArticleIDs", ctx, filters, options)}
}

func (_c *MockLatestArticleLister_ListLatestArticleIDs_Call) Run(run func(ctx context.Context, filters domain.ArticleFilters, options domain.ArticleListOptions)) *MockLatestArticleLister_ListLatestArticleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ArticleFilters), args[2].(domain.ArticleListOptions))
	})
	return _c
}

func (_c *MockLatestArticleLister_ListLatestArticleIDs_Call) Return(_a0 []string, _a1 error) *MockLatestArticleLister_ListLatestArticleIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLatestArticleLister_ListLatestArticleIDs_Call) RunAndReturn(run func(context.Context, domain.ArticleFilters, domain.ArticleListOptions) ([]string, error)) *MockLatestArticleLister_ListLatestArticleIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLatestArticleLister creates a new instance of MockLatestArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLatestArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLatestArticleLister {
	mock := &MockLatestArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
