// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUnreviewedArticleLister is an autogenerated mock type for the UnreviewedArticleLister type
type MockUnreviewedArticleLister struct {
	mock.Mock
}

type MockUnreviewedArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnreviewedArticleLister) EXPECT() *MockUnreviewedArticleLister_Expecter {
	return &MockUnreviewedArticleLister_Expecter{mock: &_m.Mock}
}

// ListUnreviewedArticleIDs provides a mock function with given fields: ctx, userID, page, pageSize
func (_m *MockUnreviewedArticleLister) ListUnreviewedArticleIDs(ctx context.Context, userID string, page int, pageSize int) ([]string, error) {
	ret := _m.Called(ctx, userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListUnreviewedArticleIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]string, error)); ok {
		return rf(ctx, userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []string); ok {
		r0 = rf(ctx, userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnreviewedArticleIDs'
type MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call struct {
	*mock.Call
}

// ListUnreviewedArticleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - pageSize int
func (_e *MockUnreviewedArticleLister_Expecter) ListUnreviewedArticleIDs(ctx interface{}, userID interface{}, page interface{}, pageSize interface{}) *MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call {
	return &MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call{Call: _e.mock.On("ListUnreviewedArticleIDs", ctx, userID, page, pageSize)}
}

func (_c *MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call) Run(run func(ctx context.Context, userID string, page int, pageSize int)) *MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call) Return(_a0 []string, _a1 error) *MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call) RunAndReturn(run func(context.Context, string, int, int) ([]string, error)) *MockUnreviewedArticleLister_ListUnreviewedArticleIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnreviewedArticleLister creates a new instance of MockUnreviewedArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnreviewedArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnreviewedArticleLister {
	mock := &MockUnreviewedArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
