// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	datasources "github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRecommendationStateStore is an autogenerated mock type for the UserRecommendationStateStore type
type MockUserRecommendationStateStore struct {
	mock.Mock
}

type MockUserRecommendationStateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRecommendationStateStore) EXPECT() *MockUserRecommendationStateStore_Expecter {
	return &MockUserRecommendationStateStore_Expecter{mock: &_m.Mock}
}

// GetUserRecommendationState provides a mock function with given fields: ctx, userID
func (_m *MockUserRecommendationStateStore) GetUserRecommendationState(ctx context.Context, userID string) (datasources.UserRecommendationState, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecommendationState")
	}

	var r0 datasources.UserRecommendationState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (datasources.UserRecommendationState, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) datasources.UserRecommendationState); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(datasources.UserRecommendationState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRecommendationStateStore_GetUserRecommendationState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRecommendationState'
type MockUserRecommendationStateStore_GetUserRecommendationState_Call struct {
	*mock.Call
}

// GetUserRecommendationState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRecommendationStateStore_Expecter) GetUserRecommendationState(ctx interface{}, userID interface{}) *MockUserRecommendationStateStore_GetUserRecommendationState_Call {
	return &MockUserRecommendationStateStore_GetUserRecommendationState_Call{Call: _e.mock.On("GetUserRecommendationState", ctx, userID)}
}

func (_c *MockUserRecommendationStateStore_GetUserRecommendationState_Call) Run(run func(ctx context.Context, userID string)) *MockUserRecommendationStateStore_GetUserRecommendationState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRecommendationStateStore_GetUserRecommendationState_Call) Return(_a0 datasources.UserRecommendationState, _a1 error) *MockUserRecommendationStateStore_GetUserRecommendationState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRecommendationStateStore_GetUserRecommendationState_Call) RunAndReturn(run func(context.Context, string) (datasources.UserRecommendationState, error)) *MockUserRecommendationStateStore_GetUserRecommendationState_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsersNeedingRegeneration provides a mock function with given fields: ctx
func (_m *MockUserRecommendationStateStore) ListUsersNeedingRegeneration(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersNeedingRegeneration")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsersNeedingRegeneration'
type MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call struct {
	*mock.Call
}

// ListUsersNeedingRegeneration is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRecommendationStateStore_Expecter) ListUsersNeedingRegeneration(ctx interface{}) *MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call {
	return &MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call{Call: _e.mock.On("ListUsersNeedingRegeneration", ctx)}
}

func (_c *MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call) Run(run func(ctx context.Context)) *MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call) Return(_a0 []string, _a1 error) *MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockUserRecommendationStateStore_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUserNeedsRegeneration provides a mock function with given fields: ctx, userID
func (_m *MockUserRecommendationStateStore) MarkUserNeedsRegeneration(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserNeedsRegeneration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserNeedsRegeneration'
type MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call struct {
	*mock.Call
}

// MarkUserNeedsRegeneration is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRecommendationStateStore_Expecter) MarkUserNeedsRegeneration(ctx interface{}, userID interface{}) *MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call {
	return &MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call{Call: _e.mock.On("MarkUserNeedsRegeneration", ctx, userID)}
}

func (_c *MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call) Run(run func(ctx context.Context, userID string)) *MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call) Return(_a0 error) *MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRecommendationStateStore_MarkUserNeedsRegeneration_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUserRegenerated provides a mock function with given fields: ctx, userID
func (_m *MockUserRecommendationStateStore) MarkUserRegenerated(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserRegenerated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRecommendationStateStore_MarkUserRegenerated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserRegenerated'
type MockUserRecommendationStateStore_MarkUserRegenerated_Call struct {
	*mock.Call
}

// MarkUserRegenerated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRecommendationStateStore_Expecter) MarkUserRegenerated(ctx interface{}, userID interface{}) *MockUserRecommendationStateStore_MarkUserRegenerated_Call {
	return &MockUserRecommendationStateStore_MarkUserRegenerated_Call{Call: _e.mock.On("MarkUserRegenerated", ctx, userID)}
}

func (_c *MockUserRecommendationStateStore_MarkUserRegenerated_Call) Run(run func(ctx context.Context, userID string)) *MockUserRecommendationStateStore_MarkUserRegenerated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRecommendationStateStore_MarkUserRegenerated_Call) Return(_a0 error) *MockUserRecommendationStateStore_MarkUserRegenerated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRecommendationStateStore_MarkUserRegenerated_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRecommendationStateStore_MarkUserRegenerated_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRecommendationStateStore creates a new instance of MockUserRecommendationStateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRecommendationStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRecommendationStateStore {
	mock := &MockUserRecommendationStateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
