// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// NewPrecomputedRecommendationUpserter creates a new instance of PrecomputedRecommendationUpserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrecomputedRecommendationUpserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrecomputedRecommendationUpserter {
	mock := &PrecomputedRecommendationUpserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrecomputedRecommendationUpserter is an autogenerated mock type for the PrecomputedRecommendationUpserter type
type PrecomputedRecommendationUpserter struct {
	mock.Mock
}

type PrecomputedRecommendationUpserter_Expecter struct {
	mock *mock.Mock
}

func (_m *PrecomputedRecommendationUpserter) EXPECT() *PrecomputedRecommendationUpserter_Expecter {
	return &PrecomputedRecommendationUpserter_Expecter{mock: &_m.Mock}
}

// UpsertPrecomputedRecommendation provides a mock function for the type PrecomputedRecommendationUpserter
func (_mock *PrecomputedRecommendationUpserter) UpsertPrecomputedRecommendation(ctx context.Context, params datasources.UpsertPrecomputedRecommendationParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPrecomputedRecommendation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datasources.UpsertPrecomputedRecommendationParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPrecomputedRecommendation'
type PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call struct {
	*mock.Call
}

// UpsertPrecomputedRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - score float64
//   - source string
//   - position int
//   - generatedAt time.Time
func (_e *PrecomputedRecommendationUpserter_Expecter) UpsertPrecomputedRecommendation(ctx interface{}, params interface{}) *PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call {
	return &PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call{Call: _e.mock.On("UpsertPrecomputedRecommendation", ctx, params)}
}

func (_c *PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call) Run(run func(ctx context.Context, params datasources.UpsertPrecomputedRecommendationParams)) *PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(datasources.UpsertPrecomputedRecommendationParams))
	})
	return _c
}

func (_c *PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call) Return(err error) *PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call) RunAndReturn(run func(ctx context.Context, params datasources.UpsertPrecomputedRecommendationParams) error) *PrecomputedRecommendationUpserter_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(run)
	return _c
}
