// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewPrecomputedRecommendationAgeGetter creates a new instance of PrecomputedRecommendationAgeGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrecomputedRecommendationAgeGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrecomputedRecommendationAgeGetter {
	mock := &PrecomputedRecommendationAgeGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrecomputedRecommendationAgeGetter is an autogenerated mock type for the PrecomputedRecommendationAgeGetter type
type PrecomputedRecommendationAgeGetter struct {
	mock.Mock
}

type PrecomputedRecommendationAgeGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *PrecomputedRecommendationAgeGetter) EXPECT() *PrecomputedRecommendationAgeGetter_Expecter {
	return &PrecomputedRecommendationAgeGetter_Expecter{mock: &_m.Mock}
}

// GetPrecomputedRecommendationAge provides a mock function for the type PrecomputedRecommendationAgeGetter
func (_mock *PrecomputedRecommendationAgeGetter) GetPrecomputedRecommendationAge(ctx context.Context, userID string) (time.Time, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendationAge")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendationAge'
type PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendationAge is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *PrecomputedRecommendationAgeGetter_Expecter) GetPrecomputedRecommendationAge(ctx interface{}, userID interface{}) *PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call {
	return &PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call{Call: _e.mock.On("GetPrecomputedRecommendationAge", ctx, userID)}
}

func (_c *PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call) Run(run func(ctx context.Context, userID string)) *PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call) Return(time1 time.Time, err error) *PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call) RunAndReturn(run func(ctx context.Context, userID string) (time.Time, error)) *PrecomputedRecommendationAgeGetter_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(run)
	return _c
}
