// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// NewPrecomputedRecommendationStore creates a new instance of PrecomputedRecommendationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrecomputedRecommendationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrecomputedRecommendationStore {
	mock := &PrecomputedRecommendationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrecomputedRecommendationStore is an autogenerated mock type for the PrecomputedRecommendationStore type
type PrecomputedRecommendationStore struct {
	mock.Mock
}

type PrecomputedRecommendationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PrecomputedRecommendationStore) EXPECT() *PrecomputedRecommendationStore_Expecter {
	return &PrecomputedRecommendationStore_Expecter{mock: &_m.Mock}
}

// DeleteUserPrecomputedRecommendations provides a mock function for the type PrecomputedRecommendationStore
func (_mock *PrecomputedRecommendationStore) DeleteUserPrecomputedRecommendations(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPrecomputedRecommendations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserPrecomputedRecommendations'
type PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call struct {
	*mock.Call
}

// DeleteUserPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *PrecomputedRecommendationStore_Expecter) DeleteUserPrecomputedRecommendations(ctx interface{}, userID interface{}) *PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call {
	return &PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call{Call: _e.mock.On("DeleteUserPrecomputedRecommendations", ctx, userID)}
}

func (_c *PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string)) *PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call) Return(err error) *PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *PrecomputedRecommendationStore_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrecomputedRecommendationAge provides a mock function for the type PrecomputedRecommendationStore
func (_mock *PrecomputedRecommendationStore) GetPrecomputedRecommendationAge(ctx context.Context, userID string) (time.Time, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendationAge")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendationAge'
type PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendationAge is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *PrecomputedRecommendationStore_Expecter) GetPrecomputedRecommendationAge(ctx interface{}, userID interface{}) *PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call {
	return &PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call{Call: _e.mock.On("GetPrecomputedRecommendationAge", ctx, userID)}
}

func (_c *PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call) Run(run func(ctx context.Context, userID string)) *PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call) Return(time1 time.Time, err error) *PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call) RunAndReturn(run func(ctx context.Context, userID string) (time.Time, error)) *PrecomputedRecommendationStore_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrecomputedRecommendations provides a mock function for the type PrecomputedRecommendationStore
func (_mock *PrecomputedRecommendationStore) GetPrecomputedRecommendations(ctx context.Context, userID string, limit int) ([]datasources.PrecomputedRecommendation, error) {
	ret := _mock.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendations")
	}

	var r0 []datasources.PrecomputedRecommendation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]datasources.PrecomputedRecommendation, error)); ok {
		return returnFunc(ctx, userID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []datasources.PrecomputedRecommendation); ok {
		r0 = returnFunc(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.PrecomputedRecommendation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendations'
type PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *PrecomputedRecommendationStore_Expecter) GetPrecomputedRecommendations(ctx interface{}, userID interface{}, limit interface{}) *PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call {
	return &PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call{Call: _e.mock.On("GetPrecomputedRecommendations", ctx, userID, limit)}
}

func (_c *PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string, limit int)) *PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call) Return(precomputedRecommendations []datasources.PrecomputedRecommendation, err error) *PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call {
	_c.Call.Return(precomputedRecommendations, err)
	return _c
}

func (_c *PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call) RunAndReturn(run func(ctx context.Context, userID string, limit int) ([]datasources.PrecomputedRecommendation, error)) *PrecomputedRecommendationStore_GetPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPrecomputedRecommendation provides a mock function for the type PrecomputedRecommendationStore
func (_mock *PrecomputedRecommendationStore) UpsertPrecomputedRecommendation(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time) error {
	ret := _mock.Called(ctx, userID, articleHashID, score, source, position, generatedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPrecomputedRecommendation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64, string, int, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, articleHashID, score, source, position, generatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPrecomputedRecommendation'
type PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call struct {
	*mock.Call
}

// UpsertPrecomputedRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - score float64
//   - source string
//   - position int
//   - generatedAt time.Time
func (_e *PrecomputedRecommendationStore_Expecter) UpsertPrecomputedRecommendation(ctx interface{}, userID interface{}, articleHashID interface{}, score interface{}, source interface{}, position interface{}, generatedAt interface{}) *PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call {
	return &PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call{Call: _e.mock.On("UpsertPrecomputedRecommendation", ctx, userID, articleHashID, score, source, position, generatedAt)}
}

func (_c *PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call) Run(run func(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time)) *PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 time.Time
		if args[6] != nil {
			arg6 = args[6].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call) Return(err error) *PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call) RunAndReturn(run func(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time) error) *PrecomputedRecommendationStore_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(run)
	return _c
}
