// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// NewPrecomputedRecommendationReader creates a new instance of PrecomputedRecommendationReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrecomputedRecommendationReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrecomputedRecommendationReader {
	mock := &PrecomputedRecommendationReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrecomputedRecommendationReader is an autogenerated mock type for the PrecomputedRecommendationReader type
type PrecomputedRecommendationReader struct {
	mock.Mock
}

type PrecomputedRecommendationReader_Expecter struct {
	mock *mock.Mock
}

func (_m *PrecomputedRecommendationReader) EXPECT() *PrecomputedRecommendationReader_Expecter {
	return &PrecomputedRecommendationReader_Expecter{mock: &_m.Mock}
}

// GetPrecomputedRecommendationAge provides a mock function for the type PrecomputedRecommendationReader
func (_mock *PrecomputedRecommendationReader) GetPrecomputedRecommendationAge(ctx context.Context, userID string) (time.Time, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendationAge")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendationAge'
type PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendationAge is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *PrecomputedRecommendationReader_Expecter) GetPrecomputedRecommendationAge(ctx interface{}, userID interface{}) *PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call {
	return &PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call{Call: _e.mock.On("GetPrecomputedRecommendationAge", ctx, userID)}
}

func (_c *PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call) Run(run func(ctx context.Context, userID string)) *PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call) Return(time1 time.Time, err error) *PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call) RunAndReturn(run func(ctx context.Context, userID string) (time.Time, error)) *PrecomputedRecommendationReader_GetPrecomputedRecommendationAge_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrecomputedRecommendations provides a mock function for the type PrecomputedRecommendationReader
func (_mock *PrecomputedRecommendationReader) GetPrecomputedRecommendations(ctx context.Context, userID string, limit int) ([]datasources.PrecomputedRecommendation, error) {
	ret := _mock.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendations")
	}

	var r0 []datasources.PrecomputedRecommendation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]datasources.PrecomputedRecommendation, error)); ok {
		return returnFunc(ctx, userID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []datasources.PrecomputedRecommendation); ok {
		r0 = returnFunc(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.PrecomputedRecommendation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendations'
type PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *PrecomputedRecommendationReader_Expecter) GetPrecomputedRecommendations(ctx interface{}, userID interface{}, limit interface{}) *PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call {
	return &PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call{Call: _e.mock.On("GetPrecomputedRecommendations", ctx, userID, limit)}
}

func (_c *PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string, limit int)) *PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call) Return(precomputedRecommendations []datasources.PrecomputedRecommendation, err error) *PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call {
	_c.Call.Return(precomputedRecommendations, err)
	return _c
}

func (_c *PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call) RunAndReturn(run func(ctx context.Context, userID string, limit int) ([]datasources.PrecomputedRecommendation, error)) *PrecomputedRecommendationReader_GetPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}
