// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewPrecomputedRecommendationDeleter creates a new instance of PrecomputedRecommendationDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrecomputedRecommendationDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrecomputedRecommendationDeleter {
	mock := &PrecomputedRecommendationDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrecomputedRecommendationDeleter is an autogenerated mock type for the PrecomputedRecommendationDeleter type
type PrecomputedRecommendationDeleter struct {
	mock.Mock
}

type PrecomputedRecommendationDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *PrecomputedRecommendationDeleter) EXPECT() *PrecomputedRecommendationDeleter_Expecter {
	return &PrecomputedRecommendationDeleter_Expecter{mock: &_m.Mock}
}

// DeleteUserPrecomputedRecommendations provides a mock function for the type PrecomputedRecommendationDeleter
func (_mock *PrecomputedRecommendationDeleter) DeleteUserPrecomputedRecommendations(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPrecomputedRecommendations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserPrecomputedRecommendations'
type PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call struct {
	*mock.Call
}

// DeleteUserPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *PrecomputedRecommendationDeleter_Expecter) DeleteUserPrecomputedRecommendations(ctx interface{}, userID interface{}) *PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call {
	return &PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call{Call: _e.mock.On("DeleteUserPrecomputedRecommendations", ctx, userID)}
}

func (_c *PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string)) *PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call) Return(err error) *PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *PrecomputedRecommendationDeleter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}
