// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewPrecomputedRecommendationWriter creates a new instance of PrecomputedRecommendationWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrecomputedRecommendationWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrecomputedRecommendationWriter {
	mock := &PrecomputedRecommendationWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrecomputedRecommendationWriter is an autogenerated mock type for the PrecomputedRecommendationWriter type
type PrecomputedRecommendationWriter struct {
	mock.Mock
}

type PrecomputedRecommendationWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *PrecomputedRecommendationWriter) EXPECT() *PrecomputedRecommendationWriter_Expecter {
	return &PrecomputedRecommendationWriter_Expecter{mock: &_m.Mock}
}

// DeleteUserPrecomputedRecommendations provides a mock function for the type PrecomputedRecommendationWriter
func (_mock *PrecomputedRecommendationWriter) DeleteUserPrecomputedRecommendations(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPrecomputedRecommendations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserPrecomputedRecommendations'
type PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call struct {
	*mock.Call
}

// DeleteUserPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *PrecomputedRecommendationWriter_Expecter) DeleteUserPrecomputedRecommendations(ctx interface{}, userID interface{}) *PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call {
	return &PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call{Call: _e.mock.On("DeleteUserPrecomputedRecommendations", ctx, userID)}
}

func (_c *PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string)) *PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call) Return(err error) *PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *PrecomputedRecommendationWriter_DeleteUserPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPrecomputedRecommendation provides a mock function for the type PrecomputedRecommendationWriter
func (_mock *PrecomputedRecommendationWriter) UpsertPrecomputedRecommendation(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time) error {
	ret := _mock.Called(ctx, userID, articleHashID, score, source, position, generatedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPrecomputedRecommendation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64, string, int, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, articleHashID, score, source, position, generatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPrecomputedRecommendation'
type PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call struct {
	*mock.Call
}

// UpsertPrecomputedRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - score float64
//   - source string
//   - position int
//   - generatedAt time.Time
func (_e *PrecomputedRecommendationWriter_Expecter) UpsertPrecomputedRecommendation(ctx interface{}, userID interface{}, articleHashID interface{}, score interface{}, source interface{}, position interface{}, generatedAt interface{}) *PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call {
	return &PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call{Call: _e.mock.On("UpsertPrecomputedRecommendation", ctx, userID, articleHashID, score, source, position, generatedAt)}
}

func (_c *PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call) Run(run func(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time)) *PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 time.Time
		if args[6] != nil {
			arg6 = args[6].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call) Return(err error) *PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call) RunAndReturn(run func(ctx context.Context, userID string, articleHashID string, score float64, source string, position int, generatedAt time.Time) error) *PrecomputedRecommendationWriter_UpsertPrecomputedRecommendation_Call {
	_c.Call.Return(run)
	return _c
}
