// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// NewPrecomputedRecommendationGetter creates a new instance of PrecomputedRecommendationGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrecomputedRecommendationGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrecomputedRecommendationGetter {
	mock := &PrecomputedRecommendationGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrecomputedRecommendationGetter is an autogenerated mock type for the PrecomputedRecommendationGetter type
type PrecomputedRecommendationGetter struct {
	mock.Mock
}

type PrecomputedRecommendationGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *PrecomputedRecommendationGetter) EXPECT() *PrecomputedRecommendationGetter_Expecter {
	return &PrecomputedRecommendationGetter_Expecter{mock: &_m.Mock}
}

// GetPrecomputedRecommendations provides a mock function for the type PrecomputedRecommendationGetter
func (_mock *PrecomputedRecommendationGetter) GetPrecomputedRecommendations(ctx context.Context, userID string, limit int) ([]datasources.PrecomputedRecommendation, error) {
	ret := _mock.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecomputedRecommendations")
	}

	var r0 []datasources.PrecomputedRecommendation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]datasources.PrecomputedRecommendation, error)); ok {
		return returnFunc(ctx, userID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []datasources.PrecomputedRecommendation); ok {
		r0 = returnFunc(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.PrecomputedRecommendation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecomputedRecommendations'
type PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call struct {
	*mock.Call
}

// GetPrecomputedRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *PrecomputedRecommendationGetter_Expecter) GetPrecomputedRecommendations(ctx interface{}, userID interface{}, limit interface{}) *PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call {
	return &PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call{Call: _e.mock.On("GetPrecomputedRecommendations", ctx, userID, limit)}
}

func (_c *PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call) Run(run func(ctx context.Context, userID string, limit int)) *PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call) Return(precomputedRecommendations []datasources.PrecomputedRecommendation, err error) *PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call {
	_c.Call.Return(precomputedRecommendations, err)
	return _c
}

func (_c *PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call) RunAndReturn(run func(ctx context.Context, userID string, limit int) ([]datasources.PrecomputedRecommendation, error)) *PrecomputedRecommendationGetter_GetPrecomputedRecommendations_Call {
	_c.Call.Return(run)
	return _c
}
