// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSimilarityRepository creates a new instance of SimilarityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimilarityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimilarityRepository {
	mock := &SimilarityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SimilarityRepository is an autogenerated mock type for the SimilarityRepository type
type SimilarityRepository struct {
	mock.Mock
}

type SimilarityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SimilarityRepository) EXPECT() *SimilarityRepository_Expecter {
	return &SimilarityRepository_Expecter{mock: &_m.Mock}
}

// FetchArticleVector provides a mock function for the type SimilarityRepository
func (_mock *SimilarityRepository) FetchArticleVector(ctx context.Context, hashID string) ([]float32, error) {
	ret := _mock.Called(ctx, hashID)

	if len(ret) == 0 {
		panic("no return value specified for FetchArticleVector")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return returnFunc(ctx, hashID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = returnFunc(ctx, hashID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hashID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimilarityRepository_FetchArticleVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArticleVector'
type SimilarityRepository_FetchArticleVector_Call struct {
	*mock.Call
}

// FetchArticleVector is a helper method to define mock.On call
//   - ctx context.Context
//   - hashID string
func (_e *SimilarityRepository_Expecter) FetchArticleVector(ctx interface{}, hashID interface{}) *SimilarityRepository_FetchArticleVector_Call {
	return &SimilarityRepository_FetchArticleVector_Call{Call: _e.mock.On("FetchArticleVector", ctx, hashID)}
}

func (_c *SimilarityRepository_FetchArticleVector_Call) Run(run func(ctx context.Context, hashID string)) *SimilarityRepository_FetchArticleVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SimilarityRepository_FetchArticleVector_Call) Return(float32s []float32, err error) *SimilarityRepository_FetchArticleVector_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *SimilarityRepository_FetchArticleVector_Call) RunAndReturn(run func(ctx context.Context, hashID string) ([]float32, error)) *SimilarityRepository_FetchArticleVector_Call {
	_c.Call.Return(run)
	return _c
}

// ListSimilarArticles provides a mock function for the type SimilarityRepository
func (_mock *SimilarityRepository) ListSimilarArticles(ctx context.Context, hashIDs []string, count int) ([]domain.SimilarArticle, error) {
	ret := _mock.Called(ctx, hashIDs, count)

	if len(ret) == 0 {
		panic("no return value specified for ListSimilarArticles")
	}

	var r0 []domain.SimilarArticle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int) ([]domain.SimilarArticle, error)); ok {
		return returnFunc(ctx, hashIDs, count)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int) []domain.SimilarArticle); ok {
		r0 = returnFunc(ctx, hashIDs, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SimilarArticle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, int) error); ok {
		r1 = returnFunc(ctx, hashIDs, count)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimilarityRepository_ListSimilarArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSimilarArticles'
type SimilarityRepository_ListSimilarArticles_Call struct {
	*mock.Call
}

// ListSimilarArticles is a helper method to define mock.On call
//   - ctx context.Context
//   - hashIDs []string
//   - count int
func (_e *SimilarityRepository_Expecter) ListSimilarArticles(ctx interface{}, hashIDs interface{}, count interface{}) *SimilarityRepository_ListSimilarArticles_Call {
	return &SimilarityRepository_ListSimilarArticles_Call{Call: _e.mock.On("ListSimilarArticles", ctx, hashIDs, count)}
}

func (_c *SimilarityRepository_ListSimilarArticles_Call) Run(run func(ctx context.Context, hashIDs []string, count int)) *SimilarityRepository_ListSimilarArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SimilarityRepository_ListSimilarArticles_Call) Return(similarArticles []domain.SimilarArticle, err error) *SimilarityRepository_ListSimilarArticles_Call {
	_c.Call.Return(similarArticles, err)
	return _c
}

func (_c *SimilarityRepository_ListSimilarArticles_Call) RunAndReturn(run func(ctx context.Context, hashIDs []string, count int) ([]domain.SimilarArticle, error)) *SimilarityRepository_ListSimilarArticles_Call {
	_c.Call.Return(run)
	return _c
}

// ListSimilarArticlesByVector provides a mock function for the type SimilarityRepository
func (_mock *SimilarityRepository) ListSimilarArticlesByVector(ctx context.Context, excludeHashIDs []string, vector []float32, limit int) ([]domain.SimilarArticle, error) {
	ret := _mock.Called(ctx, excludeHashIDs, vector, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSimilarArticlesByVector")
	}

	var r0 []domain.SimilarArticle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []float32, int) ([]domain.SimilarArticle, error)); ok {
		return returnFunc(ctx, excludeHashIDs, vector, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []float32, int) []domain.SimilarArticle); ok {
		r0 = returnFunc(ctx, excludeHashIDs, vector, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SimilarArticle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, []float32, int) error); ok {
		r1 = returnFunc(ctx, excludeHashIDs, vector, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimilarityRepository_ListSimilarArticlesByVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSimilarArticlesByVector'
type SimilarityRepository_ListSimilarArticlesByVector_Call struct {
	*mock.Call
}

// ListSimilarArticlesByVector is a helper method to define mock.On call
//   - ctx context.Context
//   - excludeHashIDs []string
//   - vector []float32
//   - limit int
func (_e *SimilarityRepository_Expecter) ListSimilarArticlesByVector(ctx interface{}, excludeHashIDs interface{}, vector interface{}, limit interface{}) *SimilarityRepository_ListSimilarArticlesByVector_Call {
	return &SimilarityRepository_ListSimilarArticlesByVector_Call{Call: _e.mock.On("ListSimilarArticlesByVector", ctx, excludeHashIDs, vector, limit)}
}

func (_c *SimilarityRepository_ListSimilarArticlesByVector_Call) Run(run func(ctx context.Context, excludeHashIDs []string, vector []float32, limit int)) *SimilarityRepository_ListSimilarArticlesByVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []float32
		if args[2] != nil {
			arg2 = args[2].([]float32)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SimilarityRepository_ListSimilarArticlesByVector_Call) Return(similarArticles []domain.SimilarArticle, err error) *SimilarityRepository_ListSimilarArticlesByVector_Call {
	_c.Call.Return(similarArticles, err)
	return _c
}

func (_c *SimilarityRepository_ListSimilarArticlesByVector_Call) RunAndReturn(run func(ctx context.Context, excludeHashIDs []string, vector []float32, limit int) ([]domain.SimilarArticle, error)) *SimilarityRepository_ListSimilarArticlesByVector_Call {
	_c.Call.Return(run)
	return _c
}
