// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSimilarArticlesByVectorLister creates a new instance of SimilarArticlesByVectorLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimilarArticlesByVectorLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimilarArticlesByVectorLister {
	mock := &SimilarArticlesByVectorLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SimilarArticlesByVectorLister is an autogenerated mock type for the SimilarArticlesByVectorLister type
type SimilarArticlesByVectorLister struct {
	mock.Mock
}

type SimilarArticlesByVectorLister_Expecter struct {
	mock *mock.Mock
}

func (_m *SimilarArticlesByVectorLister) EXPECT() *SimilarArticlesByVectorLister_Expecter {
	return &SimilarArticlesByVectorLister_Expecter{mock: &_m.Mock}
}

// ListSimilarArticlesByVector provides a mock function for the type SimilarArticlesByVectorLister
func (_mock *SimilarArticlesByVectorLister) ListSimilarArticlesByVector(ctx context.Context, excludeHashIDs []string, vector []float32, limit int) ([]domain.SimilarArticle, error) {
	ret := _mock.Called(ctx, excludeHashIDs, vector, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSimilarArticlesByVector")
	}

	var r0 []domain.SimilarArticle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []float32, int) ([]domain.SimilarArticle, error)); ok {
		return returnFunc(ctx, excludeHashIDs, vector, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []float32, int) []domain.SimilarArticle); ok {
		r0 = returnFunc(ctx, excludeHashIDs, vector, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SimilarArticle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, []float32, int) error); ok {
		r1 = returnFunc(ctx, excludeHashIDs, vector, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSimilarArticlesByVector'
type SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call struct {
	*mock.Call
}

// ListSimilarArticlesByVector is a helper method to define mock.On call
//   - ctx context.Context
//   - excludeHashIDs []string
//   - vector []float32
//   - limit int
func (_e *SimilarArticlesByVectorLister_Expecter) ListSimilarArticlesByVector(ctx interface{}, excludeHashIDs interface{}, vector interface{}, limit interface{}) *SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call {
	return &SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call{Call: _e.mock.On("ListSimilarArticlesByVector", ctx, excludeHashIDs, vector, limit)}
}

func (_c *SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call) Run(run func(ctx context.Context, excludeHashIDs []string, vector []float32, limit int)) *SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []float32
		if args[2] != nil {
			arg2 = args[2].([]float32)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call) Return(similarArticles []domain.SimilarArticle, err error) *SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call {
	_c.Call.Return(similarArticles, err)
	return _c
}

func (_c *SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call) RunAndReturn(run func(ctx context.Context, excludeHashIDs []string, vector []float32, limit int) ([]domain.SimilarArticle, error)) *SimilarArticlesByVectorLister_ListSimilarArticlesByVector_Call {
	_c.Call.Return(run)
	return _c
}
