// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSimilarArticleLister creates a new instance of SimilarArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimilarArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimilarArticleLister {
	mock := &SimilarArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SimilarArticleLister is an autogenerated mock type for the SimilarArticleLister type
type SimilarArticleLister struct {
	mock.Mock
}

type SimilarArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *SimilarArticleLister) EXPECT() *SimilarArticleLister_Expecter {
	return &SimilarArticleLister_Expecter{mock: &_m.Mock}
}

// ListSimilarArticles provides a mock function for the type SimilarArticleLister
func (_mock *SimilarArticleLister) ListSimilarArticles(ctx context.Context, hashIDs []string, count int) ([]domain.SimilarArticle, error) {
	ret := _mock.Called(ctx, hashIDs, count)

	if len(ret) == 0 {
		panic("no return value specified for ListSimilarArticles")
	}

	var r0 []domain.SimilarArticle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int) ([]domain.SimilarArticle, error)); ok {
		return returnFunc(ctx, hashIDs, count)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int) []domain.SimilarArticle); ok {
		r0 = returnFunc(ctx, hashIDs, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SimilarArticle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, int) error); ok {
		r1 = returnFunc(ctx, hashIDs, count)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimilarArticleLister_ListSimilarArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSimilarArticles'
type SimilarArticleLister_ListSimilarArticles_Call struct {
	*mock.Call
}

// ListSimilarArticles is a helper method to define mock.On call
//   - ctx context.Context
//   - hashIDs []string
//   - count int
func (_e *SimilarArticleLister_Expecter) ListSimilarArticles(ctx interface{}, hashIDs interface{}, count interface{}) *SimilarArticleLister_ListSimilarArticles_Call {
	return &SimilarArticleLister_ListSimilarArticles_Call{Call: _e.mock.On("ListSimilarArticles", ctx, hashIDs, count)}
}

func (_c *SimilarArticleLister_ListSimilarArticles_Call) Run(run func(ctx context.Context, hashIDs []string, count int)) *SimilarArticleLister_ListSimilarArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SimilarArticleLister_ListSimilarArticles_Call) Return(similarArticles []domain.SimilarArticle, err error) *SimilarArticleLister_ListSimilarArticles_Call {
	_c.Call.Return(similarArticles, err)
	return _c
}

func (_c *SimilarArticleLister_ListSimilarArticles_Call) RunAndReturn(run func(ctx context.Context, hashIDs []string, count int) ([]domain.SimilarArticle, error)) *SimilarArticleLister_ListSimilarArticles_Call {
	_c.Call.Return(run)
	return _c
}
