// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewThumbsUpArticleLister creates a new instance of ThumbsUpArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThumbsUpArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThumbsUpArticleLister {
	mock := &ThumbsUpArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ThumbsUpArticleLister is an autogenerated mock type for the ThumbsUpArticleLister type
type ThumbsUpArticleLister struct {
	mock.Mock
}

type ThumbsUpArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *ThumbsUpArticleLister) EXPECT() *ThumbsUpArticleLister_Expecter {
	return &ThumbsUpArticleLister_Expecter{mock: &_m.Mock}
}

// ListThumbsUpArticleIDs provides a mock function for the type ThumbsUpArticleLister
func (_mock *ThumbsUpArticleLister) ListThumbsUpArticleIDs(ctx context.Context, userID string) ([]string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListThumbsUpArticleIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListThumbsUpArticleIDs'
type ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call struct {
	*mock.Call
}

// ListThumbsUpArticleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ThumbsUpArticleLister_Expecter) ListThumbsUpArticleIDs(ctx interface{}, userID interface{}) *ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call {
	return &ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call{Call: _e.mock.On("ListThumbsUpArticleIDs", ctx, userID)}
}

func (_c *ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call) Run(run func(ctx context.Context, userID string)) *ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call) Return(strings []string, err error) *ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]string, error)) *ThumbsUpArticleLister_ListThumbsUpArticleIDs_Call {
	_c.Call.Return(run)
	return _c
}
