// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// NewUserInterestClusterStore creates a new instance of UserInterestClusterStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInterestClusterStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInterestClusterStore {
	mock := &UserInterestClusterStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserInterestClusterStore is an autogenerated mock type for the UserInterestClusterStore type
type UserInterestClusterStore struct {
	mock.Mock
}

type UserInterestClusterStore_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInterestClusterStore) EXPECT() *UserInterestClusterStore_Expecter {
	return &UserInterestClusterStore_Expecter{mock: &_m.Mock}
}

// DeleteUserInterestClusters provides a mock function for the type UserInterestClusterStore
func (_mock *UserInterestClusterStore) DeleteUserInterestClusters(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserInterestClusters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserInterestClusterStore_DeleteUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserInterestClusters'
type UserInterestClusterStore_DeleteUserInterestClusters_Call struct {
	*mock.Call
}

// DeleteUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserInterestClusterStore_Expecter) DeleteUserInterestClusters(ctx interface{}, userID interface{}) *UserInterestClusterStore_DeleteUserInterestClusters_Call {
	return &UserInterestClusterStore_DeleteUserInterestClusters_Call{Call: _e.mock.On("DeleteUserInterestClusters", ctx, userID)}
}

func (_c *UserInterestClusterStore_DeleteUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *UserInterestClusterStore_DeleteUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInterestClusterStore_DeleteUserInterestClusters_Call) Return(err error) *UserInterestClusterStore_DeleteUserInterestClusters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserInterestClusterStore_DeleteUserInterestClusters_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserInterestClusterStore_DeleteUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInterestClusters provides a mock function for the type UserInterestClusterStore
func (_mock *UserInterestClusterStore) GetUserInterestClusters(ctx context.Context, userID string) ([]datasources.UserInterestCluster, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInterestClusters")
	}

	var r0 []datasources.UserInterestCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]datasources.UserInterestCluster, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []datasources.UserInterestCluster); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.UserInterestCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserInterestClusterStore_GetUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInterestClusters'
type UserInterestClusterStore_GetUserInterestClusters_Call struct {
	*mock.Call
}

// GetUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserInterestClusterStore_Expecter) GetUserInterestClusters(ctx interface{}, userID interface{}) *UserInterestClusterStore_GetUserInterestClusters_Call {
	return &UserInterestClusterStore_GetUserInterestClusters_Call{Call: _e.mock.On("GetUserInterestClusters", ctx, userID)}
}

func (_c *UserInterestClusterStore_GetUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *UserInterestClusterStore_GetUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInterestClusterStore_GetUserInterestClusters_Call) Return(userInterestClusters []datasources.UserInterestCluster, err error) *UserInterestClusterStore_GetUserInterestClusters_Call {
	_c.Call.Return(userInterestClusters, err)
	return _c
}

func (_c *UserInterestClusterStore_GetUserInterestClusters_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]datasources.UserInterestCluster, error)) *UserInterestClusterStore_GetUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserInterestCluster provides a mock function for the type UserInterestClusterStore
func (_mock *UserInterestClusterStore) UpsertUserInterestCluster(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int) error {
	ret := _mock.Called(ctx, userID, clusterID, centroidVector, articleCount)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserInterestCluster")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, []float32, int) error); ok {
		r0 = returnFunc(ctx, userID, clusterID, centroidVector, articleCount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserInterestClusterStore_UpsertUserInterestCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserInterestCluster'
type UserInterestClusterStore_UpsertUserInterestCluster_Call struct {
	*mock.Call
}

// UpsertUserInterestCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - clusterID int
//   - centroidVector []float32
//   - articleCount int
func (_e *UserInterestClusterStore_Expecter) UpsertUserInterestCluster(ctx interface{}, userID interface{}, clusterID interface{}, centroidVector interface{}, articleCount interface{}) *UserInterestClusterStore_UpsertUserInterestCluster_Call {
	return &UserInterestClusterStore_UpsertUserInterestCluster_Call{Call: _e.mock.On("UpsertUserInterestCluster", ctx, userID, clusterID, centroidVector, articleCount)}
}

func (_c *UserInterestClusterStore_UpsertUserInterestCluster_Call) Run(run func(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int)) *UserInterestClusterStore_UpsertUserInterestCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []float32
		if args[3] != nil {
			arg3 = args[3].([]float32)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UserInterestClusterStore_UpsertUserInterestCluster_Call) Return(err error) *UserInterestClusterStore_UpsertUserInterestCluster_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserInterestClusterStore_UpsertUserInterestCluster_Call) RunAndReturn(run func(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int) error) *UserInterestClusterStore_UpsertUserInterestCluster_Call {
	_c.Call.Return(run)
	return _c
}
