// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRecommendationStateStore creates a new instance of UserRecommendationStateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRecommendationStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRecommendationStateStore {
	mock := &UserRecommendationStateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRecommendationStateStore is an autogenerated mock type for the UserRecommendationStateStore type
type UserRecommendationStateStore struct {
	mock.Mock
}

type UserRecommendationStateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRecommendationStateStore) EXPECT() *UserRecommendationStateStore_Expecter {
	return &UserRecommendationStateStore_Expecter{mock: &_m.Mock}
}

// GetUserRecommendationState provides a mock function for the type UserRecommendationStateStore
func (_mock *UserRecommendationStateStore) GetUserRecommendationState(ctx context.Context, userID string) (datasources.UserRecommendationState, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecommendationState")
	}

	var r0 datasources.UserRecommendationState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (datasources.UserRecommendationState, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) datasources.UserRecommendationState); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(datasources.UserRecommendationState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRecommendationStateStore_GetUserRecommendationState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRecommendationState'
type UserRecommendationStateStore_GetUserRecommendationState_Call struct {
	*mock.Call
}

// GetUserRecommendationState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRecommendationStateStore_Expecter) GetUserRecommendationState(ctx interface{}, userID interface{}) *UserRecommendationStateStore_GetUserRecommendationState_Call {
	return &UserRecommendationStateStore_GetUserRecommendationState_Call{Call: _e.mock.On("GetUserRecommendationState", ctx, userID)}
}

func (_c *UserRecommendationStateStore_GetUserRecommendationState_Call) Run(run func(ctx context.Context, userID string)) *UserRecommendationStateStore_GetUserRecommendationState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRecommendationStateStore_GetUserRecommendationState_Call) Return(userRecommendationState datasources.UserRecommendationState, err error) *UserRecommendationStateStore_GetUserRecommendationState_Call {
	_c.Call.Return(userRecommendationState, err)
	return _c
}

func (_c *UserRecommendationStateStore_GetUserRecommendationState_Call) RunAndReturn(run func(ctx context.Context, userID string) (datasources.UserRecommendationState, error)) *UserRecommendationStateStore_GetUserRecommendationState_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsersNeedingRegeneration provides a mock function for the type UserRecommendationStateStore
func (_mock *UserRecommendationStateStore) ListUsersNeedingRegeneration(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersNeedingRegeneration")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRecommendationStateStore_ListUsersNeedingRegeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsersNeedingRegeneration'
type UserRecommendationStateStore_ListUsersNeedingRegeneration_Call struct {
	*mock.Call
}

// ListUsersNeedingRegeneration is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRecommendationStateStore_Expecter) ListUsersNeedingRegeneration(ctx interface{}) *UserRecommendationStateStore_ListUsersNeedingRegeneration_Call {
	return &UserRecommendationStateStore_ListUsersNeedingRegeneration_Call{Call: _e.mock.On("ListUsersNeedingRegeneration", ctx)}
}

func (_c *UserRecommendationStateStore_ListUsersNeedingRegeneration_Call) Run(run func(ctx context.Context)) *UserRecommendationStateStore_ListUsersNeedingRegeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRecommendationStateStore_ListUsersNeedingRegeneration_Call) Return(strings []string, err error) *UserRecommendationStateStore_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *UserRecommendationStateStore_ListUsersNeedingRegeneration_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *UserRecommendationStateStore_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUserNeedsRegeneration provides a mock function for the type UserRecommendationStateStore
func (_mock *UserRecommendationStateStore) MarkUserNeedsRegeneration(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserNeedsRegeneration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRecommendationStateStore_MarkUserNeedsRegeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserNeedsRegeneration'
type UserRecommendationStateStore_MarkUserNeedsRegeneration_Call struct {
	*mock.Call
}

// MarkUserNeedsRegeneration is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRecommendationStateStore_Expecter) MarkUserNeedsRegeneration(ctx interface{}, userID interface{}) *UserRecommendationStateStore_MarkUserNeedsRegeneration_Call {
	return &UserRecommendationStateStore_MarkUserNeedsRegeneration_Call{Call: _e.mock.On("MarkUserNeedsRegeneration", ctx, userID)}
}

func (_c *UserRecommendationStateStore_MarkUserNeedsRegeneration_Call) Run(run func(ctx context.Context, userID string)) *UserRecommendationStateStore_MarkUserNeedsRegeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRecommendationStateStore_MarkUserNeedsRegeneration_Call) Return(err error) *UserRecommendationStateStore_MarkUserNeedsRegeneration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRecommendationStateStore_MarkUserNeedsRegeneration_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserRecommendationStateStore_MarkUserNeedsRegeneration_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUserRegenerated provides a mock function for the type UserRecommendationStateStore
func (_mock *UserRecommendationStateStore) MarkUserRegenerated(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserRegenerated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRecommendationStateStore_MarkUserRegenerated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserRegenerated'
type UserRecommendationStateStore_MarkUserRegenerated_Call struct {
	*mock.Call
}

// MarkUserRegenerated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRecommendationStateStore_Expecter) MarkUserRegenerated(ctx interface{}, userID interface{}) *UserRecommendationStateStore_MarkUserRegenerated_Call {
	return &UserRecommendationStateStore_MarkUserRegenerated_Call{Call: _e.mock.On("MarkUserRegenerated", ctx, userID)}
}

func (_c *UserRecommendationStateStore_MarkUserRegenerated_Call) Run(run func(ctx context.Context, userID string)) *UserRecommendationStateStore_MarkUserRegenerated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRecommendationStateStore_MarkUserRegenerated_Call) Return(err error) *UserRecommendationStateStore_MarkUserRegenerated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRecommendationStateStore_MarkUserRegenerated_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserRecommendationStateStore_MarkUserRegenerated_Call {
	_c.Call.Return(run)
	return _c
}
