// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// NewUserInterestClusterGetter creates a new instance of UserInterestClusterGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInterestClusterGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInterestClusterGetter {
	mock := &UserInterestClusterGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserInterestClusterGetter is an autogenerated mock type for the UserInterestClusterGetter type
type UserInterestClusterGetter struct {
	mock.Mock
}

type UserInterestClusterGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInterestClusterGetter) EXPECT() *UserInterestClusterGetter_Expecter {
	return &UserInterestClusterGetter_Expecter{mock: &_m.Mock}
}

// GetUserInterestClusters provides a mock function for the type UserInterestClusterGetter
func (_mock *UserInterestClusterGetter) GetUserInterestClusters(ctx context.Context, userID string) ([]datasources.UserInterestCluster, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInterestClusters")
	}

	var r0 []datasources.UserInterestCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]datasources.UserInterestCluster, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []datasources.UserInterestCluster); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasources.UserInterestCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserInterestClusterGetter_GetUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInterestClusters'
type UserInterestClusterGetter_GetUserInterestClusters_Call struct {
	*mock.Call
}

// GetUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserInterestClusterGetter_Expecter) GetUserInterestClusters(ctx interface{}, userID interface{}) *UserInterestClusterGetter_GetUserInterestClusters_Call {
	return &UserInterestClusterGetter_GetUserInterestClusters_Call{Call: _e.mock.On("GetUserInterestClusters", ctx, userID)}
}

func (_c *UserInterestClusterGetter_GetUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *UserInterestClusterGetter_GetUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInterestClusterGetter_GetUserInterestClusters_Call) Return(userInterestClusters []datasources.UserInterestCluster, err error) *UserInterestClusterGetter_GetUserInterestClusters_Call {
	_c.Call.Return(userInterestClusters, err)
	return _c
}

func (_c *UserInterestClusterGetter_GetUserInterestClusters_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]datasources.UserInterestCluster, error)) *UserInterestClusterGetter_GetUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}
