// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewUserArticleVectorsGetter creates a new instance of UserArticleVectorsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserArticleVectorsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserArticleVectorsGetter {
	mock := &UserArticleVectorsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserArticleVectorsGetter is an autogenerated mock type for the UserArticleVectorsGetter type
type UserArticleVectorsGetter struct {
	mock.Mock
}

type UserArticleVectorsGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserArticleVectorsGetter) EXPECT() *UserArticleVectorsGetter_Expecter {
	return &UserArticleVectorsGetter_Expecter{mock: &_m.Mock}
}

// GetUserArticleVectorsByType provides a mock function for the type UserArticleVectorsGetter
func (_mock *UserArticleVectorsGetter) GetUserArticleVectorsByType(ctx context.Context, userID string, ratingType domain.UserRatingType) ([]domain.UserArticleRating, error) {
	ret := _mock.Called(ctx, userID, ratingType)

	if len(ret) == 0 {
		panic("no return value specified for GetUserArticleVectorsByType")
	}

	var r0 []domain.UserArticleRating
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) ([]domain.UserArticleRating, error)); ok {
		return returnFunc(ctx, userID, ratingType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) []domain.UserArticleRating); ok {
		r0 = returnFunc(ctx, userID, ratingType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserArticleRating)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.UserRatingType) error); ok {
		r1 = returnFunc(ctx, userID, ratingType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserArticleVectorsGetter_GetUserArticleVectorsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserArticleVectorsByType'
type UserArticleVectorsGetter_GetUserArticleVectorsByType_Call struct {
	*mock.Call
}

// GetUserArticleVectorsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ratingType domain.UserRatingType
func (_e *UserArticleVectorsGetter_Expecter) GetUserArticleVectorsByType(ctx interface{}, userID interface{}, ratingType interface{}) *UserArticleVectorsGetter_GetUserArticleVectorsByType_Call {
	return &UserArticleVectorsGetter_GetUserArticleVectorsByType_Call{Call: _e.mock.On("GetUserArticleVectorsByType", ctx, userID, ratingType)}
}

func (_c *UserArticleVectorsGetter_GetUserArticleVectorsByType_Call) Run(run func(ctx context.Context, userID string, ratingType domain.UserRatingType)) *UserArticleVectorsGetter_GetUserArticleVectorsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.UserRatingType
		if args[2] != nil {
			arg2 = args[2].(domain.UserRatingType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserArticleVectorsGetter_GetUserArticleVectorsByType_Call) Return(userArticleRatings []domain.UserArticleRating, err error) *UserArticleVectorsGetter_GetUserArticleVectorsByType_Call {
	_c.Call.Return(userArticleRatings, err)
	return _c
}

func (_c *UserArticleVectorsGetter_GetUserArticleVectorsByType_Call) RunAndReturn(run func(ctx context.Context, userID string, ratingType domain.UserRatingType) ([]domain.UserArticleRating, error)) *UserArticleVectorsGetter_GetUserArticleVectorsByType_Call {
	_c.Call.Return(run)
	return _c
}
