// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUsersNeedingRegenerationLister creates a new instance of UsersNeedingRegenerationLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersNeedingRegenerationLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersNeedingRegenerationLister {
	mock := &UsersNeedingRegenerationLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsersNeedingRegenerationLister is an autogenerated mock type for the UsersNeedingRegenerationLister type
type UsersNeedingRegenerationLister struct {
	mock.Mock
}

type UsersNeedingRegenerationLister_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersNeedingRegenerationLister) EXPECT() *UsersNeedingRegenerationLister_Expecter {
	return &UsersNeedingRegenerationLister_Expecter{mock: &_m.Mock}
}

// ListUsersNeedingRegeneration provides a mock function for the type UsersNeedingRegenerationLister
func (_mock *UsersNeedingRegenerationLister) ListUsersNeedingRegeneration(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersNeedingRegeneration")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsersNeedingRegeneration'
type UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call struct {
	*mock.Call
}

// ListUsersNeedingRegeneration is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UsersNeedingRegenerationLister_Expecter) ListUsersNeedingRegeneration(ctx interface{}) *UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call {
	return &UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call{Call: _e.mock.On("ListUsersNeedingRegeneration", ctx)}
}

func (_c *UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call) Run(run func(ctx context.Context)) *UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call) Return(strings []string, err error) *UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *UsersNeedingRegenerationLister_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(run)
	return _c
}
