// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserRecommendationRegenerationStatusRepository creates a new instance of UserRecommendationRegenerationStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRecommendationRegenerationStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRecommendationRegenerationStatusRepository {
	mock := &UserRecommendationRegenerationStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRecommendationRegenerationStatusRepository is an autogenerated mock type for the UserRecommendationRegenerationStatusRepository type
type UserRecommendationRegenerationStatusRepository struct {
	mock.Mock
}

type UserRecommendationRegenerationStatusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRecommendationRegenerationStatusRepository) EXPECT() *UserRecommendationRegenerationStatusRepository_Expecter {
	return &UserRecommendationRegenerationStatusRepository_Expecter{mock: &_m.Mock}
}

// ListUsersNeedingRegeneration provides a mock function for the type UserRecommendationRegenerationStatusRepository
func (_mock *UserRecommendationRegenerationStatusRepository) ListUsersNeedingRegeneration(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersNeedingRegeneration")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsersNeedingRegeneration'
type UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call struct {
	*mock.Call
}

// ListUsersNeedingRegeneration is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRecommendationRegenerationStatusRepository_Expecter) ListUsersNeedingRegeneration(ctx interface{}) *UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call {
	return &UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call{Call: _e.mock.On("ListUsersNeedingRegeneration", ctx)}
}

func (_c *UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call) Run(run func(ctx context.Context)) *UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call) Return(strings []string, err error) *UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *UserRecommendationRegenerationStatusRepository_ListUsersNeedingRegeneration_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUserRegenerated provides a mock function for the type UserRecommendationRegenerationStatusRepository
func (_mock *UserRecommendationRegenerationStatusRepository) MarkUserRegenerated(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserRegenerated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserRegenerated'
type UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call struct {
	*mock.Call
}

// MarkUserRegenerated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRecommendationRegenerationStatusRepository_Expecter) MarkUserRegenerated(ctx interface{}, userID interface{}) *UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call {
	return &UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call{Call: _e.mock.On("MarkUserRegenerated", ctx, userID)}
}

func (_c *UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call) Run(run func(ctx context.Context, userID string)) *UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call) Return(err error) *UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserRecommendationRegenerationStatusRepository_MarkUserRegenerated_Call {
	_c.Call.Return(run)
	return _c
}
