// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewUserArticleInteractionStore creates a new instance of UserArticleInteractionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserArticleInteractionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserArticleInteractionStore {
	mock := &UserArticleInteractionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserArticleInteractionStore is an autogenerated mock type for the UserArticleInteractionStore type
type UserArticleInteractionStore struct {
	mock.Mock
}

type UserArticleInteractionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *UserArticleInteractionStore) EXPECT() *UserArticleInteractionStore_Expecter {
	return &UserArticleInteractionStore_Expecter{mock: &_m.Mock}
}

// CountUserArticleVectorsByType provides a mock function for the type UserArticleInteractionStore
func (_mock *UserArticleInteractionStore) CountUserArticleVectorsByType(ctx context.Context, userID string, ratingType domain.UserRatingType) (int64, error) {
	ret := _mock.Called(ctx, userID, ratingType)

	if len(ret) == 0 {
		panic("no return value specified for CountUserArticleVectorsByType")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) (int64, error)); ok {
		return returnFunc(ctx, userID, ratingType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) int64); ok {
		r0 = returnFunc(ctx, userID, ratingType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.UserRatingType) error); ok {
		r1 = returnFunc(ctx, userID, ratingType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserArticleInteractionStore_CountUserArticleVectorsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserArticleVectorsByType'
type UserArticleInteractionStore_CountUserArticleVectorsByType_Call struct {
	*mock.Call
}

// CountUserArticleVectorsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ratingType domain.UserRatingType
func (_e *UserArticleInteractionStore_Expecter) CountUserArticleVectorsByType(ctx interface{}, userID interface{}, ratingType interface{}) *UserArticleInteractionStore_CountUserArticleVectorsByType_Call {
	return &UserArticleInteractionStore_CountUserArticleVectorsByType_Call{Call: _e.mock.On("CountUserArticleVectorsByType", ctx, userID, ratingType)}
}

func (_c *UserArticleInteractionStore_CountUserArticleVectorsByType_Call) Run(run func(ctx context.Context, userID string, ratingType domain.UserRatingType)) *UserArticleInteractionStore_CountUserArticleVectorsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.UserRatingType
		if args[2] != nil {
			arg2 = args[2].(domain.UserRatingType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserArticleInteractionStore_CountUserArticleVectorsByType_Call) Return(n int64, err error) *UserArticleInteractionStore_CountUserArticleVectorsByType_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UserArticleInteractionStore_CountUserArticleVectorsByType_Call) RunAndReturn(run func(ctx context.Context, userID string, ratingType domain.UserRatingType) (int64, error)) *UserArticleInteractionStore_CountUserArticleVectorsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserArticleVectorsByType provides a mock function for the type UserArticleInteractionStore
func (_mock *UserArticleInteractionStore) GetUserArticleVectorsByType(ctx context.Context, userID string, ratingType domain.UserRatingType) ([]domain.UserArticleRating, error) {
	ret := _mock.Called(ctx, userID, ratingType)

	if len(ret) == 0 {
		panic("no return value specified for GetUserArticleVectorsByType")
	}

	var r0 []domain.UserArticleRating
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) ([]domain.UserArticleRating, error)); ok {
		return returnFunc(ctx, userID, ratingType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) []domain.UserArticleRating); ok {
		r0 = returnFunc(ctx, userID, ratingType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserArticleRating)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.UserRatingType) error); ok {
		r1 = returnFunc(ctx, userID, ratingType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserArticleInteractionStore_GetUserArticleVectorsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserArticleVectorsByType'
type UserArticleInteractionStore_GetUserArticleVectorsByType_Call struct {
	*mock.Call
}

// GetUserArticleVectorsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ratingType domain.UserRatingType
func (_e *UserArticleInteractionStore_Expecter) GetUserArticleVectorsByType(ctx interface{}, userID interface{}, ratingType interface{}) *UserArticleInteractionStore_GetUserArticleVectorsByType_Call {
	return &UserArticleInteractionStore_GetUserArticleVectorsByType_Call{Call: _e.mock.On("GetUserArticleVectorsByType", ctx, userID, ratingType)}
}

func (_c *UserArticleInteractionStore_GetUserArticleVectorsByType_Call) Run(run func(ctx context.Context, userID string, ratingType domain.UserRatingType)) *UserArticleInteractionStore_GetUserArticleVectorsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.UserRatingType
		if args[2] != nil {
			arg2 = args[2].(domain.UserRatingType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserArticleInteractionStore_GetUserArticleVectorsByType_Call) Return(userArticleRatings []domain.UserArticleRating, err error) *UserArticleInteractionStore_GetUserArticleVectorsByType_Call {
	_c.Call.Return(userArticleRatings, err)
	return _c
}

func (_c *UserArticleInteractionStore_GetUserArticleVectorsByType_Call) RunAndReturn(run func(ctx context.Context, userID string, ratingType domain.UserRatingType) ([]domain.UserArticleRating, error)) *UserArticleInteractionStore_GetUserArticleVectorsByType_Call {
	_c.Call.Return(run)
	return _c
}

// SetArticleRating provides a mock function for the type UserArticleInteractionStore
func (_mock *UserArticleInteractionStore) SetArticleRating(ctx context.Context, userID string, articleHashID string, thumbsUp *bool, thumbsDown *bool, vector []float32) error {
	ret := _mock.Called(ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)

	if len(ret) == 0 {
		panic("no return value specified for SetArticleRating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *bool, *bool, []float32) error); ok {
		r0 = returnFunc(ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserArticleInteractionStore_SetArticleRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArticleRating'
type UserArticleInteractionStore_SetArticleRating_Call struct {
	*mock.Call
}

// SetArticleRating is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - articleHashID string
//   - thumbsUp *bool
//   - thumbsDown *bool
//   - vector []float32
func (_e *UserArticleInteractionStore_Expecter) SetArticleRating(ctx interface{}, userID interface{}, articleHashID interface{}, thumbsUp interface{}, thumbsDown interface{}, vector interface{}) *UserArticleInteractionStore_SetArticleRating_Call {
	return &UserArticleInteractionStore_SetArticleRating_Call{Call: _e.mock.On("SetArticleRating", ctx, userID, articleHashID, thumbsUp, thumbsDown, vector)}
}

func (_c *UserArticleInteractionStore_SetArticleRating_Call) Run(run func(ctx context.Context, userID string, articleHashID string, thumbsUp *bool, thumbsDown *bool, vector []float32)) *UserArticleInteractionStore_SetArticleRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *bool
		if args[3] != nil {
			arg3 = args[3].(*bool)
		}
		var arg4 *bool
		if args[4] != nil {
			arg4 = args[4].(*bool)
		}
		var arg5 []float32
		if args[5] != nil {
			arg5 = args[5].([]float32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *UserArticleInteractionStore_SetArticleRating_Call) Return(err error) *UserArticleInteractionStore_SetArticleRating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserArticleInteractionStore_SetArticleRating_Call) RunAndReturn(run func(ctx context.Context, userID string, articleHashID string, thumbsUp *bool, thumbsDown *bool, vector []float32) error) *UserArticleInteractionStore_SetArticleRating_Call {
	_c.Call.Return(run)
	return _c
}
