// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserRegeneratedMarker creates a new instance of UserRegeneratedMarker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRegeneratedMarker(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRegeneratedMarker {
	mock := &UserRegeneratedMarker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRegeneratedMarker is an autogenerated mock type for the UserRegeneratedMarker type
type UserRegeneratedMarker struct {
	mock.Mock
}

type UserRegeneratedMarker_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRegeneratedMarker) EXPECT() *UserRegeneratedMarker_Expecter {
	return &UserRegeneratedMarker_Expecter{mock: &_m.Mock}
}

// MarkUserRegenerated provides a mock function for the type UserRegeneratedMarker
func (_mock *UserRegeneratedMarker) MarkUserRegenerated(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserRegenerated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRegeneratedMarker_MarkUserRegenerated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserRegenerated'
type UserRegeneratedMarker_MarkUserRegenerated_Call struct {
	*mock.Call
}

// MarkUserRegenerated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRegeneratedMarker_Expecter) MarkUserRegenerated(ctx interface{}, userID interface{}) *UserRegeneratedMarker_MarkUserRegenerated_Call {
	return &UserRegeneratedMarker_MarkUserRegenerated_Call{Call: _e.mock.On("MarkUserRegenerated", ctx, userID)}
}

func (_c *UserRegeneratedMarker_MarkUserRegenerated_Call) Run(run func(ctx context.Context, userID string)) *UserRegeneratedMarker_MarkUserRegenerated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRegeneratedMarker_MarkUserRegenerated_Call) Return(err error) *UserRegeneratedMarker_MarkUserRegenerated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRegeneratedMarker_MarkUserRegenerated_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserRegeneratedMarker_MarkUserRegenerated_Call {
	_c.Call.Return(run)
	return _c
}
