// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/datasources"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRecommendationStateGetter creates a new instance of UserRecommendationStateGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRecommendationStateGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRecommendationStateGetter {
	mock := &UserRecommendationStateGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRecommendationStateGetter is an autogenerated mock type for the UserRecommendationStateGetter type
type UserRecommendationStateGetter struct {
	mock.Mock
}

type UserRecommendationStateGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRecommendationStateGetter) EXPECT() *UserRecommendationStateGetter_Expecter {
	return &UserRecommendationStateGetter_Expecter{mock: &_m.Mock}
}

// GetUserRecommendationState provides a mock function for the type UserRecommendationStateGetter
func (_mock *UserRecommendationStateGetter) GetUserRecommendationState(ctx context.Context, userID string) (datasources.UserRecommendationState, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecommendationState")
	}

	var r0 datasources.UserRecommendationState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (datasources.UserRecommendationState, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) datasources.UserRecommendationState); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(datasources.UserRecommendationState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRecommendationStateGetter_GetUserRecommendationState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRecommendationState'
type UserRecommendationStateGetter_GetUserRecommendationState_Call struct {
	*mock.Call
}

// GetUserRecommendationState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRecommendationStateGetter_Expecter) GetUserRecommendationState(ctx interface{}, userID interface{}) *UserRecommendationStateGetter_GetUserRecommendationState_Call {
	return &UserRecommendationStateGetter_GetUserRecommendationState_Call{Call: _e.mock.On("GetUserRecommendationState", ctx, userID)}
}

func (_c *UserRecommendationStateGetter_GetUserRecommendationState_Call) Run(run func(ctx context.Context, userID string)) *UserRecommendationStateGetter_GetUserRecommendationState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRecommendationStateGetter_GetUserRecommendationState_Call) Return(userRecommendationState datasources.UserRecommendationState, err error) *UserRecommendationStateGetter_GetUserRecommendationState_Call {
	_c.Call.Return(userRecommendationState, err)
	return _c
}

func (_c *UserRecommendationStateGetter_GetUserRecommendationState_Call) RunAndReturn(run func(ctx context.Context, userID string) (datasources.UserRecommendationState, error)) *UserRecommendationStateGetter_GetUserRecommendationState_Call {
	_c.Call.Return(run)
	return _c
}
