// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserAPITokenCounter creates a new instance of UserAPITokenCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserAPITokenCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAPITokenCounter {
	mock := &UserAPITokenCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserAPITokenCounter is an autogenerated mock type for the UserAPITokenCounter type
type UserAPITokenCounter struct {
	mock.Mock
}

type UserAPITokenCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserAPITokenCounter) EXPECT() *UserAPITokenCounter_Expecter {
	return &UserAPITokenCounter_Expecter{mock: &_m.Mock}
}

// CountUserActiveAPITokens provides a mock function for the type UserAPITokenCounter
func (_mock *UserAPITokenCounter) CountUserActiveAPITokens(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUserActiveAPITokens")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserAPITokenCounter_CountUserActiveAPITokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserActiveAPITokens'
type UserAPITokenCounter_CountUserActiveAPITokens_Call struct {
	*mock.Call
}

// CountUserActiveAPITokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserAPITokenCounter_Expecter) CountUserActiveAPITokens(ctx interface{}, userID interface{}) *UserAPITokenCounter_CountUserActiveAPITokens_Call {
	return &UserAPITokenCounter_CountUserActiveAPITokens_Call{Call: _e.mock.On("CountUserActiveAPITokens", ctx, userID)}
}

func (_c *UserAPITokenCounter_CountUserActiveAPITokens_Call) Run(run func(ctx context.Context, userID string)) *UserAPITokenCounter_CountUserActiveAPITokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserAPITokenCounter_CountUserActiveAPITokens_Call) Return(n int64, err error) *UserAPITokenCounter_CountUserActiveAPITokens_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UserAPITokenCounter_CountUserActiveAPITokens_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *UserAPITokenCounter_CountUserActiveAPITokens_Call {
	_c.Call.Return(run)
	return _c
}
