// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserRegenerationNeededMarker creates a new instance of UserRegenerationNeededMarker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRegenerationNeededMarker(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRegenerationNeededMarker {
	mock := &UserRegenerationNeededMarker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRegenerationNeededMarker is an autogenerated mock type for the UserRegenerationNeededMarker type
type UserRegenerationNeededMarker struct {
	mock.Mock
}

type UserRegenerationNeededMarker_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRegenerationNeededMarker) EXPECT() *UserRegenerationNeededMarker_Expecter {
	return &UserRegenerationNeededMarker_Expecter{mock: &_m.Mock}
}

// MarkUserNeedsRegeneration provides a mock function for the type UserRegenerationNeededMarker
func (_mock *UserRegenerationNeededMarker) MarkUserNeedsRegeneration(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserNeedsRegeneration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUserNeedsRegeneration'
type UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call struct {
	*mock.Call
}

// MarkUserNeedsRegeneration is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRegenerationNeededMarker_Expecter) MarkUserNeedsRegeneration(ctx interface{}, userID interface{}) *UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call {
	return &UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call{Call: _e.mock.On("MarkUserNeedsRegeneration", ctx, userID)}
}

func (_c *UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call) Run(run func(ctx context.Context, userID string)) *UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call) Return(err error) *UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserRegenerationNeededMarker_MarkUserNeedsRegeneration_Call {
	_c.Call.Return(run)
	return _c
}
