// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserInterestClusterUpserter creates a new instance of UserInterestClusterUpserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInterestClusterUpserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInterestClusterUpserter {
	mock := &UserInterestClusterUpserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserInterestClusterUpserter is an autogenerated mock type for the UserInterestClusterUpserter type
type UserInterestClusterUpserter struct {
	mock.Mock
}

type UserInterestClusterUpserter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInterestClusterUpserter) EXPECT() *UserInterestClusterUpserter_Expecter {
	return &UserInterestClusterUpserter_Expecter{mock: &_m.Mock}
}

// UpsertUserInterestCluster provides a mock function for the type UserInterestClusterUpserter
func (_mock *UserInterestClusterUpserter) UpsertUserInterestCluster(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int) error {
	ret := _mock.Called(ctx, userID, clusterID, centroidVector, articleCount)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserInterestCluster")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, []float32, int) error); ok {
		r0 = returnFunc(ctx, userID, clusterID, centroidVector, articleCount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserInterestClusterUpserter_UpsertUserInterestCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserInterestCluster'
type UserInterestClusterUpserter_UpsertUserInterestCluster_Call struct {
	*mock.Call
}

// UpsertUserInterestCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - clusterID int
//   - centroidVector []float32
//   - articleCount int
func (_e *UserInterestClusterUpserter_Expecter) UpsertUserInterestCluster(ctx interface{}, userID interface{}, clusterID interface{}, centroidVector interface{}, articleCount interface{}) *UserInterestClusterUpserter_UpsertUserInterestCluster_Call {
	return &UserInterestClusterUpserter_UpsertUserInterestCluster_Call{Call: _e.mock.On("UpsertUserInterestCluster", ctx, userID, clusterID, centroidVector, articleCount)}
}

func (_c *UserInterestClusterUpserter_UpsertUserInterestCluster_Call) Run(run func(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int)) *UserInterestClusterUpserter_UpsertUserInterestCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []float32
		if args[3] != nil {
			arg3 = args[3].([]float32)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UserInterestClusterUpserter_UpsertUserInterestCluster_Call) Return(err error) *UserInterestClusterUpserter_UpsertUserInterestCluster_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserInterestClusterUpserter_UpsertUserInterestCluster_Call) RunAndReturn(run func(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int) error) *UserInterestClusterUpserter_UpsertUserInterestCluster_Call {
	_c.Call.Return(run)
	return _c
}
