// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewUserAPITokenLister creates a new instance of UserAPITokenLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserAPITokenLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAPITokenLister {
	mock := &UserAPITokenLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserAPITokenLister is an autogenerated mock type for the UserAPITokenLister type
type UserAPITokenLister struct {
	mock.Mock
}

type UserAPITokenLister_Expecter struct {
	mock *mock.Mock
}

func (_m *UserAPITokenLister) EXPECT() *UserAPITokenLister_Expecter {
	return &UserAPITokenLister_Expecter{mock: &_m.Mock}
}

// ListUserAPITokens provides a mock function for the type UserAPITokenLister
func (_mock *UserAPITokenLister) ListUserAPITokens(ctx context.Context, userID string) ([]domain.APIToken, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserAPITokens")
	}

	var r0 []domain.APIToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.APIToken, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.APIToken); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.APIToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserAPITokenLister_ListUserAPITokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserAPITokens'
type UserAPITokenLister_ListUserAPITokens_Call struct {
	*mock.Call
}

// ListUserAPITokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserAPITokenLister_Expecter) ListUserAPITokens(ctx interface{}, userID interface{}) *UserAPITokenLister_ListUserAPITokens_Call {
	return &UserAPITokenLister_ListUserAPITokens_Call{Call: _e.mock.On("ListUserAPITokens", ctx, userID)}
}

func (_c *UserAPITokenLister_ListUserAPITokens_Call) Run(run func(ctx context.Context, userID string)) *UserAPITokenLister_ListUserAPITokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserAPITokenLister_ListUserAPITokens_Call) Return(aPITokens []domain.APIToken, err error) *UserAPITokenLister_ListUserAPITokens_Call {
	_c.Call.Return(aPITokens, err)
	return _c
}

func (_c *UserAPITokenLister_ListUserAPITokens_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]domain.APIToken, error)) *UserAPITokenLister_ListUserAPITokens_Call {
	_c.Call.Return(run)
	return _c
}
