// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jbeshir/alignment-research-feed/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewUserArticleVectorsCounter creates a new instance of UserArticleVectorsCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserArticleVectorsCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserArticleVectorsCounter {
	mock := &UserArticleVectorsCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserArticleVectorsCounter is an autogenerated mock type for the UserArticleVectorsCounter type
type UserArticleVectorsCounter struct {
	mock.Mock
}

type UserArticleVectorsCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserArticleVectorsCounter) EXPECT() *UserArticleVectorsCounter_Expecter {
	return &UserArticleVectorsCounter_Expecter{mock: &_m.Mock}
}

// CountUserArticleVectorsByType provides a mock function for the type UserArticleVectorsCounter
func (_mock *UserArticleVectorsCounter) CountUserArticleVectorsByType(ctx context.Context, userID string, ratingType domain.UserRatingType) (int64, error) {
	ret := _mock.Called(ctx, userID, ratingType)

	if len(ret) == 0 {
		panic("no return value specified for CountUserArticleVectorsByType")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) (int64, error)); ok {
		return returnFunc(ctx, userID, ratingType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.UserRatingType) int64); ok {
		r0 = returnFunc(ctx, userID, ratingType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.UserRatingType) error); ok {
		r1 = returnFunc(ctx, userID, ratingType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserArticleVectorsCounter_CountUserArticleVectorsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserArticleVectorsByType'
type UserArticleVectorsCounter_CountUserArticleVectorsByType_Call struct {
	*mock.Call
}

// CountUserArticleVectorsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ratingType domain.UserRatingType
func (_e *UserArticleVectorsCounter_Expecter) CountUserArticleVectorsByType(ctx interface{}, userID interface{}, ratingType interface{}) *UserArticleVectorsCounter_CountUserArticleVectorsByType_Call {
	return &UserArticleVectorsCounter_CountUserArticleVectorsByType_Call{Call: _e.mock.On("CountUserArticleVectorsByType", ctx, userID, ratingType)}
}

func (_c *UserArticleVectorsCounter_CountUserArticleVectorsByType_Call) Run(run func(ctx context.Context, userID string, ratingType domain.UserRatingType)) *UserArticleVectorsCounter_CountUserArticleVectorsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.UserRatingType
		if args[2] != nil {
			arg2 = args[2].(domain.UserRatingType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserArticleVectorsCounter_CountUserArticleVectorsByType_Call) Return(n int64, err error) *UserArticleVectorsCounter_CountUserArticleVectorsByType_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UserArticleVectorsCounter_CountUserArticleVectorsByType_Call) RunAndReturn(run func(ctx context.Context, userID string, ratingType domain.UserRatingType) (int64, error)) *UserArticleVectorsCounter_CountUserArticleVectorsByType_Call {
	_c.Call.Return(run)
	return _c
}
