// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserInterestClusterWriter creates a new instance of UserInterestClusterWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInterestClusterWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInterestClusterWriter {
	mock := &UserInterestClusterWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserInterestClusterWriter is an autogenerated mock type for the UserInterestClusterWriter type
type UserInterestClusterWriter struct {
	mock.Mock
}

type UserInterestClusterWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInterestClusterWriter) EXPECT() *UserInterestClusterWriter_Expecter {
	return &UserInterestClusterWriter_Expecter{mock: &_m.Mock}
}

// DeleteUserInterestClusters provides a mock function for the type UserInterestClusterWriter
func (_mock *UserInterestClusterWriter) DeleteUserInterestClusters(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserInterestClusters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserInterestClusterWriter_DeleteUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserInterestClusters'
type UserInterestClusterWriter_DeleteUserInterestClusters_Call struct {
	*mock.Call
}

// DeleteUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserInterestClusterWriter_Expecter) DeleteUserInterestClusters(ctx interface{}, userID interface{}) *UserInterestClusterWriter_DeleteUserInterestClusters_Call {
	return &UserInterestClusterWriter_DeleteUserInterestClusters_Call{Call: _e.mock.On("DeleteUserInterestClusters", ctx, userID)}
}

func (_c *UserInterestClusterWriter_DeleteUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *UserInterestClusterWriter_DeleteUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInterestClusterWriter_DeleteUserInterestClusters_Call) Return(err error) *UserInterestClusterWriter_DeleteUserInterestClusters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserInterestClusterWriter_DeleteUserInterestClusters_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserInterestClusterWriter_DeleteUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserInterestCluster provides a mock function for the type UserInterestClusterWriter
func (_mock *UserInterestClusterWriter) UpsertUserInterestCluster(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int) error {
	ret := _mock.Called(ctx, userID, clusterID, centroidVector, articleCount)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserInterestCluster")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, []float32, int) error); ok {
		r0 = returnFunc(ctx, userID, clusterID, centroidVector, articleCount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserInterestClusterWriter_UpsertUserInterestCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserInterestCluster'
type UserInterestClusterWriter_UpsertUserInterestCluster_Call struct {
	*mock.Call
}

// UpsertUserInterestCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - clusterID int
//   - centroidVector []float32
//   - articleCount int
func (_e *UserInterestClusterWriter_Expecter) UpsertUserInterestCluster(ctx interface{}, userID interface{}, clusterID interface{}, centroidVector interface{}, articleCount interface{}) *UserInterestClusterWriter_UpsertUserInterestCluster_Call {
	return &UserInterestClusterWriter_UpsertUserInterestCluster_Call{Call: _e.mock.On("UpsertUserInterestCluster", ctx, userID, clusterID, centroidVector, articleCount)}
}

func (_c *UserInterestClusterWriter_UpsertUserInterestCluster_Call) Run(run func(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int)) *UserInterestClusterWriter_UpsertUserInterestCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []float32
		if args[3] != nil {
			arg3 = args[3].([]float32)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UserInterestClusterWriter_UpsertUserInterestCluster_Call) Return(err error) *UserInterestClusterWriter_UpsertUserInterestCluster_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserInterestClusterWriter_UpsertUserInterestCluster_Call) RunAndReturn(run func(ctx context.Context, userID string, clusterID int, centroidVector []float32, articleCount int) error) *UserInterestClusterWriter_UpsertUserInterestCluster_Call {
	_c.Call.Return(run)
	return _c
}
