// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserInterestClusterDeleter creates a new instance of UserInterestClusterDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInterestClusterDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInterestClusterDeleter {
	mock := &UserInterestClusterDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserInterestClusterDeleter is an autogenerated mock type for the UserInterestClusterDeleter type
type UserInterestClusterDeleter struct {
	mock.Mock
}

type UserInterestClusterDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInterestClusterDeleter) EXPECT() *UserInterestClusterDeleter_Expecter {
	return &UserInterestClusterDeleter_Expecter{mock: &_m.Mock}
}

// DeleteUserInterestClusters provides a mock function for the type UserInterestClusterDeleter
func (_mock *UserInterestClusterDeleter) DeleteUserInterestClusters(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserInterestClusters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserInterestClusterDeleter_DeleteUserInterestClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserInterestClusters'
type UserInterestClusterDeleter_DeleteUserInterestClusters_Call struct {
	*mock.Call
}

// DeleteUserInterestClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserInterestClusterDeleter_Expecter) DeleteUserInterestClusters(ctx interface{}, userID interface{}) *UserInterestClusterDeleter_DeleteUserInterestClusters_Call {
	return &UserInterestClusterDeleter_DeleteUserInterestClusters_Call{Call: _e.mock.On("DeleteUserInterestClusters", ctx, userID)}
}

func (_c *UserInterestClusterDeleter_DeleteUserInterestClusters_Call) Run(run func(ctx context.Context, userID string)) *UserInterestClusterDeleter_DeleteUserInterestClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInterestClusterDeleter_DeleteUserInterestClusters_Call) Return(err error) *UserInterestClusterDeleter_DeleteUserInterestClusters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserInterestClusterDeleter_DeleteUserInterestClusters_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserInterestClusterDeleter_DeleteUserInterestClusters_Call {
	_c.Call.Return(run)
	return _c
}
