// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type ArticlesPineconeStatus string

const (
	ArticlesPineconeStatusAbsent          ArticlesPineconeStatus = "absent"
	ArticlesPineconeStatusPendingRemoval  ArticlesPineconeStatus = "pending_removal"
	ArticlesPineconeStatusPendingAddition ArticlesPineconeStatus = "pending_addition"
	ArticlesPineconeStatusAdded           ArticlesPineconeStatus = "added"
)

func (e *ArticlesPineconeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArticlesPineconeStatus(s)
	case string:
		*e = ArticlesPineconeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ArticlesPineconeStatus: %T", src)
	}
	return nil
}

type NullArticlesPineconeStatus struct {
	ArticlesPineconeStatus ArticlesPineconeStatus
	Valid                  bool // Valid is true if ArticlesPineconeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArticlesPineconeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ArticlesPineconeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArticlesPineconeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArticlesPineconeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArticlesPineconeStatus), nil
}

type ApiToken struct {
	ID          string
	UserID      string
	TokenHash   string
	TokenPrefix string
	Name        sql.NullString
	CreatedAt   time.Time
	LastUsedAt  sql.NullTime
	ExpiresAt   sql.NullTime
	RevokedAt   sql.NullTime
}

type Article struct {
	ID            int32
	HashID        string
	Title         sql.NullString
	Url           sql.NullString
	Source        sql.NullString
	SourceType    sql.NullString
	Authors       string
	Text          sql.NullString
	DatePublished sql.NullTime
	Metadata      json.RawMessage
	DateCreated   time.Time
	DateUpdated   sql.NullTime
	Status        sql.NullString
	Comments      sql.NullString
	DateChecked   time.Time
	// How much MIRI wants this in the chatbot
	MiriConfidence sql.NullFloat64
	// Whether this is core or wider from MIRI's perspective
	MiriDistance sql.NullString
	// Whether the article is about technical details
	NeedsTech sql.NullBool
	// Describes the confidence in how good this article is, as a value <0, 1>
	Confidence     sql.NullFloat64
	PineconeStatus ArticlesPineconeStatus
}

type Summary struct {
	ID        int32
	Text      string
	Source    sql.NullString
	ArticleID int32
}

type UserArticleInteraction struct {
	UserID        string
	ArticleHashID string
	HaveRead      bool
	ThumbsUp      bool
	ThumbsDown    bool
	DateRead      sql.NullTime
	DateRated     sql.NullTime
	Vector        sql.NullString
}

type UserInterestCluster struct {
	UserID         string
	ClusterID      int32
	CentroidVector []byte
	ArticleCount   int32
	UpdatedAt      time.Time
}

type UserPrecomputedRecommendation struct {
	UserID        string
	ArticleHashID string
	Score         float64
	Source        string
	Position      int32
	GeneratedAt   time.Time
}

type UserRecommendationState struct {
	UserID            string
	LastGeneratedAt   sql.NullTime
	LastRatingAt      sql.NullTime
	NeedsRegeneration bool
}
