// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Article struct {
	ID             int32
	HashID         string
	Title          sql.NullString
	Url            sql.NullString
	Source         sql.NullString
	SourceType     sql.NullString
	Authors        string
	Text           sql.NullString
	DatePublished  sql.NullTime
	Metadata       json.RawMessage
	DateCreated    time.Time
	DateUpdated    sql.NullTime
	Confidence     sql.NullFloat64
	Status         sql.NullString
	Comments       sql.NullString
	PineconeStatus string
	DateChecked    time.Time
}

type ArticleRating struct {
	ArticleHashID string
	UserID        string
	HaveRead      sql.NullBool
	ThumbsUp      sql.NullBool
	ThumbsDown    sql.NullBool
}

type Summary struct {
	ID        int32
	Text      string
	Source    sql.NullString
	ArticleID int32
}
