// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const fetchArticlesByID = `-- name: FetchArticlesByID :many
SELECT
    hash_id,
    title,
    url,
    source,
    LEFT(COALESCE(text, ''), 500) as text_start,
    authors,
    date_published,
    have_read,
    thumbs_up,
    thumbs_down
FROM articles
LEFT JOIN article_ratings
    ON articles.hash_id = article_ratings.article_hash_id
        AND article_ratings.user_id = ?
WHERE hash_id IN (/*SLICE:hash_ids*/?)
`

type FetchArticlesByIDParams struct {
	UserID  string
	HashIds []string
}

type FetchArticlesByIDRow struct {
	HashID        string
	Title         sql.NullString
	Url           sql.NullString
	Source        sql.NullString
	TextStart     string
	Authors       string
	DatePublished sql.NullTime
	HaveRead      sql.NullBool
	ThumbsUp      sql.NullBool
	ThumbsDown    sql.NullBool
}

func (q *Queries) FetchArticlesByID(ctx context.Context, arg FetchArticlesByIDParams) ([]FetchArticlesByIDRow, error) {
	query := fetchArticlesByID
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.HashIds) > 0 {
		for _, v := range arg.HashIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:hash_ids*/?", strings.Repeat(",?", len(arg.HashIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:hash_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchArticlesByIDRow
	for rows.Next() {
		var i FetchArticlesByIDRow
		if err := rows.Scan(
			&i.HashID,
			&i.Title,
			&i.Url,
			&i.Source,
			&i.TextStart,
			&i.Authors,
			&i.DatePublished,
			&i.HaveRead,
			&i.ThumbsUp,
			&i.ThumbsDown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRatingVectorAdded = `-- name: GetRatingVectorAdded :one
SELECT vector_added FROM article_ratings WHERE user_id = ? AND article_hash_id = ?
`

type GetRatingVectorAddedParams struct {
	UserID        string
	ArticleHashID string
}

func (q *Queries) GetRatingVectorAdded(ctx context.Context, arg GetRatingVectorAddedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, getRatingVectorAdded, arg.UserID, arg.ArticleHashID)
	var vector_added bool
	err := row.Scan(&vector_added)
	return vector_added, err
}

const getUserVector = `-- name: GetUserVector :one
SELECT vector_sum, vector_count FROM user_recommendation_vectors WHERE user_id = ?
`

type GetUserVectorRow struct {
	VectorSum   []byte
	VectorCount int32
}

func (q *Queries) GetUserVector(ctx context.Context, userID string) (GetUserVectorRow, error) {
	row := q.db.QueryRowContext(ctx, getUserVector, userID)
	var i GetUserVectorRow
	err := row.Scan(&i.VectorSum, &i.VectorCount)
	return i, err
}

const insertArticle = `-- name: InsertArticle :exec
INSERT INTO articles (
                      hash_id,
                      title,
                      url,
                      source,
                      text,
                      authors,
                      date_published,
                      date_created,
                      pinecone_status,
                      date_checked) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertArticleParams struct {
	HashID         string
	Title          sql.NullString
	Url            sql.NullString
	Source         sql.NullString
	Text           sql.NullString
	Authors        string
	DatePublished  sql.NullTime
	DateCreated    time.Time
	PineconeStatus ArticlesPineconeStatus
	DateChecked    time.Time
}

func (q *Queries) InsertArticle(ctx context.Context, arg InsertArticleParams) error {
	_, err := q.db.ExecContext(ctx, insertArticle,
		arg.HashID,
		arg.Title,
		arg.Url,
		arg.Source,
		arg.Text,
		arg.Authors,
		arg.DatePublished,
		arg.DateCreated,
		arg.PineconeStatus,
		arg.DateChecked,
	)
	return err
}

const listThumbsUpArticleIDs = `-- name: ListThumbsUpArticleIDs :many
SELECT article_hash_id FROM article_ratings
WHERE user_id = ? AND thumbs_up = TRUE
`

func (q *Queries) ListThumbsUpArticleIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listThumbsUpArticleIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var article_hash_id string
		if err := rows.Scan(&article_hash_id); err != nil {
			return nil, err
		}
		items = append(items, article_hash_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArticleRead = `-- name: SetArticleRead :exec
INSERT INTO article_ratings (
        article_hash_id,
        user_id,
        have_read,
        thumbs_up,
        thumbs_down
    ) VALUES (?, ?, ?, FALSE, FALSE)
ON DUPLICATE KEY UPDATE have_read = ?
`

type SetArticleReadParams struct {
	ArticleHashID string
	UserID        string
	HaveRead      sql.NullBool
}

func (q *Queries) SetArticleRead(ctx context.Context, arg SetArticleReadParams) error {
	_, err := q.db.ExecContext(ctx, setArticleRead,
		arg.ArticleHashID,
		arg.UserID,
		arg.HaveRead,
		arg.HaveRead,
	)
	return err
}

const setArticleThumbsDown = `-- name: SetArticleThumbsDown :exec
INSERT INTO article_ratings (
        article_hash_id,
        user_id,
        have_read,
        thumbs_up,
        thumbs_down
    ) VALUES (?, ?, FALSE, FALSE, ?)
ON DUPLICATE KEY UPDATE
    thumbs_down = ?,
    thumbs_up = IF(?, FALSE, thumbs_up)
`

type SetArticleThumbsDownParams struct {
	ArticleHashID string
	UserID        string
	ThumbsDown    sql.NullBool
}

func (q *Queries) SetArticleThumbsDown(ctx context.Context, arg SetArticleThumbsDownParams) error {
	_, err := q.db.ExecContext(ctx, setArticleThumbsDown,
		arg.ArticleHashID,
		arg.UserID,
		arg.ThumbsDown,
		arg.ThumbsDown,
		arg.ThumbsDown,
	)
	return err
}

const setArticleThumbsUp = `-- name: SetArticleThumbsUp :exec
INSERT INTO article_ratings (
        article_hash_id,
        user_id,
        have_read,
        thumbs_up,
        thumbs_down
    ) VALUES (?, ?, FALSE, ?, FALSE)
ON DUPLICATE KEY UPDATE
    thumbs_up = ?,
    thumbs_down = IF(?, FALSE, thumbs_down)
`

type SetArticleThumbsUpParams struct {
	ArticleHashID string
	UserID        string
	ThumbsUp      sql.NullBool
}

func (q *Queries) SetArticleThumbsUp(ctx context.Context, arg SetArticleThumbsUpParams) error {
	_, err := q.db.ExecContext(ctx, setArticleThumbsUp,
		arg.ArticleHashID,
		arg.UserID,
		arg.ThumbsUp,
		arg.ThumbsUp,
		arg.ThumbsUp,
	)
	return err
}

const setRatingVectorAdded = `-- name: SetRatingVectorAdded :exec
UPDATE article_ratings SET vector_added = ? WHERE user_id = ? AND article_hash_id = ?
`

type SetRatingVectorAddedParams struct {
	VectorAdded   bool
	UserID        string
	ArticleHashID string
}

func (q *Queries) SetRatingVectorAdded(ctx context.Context, arg SetRatingVectorAddedParams) error {
	_, err := q.db.ExecContext(ctx, setRatingVectorAdded, arg.VectorAdded, arg.UserID, arg.ArticleHashID)
	return err
}

const updateUserVectorSubtract = `-- name: UpdateUserVectorSubtract :exec
UPDATE user_recommendation_vectors
SET vector_sum = ?, vector_count = vector_count - 1, updated_at = NOW()
WHERE user_id = ?
`

type UpdateUserVectorSubtractParams struct {
	VectorSum []byte
	UserID    string
}

func (q *Queries) UpdateUserVectorSubtract(ctx context.Context, arg UpdateUserVectorSubtractParams) error {
	_, err := q.db.ExecContext(ctx, updateUserVectorSubtract, arg.VectorSum, arg.UserID)
	return err
}

const upsertUserVectorAdd = `-- name: UpsertUserVectorAdd :exec
INSERT INTO user_recommendation_vectors (user_id, vector_sum, vector_count, updated_at)
VALUES (?, ?, 1, NOW())
ON DUPLICATE KEY UPDATE
    vector_sum = ?,
    vector_count = vector_count + 1,
    updated_at = NOW()
`

type UpsertUserVectorAddParams struct {
	UserID      string
	VectorSum   []byte
	VectorSum_2 []byte
}

func (q *Queries) UpsertUserVectorAdd(ctx context.Context, arg UpsertUserVectorAddParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserVectorAdd, arg.UserID, arg.VectorSum, arg.VectorSum_2)
	return err
}
