with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  github.com/jbeshir/alignment-research-feed/internal/datasources:
    interfaces:
      ArticleFetcher:
      ArticleReadSetter:
      ArticleThumbsUpSetter:
      ArticleThumbsDownSetter:
      LatestArticleLister:
      ThumbsUpArticleLister:
      UserVectorGetter:
      UserVectorSyncer:
      SimilarArticleLister:
      ArticleVectorFetcher:
      SimilarArticlesByVectorLister:
