with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  github.com/jbeshir/alignment-research-feed/internal/datasources:
    config:
      all: true
  github.com/jbeshir/alignment-research-feed/internal/command:
    config:
      all: true
