dir: '{{.InterfaceDir}}/mocks'
filename: '{{.InterfaceName | snakecase}}.go'
structname: '{{.InterfaceName}}'
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/jbeshir/alignment-research-feed/internal/command:
    config:
      all: true
  github.com/jbeshir/alignment-research-feed/internal/datasources:
    config:
      all: true
