// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCommand creates a new instance of Command. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommand[Req any, Res any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Command[Req, Res] {
	mock := &Command[Req, Res]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Command is an autogenerated mock type for the Command type
type Command[Req any, Res any] struct {
	mock.Mock
}

type Command_Expecter[Req any, Res any] struct {
	mock *mock.Mock
}

func (_m *Command[Req, Res]) EXPECT() *Command_Expecter[Req, Res] {
	return &Command_Expecter[Req, Res]{mock: &_m.Mock}
}

// Execute provides a mock function for the type Command
func (_mock *Command[Req, Res]) Execute(ctx context.Context, req Req) (Res, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 Res
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Req) (Res, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Req) Res); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Res)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Req) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Command_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Command_Execute_Call[Req any, Res any] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req Req
func (_e *Command_Expecter[Req, Res]) Execute(ctx interface{}, req interface{}) *Command_Execute_Call[Req, Res] {
	return &Command_Execute_Call[Req, Res]{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *Command_Execute_Call[Req, Res]) Run(run func(ctx context.Context, req Req)) *Command_Execute_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Req
		if args[1] != nil {
			arg1 = args[1].(Req)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Command_Execute_Call[Req, Res]) Return(v Res, err error) *Command_Execute_Call[Req, Res] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Command_Execute_Call[Req, Res]) RunAndReturn(run func(ctx context.Context, req Req) (Res, error)) *Command_Execute_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}
