// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCommand is an autogenerated mock type for the Command type
type MockCommand[Req interface{}, Res interface{}] struct {
	mock.Mock
}

type MockCommand_Expecter[Req interface{}, Res interface{}] struct {
	mock *mock.Mock
}

func (_m *MockCommand[Req, Res]) EXPECT() *MockCommand_Expecter[Req, Res] {
	return &MockCommand_Expecter[Req, Res]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, req
func (_m *MockCommand[Req, Res]) Execute(ctx context.Context, req Req) (Res, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 Res
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Req) (Res, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Req) Res); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Res)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Req) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommand_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommand_Execute_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req Req
func (_e *MockCommand_Expecter[Req, Res]) Execute(ctx interface{}, req interface{}) *MockCommand_Execute_Call[Req, Res] {
	return &MockCommand_Execute_Call[Req, Res]{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockCommand_Execute_Call[Req, Res]) Run(run func(ctx context.Context, req Req)) *MockCommand_Execute_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Req))
	})
	return _c
}

func (_c *MockCommand_Execute_Call[Req, Res]) Return(_a0 Res, _a1 error) *MockCommand_Execute_Call[Req, Res] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommand_Execute_Call[Req, Res]) RunAndReturn(run func(context.Context, Req) (Res, error)) *MockCommand_Execute_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// NewMockCommand creates a new instance of MockCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommand[Req interface{}, Res interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommand[Req, Res] {
	mock := &MockCommand[Req, Res]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
