name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Lint
        run: make lint

  lint-openapi:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install vacuum
        run: go install github.com/daveshanley/vacuum@latest

      - name: Lint OpenAPI spec
        run: make lint-openapi

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup env
        run: make setup-files

      - name: Run dockerized tests
        run: make docker-test
